namespace DazaBestApplication.Modals
{
    partial class ForgotPasswordModal
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ForgotPasswordModal));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            pictureBox1 = new PictureBox();
            btncancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            label1 = new Label();
            btnNext = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            label2 = new Label();
            ForgotEmailTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            QuestionPanel = new Panel();
            label10 = new Label();
            label9 = new Label();
            label8 = new Label();
            panel1 = new Panel();
            panel5 = new Panel();
            label6 = new Label();
            pictureBox2 = new PictureBox();
            BackBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ValidateBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            Ans3txt = new Bunifu.UI.WinForms.BunifuTextBox();
            Ans2txt = new Bunifu.UI.WinForms.BunifuTextBox();
            Ans1txt = new Bunifu.UI.WinForms.BunifuTextBox();
            ResetPassPanel = new Panel();
            label5 = new Label();
            label4 = new Label();
            bunifuTextBox2 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            panel4 = new Panel();
            CancelBtn2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ResetPassBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            panel2 = new Panel();
            panel3 = new Panel();
            label3 = new Label();
            panel6 = new Panel();
            panel7 = new Panel();
            label7 = new Label();
            ((System.ComponentModel.ISupportInitialize)pictureBox1).BeginInit();
            QuestionPanel.SuspendLayout();
            panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox2).BeginInit();
            ResetPassPanel.SuspendLayout();
            panel4.SuspendLayout();
            panel2.SuspendLayout();
            panel6.SuspendLayout();
            SuspendLayout();
            // 
            // pictureBox1
            // 
            pictureBox1.Image = Properties.Resources._try;
            pictureBox1.Location = new Point(37, 58);
            pictureBox1.Name = "pictureBox1";
            pictureBox1.Size = new Size(300, 300);
            pictureBox1.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox1.TabIndex = 0;
            pictureBox1.TabStop = false;
            // 
            // btncancel
            // 
            btncancel.AllowAnimations = true;
            btncancel.AllowMouseEffects = true;
            btncancel.AllowToggling = false;
            btncancel.AnimationSpeed = 200;
            btncancel.AutoGenerateColors = false;
            btncancel.AutoRoundBorders = false;
            btncancel.AutoSizeLeftIcon = true;
            btncancel.AutoSizeRightIcon = true;
            btncancel.BackColor = Color.Transparent;
            btncancel.BackColor1 = Color.FromArgb(51, 122, 183);
            btncancel.BackgroundImage = (Image)resources.GetObject("btncancel.BackgroundImage");
            btncancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btncancel.ButtonText = "Cancel";
            btncancel.ButtonTextMarginLeft = 0;
            btncancel.ColorContrastOnClick = 45;
            btncancel.ColorContrastOnHover = 45;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            btncancel.CustomizableEdges = borderEdges1;
            btncancel.DialogResult = DialogResult.None;
            btncancel.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btncancel.DisabledFillColor = Color.Empty;
            btncancel.DisabledForecolor = Color.Empty;
            btncancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            btncancel.Font = new Font("Segoe UI", 9F);
            btncancel.ForeColor = Color.White;
            btncancel.IconLeft = null;
            btncancel.IconLeftAlign = ContentAlignment.MiddleLeft;
            btncancel.IconLeftCursor = Cursors.Default;
            btncancel.IconLeftPadding = new Padding(11, 3, 3, 3);
            btncancel.IconMarginLeft = 11;
            btncancel.IconPadding = 10;
            btncancel.IconRight = null;
            btncancel.IconRightAlign = ContentAlignment.MiddleRight;
            btncancel.IconRightCursor = Cursors.Default;
            btncancel.IconRightPadding = new Padding(3, 3, 7, 3);
            btncancel.IconSize = 25;
            btncancel.IdleBorderColor = Color.Empty;
            btncancel.IdleBorderRadius = 0;
            btncancel.IdleBorderThickness = 0;
            btncancel.IdleFillColor = Color.Empty;
            btncancel.IdleIconLeftImage = null;
            btncancel.IdleIconRightImage = null;
            btncancel.IndicateFocus = false;
            btncancel.Location = new Point(417, 319);
            btncancel.Name = "btncancel";
            btncancel.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btncancel.OnDisabledState.BorderRadius = 1;
            btncancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btncancel.OnDisabledState.BorderThickness = 1;
            btncancel.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btncancel.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btncancel.OnDisabledState.IconLeftImage = null;
            btncancel.OnDisabledState.IconRightImage = null;
            btncancel.onHoverState.BorderColor = Color.FromArgb(192, 74, 62);
            btncancel.onHoverState.BorderRadius = 1;
            btncancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btncancel.onHoverState.BorderThickness = 1;
            btncancel.onHoverState.FillColor = Color.FromArgb(192, 74, 62);
            btncancel.onHoverState.ForeColor = Color.White;
            btncancel.onHoverState.IconLeftImage = null;
            btncancel.onHoverState.IconRightImage = null;
            btncancel.OnIdleState.BorderColor = Color.FromArgb(192, 57, 43);
            btncancel.OnIdleState.BorderRadius = 1;
            btncancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btncancel.OnIdleState.BorderThickness = 1;
            btncancel.OnIdleState.FillColor = Color.FromArgb(192, 57, 43);
            btncancel.OnIdleState.ForeColor = Color.White;
            btncancel.OnIdleState.IconLeftImage = null;
            btncancel.OnIdleState.IconRightImage = null;
            btncancel.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btncancel.OnPressedState.BorderRadius = 1;
            btncancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btncancel.OnPressedState.BorderThickness = 1;
            btncancel.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btncancel.OnPressedState.ForeColor = Color.White;
            btncancel.OnPressedState.IconLeftImage = null;
            btncancel.OnPressedState.IconRightImage = null;
            btncancel.Size = new Size(150, 39);
            btncancel.TabIndex = 1;
            btncancel.TextAlign = ContentAlignment.MiddleCenter;
            btncancel.TextAlignment = HorizontalAlignment.Center;
            btncancel.TextMarginLeft = 0;
            btncancel.TextPadding = new Padding(0);
            btncancel.UseDefaultRadiusAndThickness = true;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Courier New", 27.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label1.ForeColor = Color.FromArgb(192, 57, 43);
            label1.Location = new Point(419, 59);
            label1.Name = "label1";
            label1.Size = new Size(216, 82);
            label1.TabIndex = 2;
            label1.Text = "Forgot\r\nPassword?";
            // 
            // btnNext
            // 
            btnNext.AllowAnimations = true;
            btnNext.AllowMouseEffects = true;
            btnNext.AllowToggling = false;
            btnNext.AnimationSpeed = 200;
            btnNext.AutoGenerateColors = false;
            btnNext.AutoRoundBorders = false;
            btnNext.AutoSizeLeftIcon = true;
            btnNext.AutoSizeRightIcon = true;
            btnNext.BackColor = Color.Transparent;
            btnNext.BackColor1 = Color.FromArgb(51, 122, 183);
            btnNext.BackgroundImage = (Image)resources.GetObject("btnNext.BackgroundImage");
            btnNext.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnNext.ButtonText = "Next";
            btnNext.ButtonTextMarginLeft = 0;
            btnNext.ColorContrastOnClick = 45;
            btnNext.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            btnNext.CustomizableEdges = borderEdges2;
            btnNext.DialogResult = DialogResult.None;
            btnNext.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnNext.DisabledFillColor = Color.Empty;
            btnNext.DisabledForecolor = Color.Empty;
            btnNext.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            btnNext.Font = new Font("Segoe UI", 9F);
            btnNext.ForeColor = Color.White;
            btnNext.IconLeft = null;
            btnNext.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnNext.IconLeftCursor = Cursors.Default;
            btnNext.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnNext.IconMarginLeft = 11;
            btnNext.IconPadding = 10;
            btnNext.IconRight = null;
            btnNext.IconRightAlign = ContentAlignment.MiddleRight;
            btnNext.IconRightCursor = Cursors.Default;
            btnNext.IconRightPadding = new Padding(3, 3, 7, 3);
            btnNext.IconSize = 25;
            btnNext.IdleBorderColor = Color.Empty;
            btnNext.IdleBorderRadius = 0;
            btnNext.IdleBorderThickness = 0;
            btnNext.IdleFillColor = Color.Empty;
            btnNext.IdleIconLeftImage = null;
            btnNext.IdleIconRightImage = null;
            btnNext.IndicateFocus = false;
            btnNext.Location = new Point(596, 319);
            btnNext.Name = "btnNext";
            btnNext.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnNext.OnDisabledState.BorderRadius = 1;
            btnNext.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnNext.OnDisabledState.BorderThickness = 1;
            btnNext.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnNext.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnNext.OnDisabledState.IconLeftImage = null;
            btnNext.OnDisabledState.IconRightImage = null;
            btnNext.onHoverState.BorderColor = Color.FromArgb(192, 74, 62);
            btnNext.onHoverState.BorderRadius = 1;
            btnNext.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnNext.onHoverState.BorderThickness = 1;
            btnNext.onHoverState.FillColor = Color.FromArgb(192, 74, 62);
            btnNext.onHoverState.ForeColor = Color.White;
            btnNext.onHoverState.IconLeftImage = null;
            btnNext.onHoverState.IconRightImage = null;
            btnNext.OnIdleState.BorderColor = Color.FromArgb(192, 57, 43);
            btnNext.OnIdleState.BorderRadius = 1;
            btnNext.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnNext.OnIdleState.BorderThickness = 1;
            btnNext.OnIdleState.FillColor = Color.FromArgb(192, 57, 43);
            btnNext.OnIdleState.ForeColor = Color.White;
            btnNext.OnIdleState.IconLeftImage = null;
            btnNext.OnIdleState.IconRightImage = null;
            btnNext.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnNext.OnPressedState.BorderRadius = 1;
            btnNext.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnNext.OnPressedState.BorderThickness = 1;
            btnNext.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnNext.OnPressedState.ForeColor = Color.White;
            btnNext.OnPressedState.IconLeftImage = null;
            btnNext.OnPressedState.IconRightImage = null;
            btnNext.Size = new Size(150, 39);
            btnNext.TabIndex = 3;
            btnNext.TextAlign = ContentAlignment.MiddleCenter;
            btnNext.TextAlignment = HorizontalAlignment.Center;
            btnNext.TextMarginLeft = 0;
            btnNext.TextPadding = new Padding(0);
            btnNext.UseDefaultRadiusAndThickness = true;
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Courier New", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label2.Location = new Point(419, 178);
            label2.Name = "label2";
            label2.Size = new Size(327, 16);
            label2.TabIndex = 4;
            label2.Text = "Enter your username to find your account";
            // 
            // ForgotEmailTxt
            // 
            ForgotEmailTxt.AcceptsReturn = false;
            ForgotEmailTxt.AcceptsTab = false;
            ForgotEmailTxt.AnimationSpeed = 200;
            ForgotEmailTxt.AutoCompleteMode = AutoCompleteMode.None;
            ForgotEmailTxt.AutoCompleteSource = AutoCompleteSource.None;
            ForgotEmailTxt.AutoSizeHeight = true;
            ForgotEmailTxt.BackColor = Color.Transparent;
            ForgotEmailTxt.BackgroundImage = (Image)resources.GetObject("ForgotEmailTxt.BackgroundImage");
            ForgotEmailTxt.BorderColorActive = Color.DodgerBlue;
            ForgotEmailTxt.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            ForgotEmailTxt.BorderColorHover = Color.FromArgb(105, 181, 255);
            ForgotEmailTxt.BorderColorIdle = Color.Silver;
            ForgotEmailTxt.BorderRadius = 1;
            ForgotEmailTxt.BorderThickness = 1;
            ForgotEmailTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            ForgotEmailTxt.CharacterCasing = CharacterCasing.Normal;
            ForgotEmailTxt.DefaultFont = new Font("Segoe UI", 9.25F);
            ForgotEmailTxt.DefaultText = "";
            ForgotEmailTxt.FillColor = Color.White;
            ForgotEmailTxt.HideSelection = true;
            ForgotEmailTxt.IconLeft = null;
            ForgotEmailTxt.IconLeftCursor = Cursors.IBeam;
            ForgotEmailTxt.IconPadding = 10;
            ForgotEmailTxt.IconRight = null;
            ForgotEmailTxt.IconRightCursor = Cursors.IBeam;
            ForgotEmailTxt.Location = new Point(419, 229);
            ForgotEmailTxt.MaxLength = 32767;
            ForgotEmailTxt.MinimumSize = new Size(1, 1);
            ForgotEmailTxt.Modified = false;
            ForgotEmailTxt.Multiline = false;
            ForgotEmailTxt.Name = "ForgotEmailTxt";
            stateProperties1.BorderColor = Color.DodgerBlue;
            stateProperties1.FillColor = Color.Empty;
            stateProperties1.ForeColor = Color.Empty;
            stateProperties1.PlaceholderForeColor = Color.Empty;
            ForgotEmailTxt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties2.PlaceholderForeColor = Color.DarkGray;
            ForgotEmailTxt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties3.FillColor = Color.Empty;
            stateProperties3.ForeColor = Color.Empty;
            stateProperties3.PlaceholderForeColor = Color.Empty;
            ForgotEmailTxt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = Color.Silver;
            stateProperties4.FillColor = Color.White;
            stateProperties4.ForeColor = Color.Empty;
            stateProperties4.PlaceholderForeColor = Color.Empty;
            ForgotEmailTxt.OnIdleState = stateProperties4;
            ForgotEmailTxt.Padding = new Padding(3);
            ForgotEmailTxt.PasswordChar = '\0';
            ForgotEmailTxt.PlaceholderForeColor = Color.Silver;
            ForgotEmailTxt.PlaceholderText = "Enter text";
            ForgotEmailTxt.ReadOnly = false;
            ForgotEmailTxt.ScrollBars = ScrollBars.None;
            ForgotEmailTxt.SelectedText = "";
            ForgotEmailTxt.SelectionLength = 0;
            ForgotEmailTxt.SelectionStart = 0;
            ForgotEmailTxt.ShortcutsEnabled = true;
            ForgotEmailTxt.Size = new Size(329, 39);
            ForgotEmailTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            ForgotEmailTxt.TabIndex = 5;
            ForgotEmailTxt.TextAlign = HorizontalAlignment.Left;
            ForgotEmailTxt.TextMarginBottom = 0;
            ForgotEmailTxt.TextMarginLeft = 3;
            ForgotEmailTxt.TextMarginTop = 1;
            ForgotEmailTxt.TextPlaceholder = "Enter text";
            ForgotEmailTxt.UseSystemPasswordChar = false;
            ForgotEmailTxt.WordWrap = true;
            // 
            // QuestionPanel
            // 
            QuestionPanel.Controls.Add(label10);
            QuestionPanel.Controls.Add(label9);
            QuestionPanel.Controls.Add(label8);
            QuestionPanel.Controls.Add(panel1);
            QuestionPanel.Controls.Add(pictureBox2);
            QuestionPanel.Controls.Add(BackBtn);
            QuestionPanel.Controls.Add(ValidateBtn);
            QuestionPanel.Controls.Add(Ans3txt);
            QuestionPanel.Controls.Add(Ans2txt);
            QuestionPanel.Controls.Add(Ans1txt);
            QuestionPanel.Location = new Point(700, 300);
            QuestionPanel.Name = "QuestionPanel";
            QuestionPanel.Size = new Size(800, 450);
            QuestionPanel.TabIndex = 6;
            // 
            // label10
            // 
            label10.BorderStyle = BorderStyle.FixedSingle;
            label10.Font = new Font("Courier New", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label10.Location = new Point(343, 271);
            label10.Name = "label10";
            label10.Size = new Size(388, 32);
            label10.TabIndex = 12;
            label10.Text = "Question3";
            // 
            // label9
            // 
            label9.BorderStyle = BorderStyle.FixedSingle;
            label9.Font = new Font("Courier New", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label9.Location = new Point(343, 171);
            label9.Name = "label9";
            label9.Size = new Size(388, 32);
            label9.TabIndex = 11;
            label9.Text = "Question2";
            // 
            // label8
            // 
            label8.BorderStyle = BorderStyle.FixedSingle;
            label8.Font = new Font("Courier New", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label8.Location = new Point(343, 70);
            label8.Name = "label8";
            label8.Size = new Size(388, 32);
            label8.TabIndex = 10;
            label8.Text = "Question1";
            // 
            // panel1
            // 
            panel1.BackColor = Color.White;
            panel1.Controls.Add(panel5);
            panel1.Controls.Add(label6);
            panel1.Dock = DockStyle.Top;
            panel1.Location = new Point(0, 0);
            panel1.Name = "panel1";
            panel1.Size = new Size(800, 40);
            panel1.TabIndex = 9;
            // 
            // panel5
            // 
            panel5.BackColor = Color.Maroon;
            panel5.Dock = DockStyle.Bottom;
            panel5.Location = new Point(0, 35);
            panel5.Name = "panel5";
            panel5.Size = new Size(800, 5);
            panel5.TabIndex = 3;
            // 
            // label6
            // 
            label6.BackColor = Color.Transparent;
            label6.Font = new Font("Courier New", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label6.Location = new Point(10, 0);
            label6.Name = "label6";
            label6.Size = new Size(154, 33);
            label6.TabIndex = 0;
            label6.Text = "Reset Password";
            label6.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // pictureBox2
            // 
            pictureBox2.Image = Properties.Resources._try;
            pictureBox2.Location = new Point(21, 62);
            pictureBox2.Name = "pictureBox2";
            pictureBox2.Size = new Size(300, 300);
            pictureBox2.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox2.TabIndex = 8;
            pictureBox2.TabStop = false;
            // 
            // BackBtn
            // 
            BackBtn.AllowAnimations = true;
            BackBtn.AllowMouseEffects = true;
            BackBtn.AllowToggling = false;
            BackBtn.AnimationSpeed = 200;
            BackBtn.AutoGenerateColors = false;
            BackBtn.AutoRoundBorders = false;
            BackBtn.AutoSizeLeftIcon = true;
            BackBtn.AutoSizeRightIcon = true;
            BackBtn.BackColor = Color.Transparent;
            BackBtn.BackColor1 = Color.FromArgb(51, 122, 183);
            BackBtn.BackgroundImage = (Image)resources.GetObject("BackBtn.BackgroundImage");
            BackBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BackBtn.ButtonText = "Back";
            BackBtn.ButtonTextMarginLeft = 0;
            BackBtn.ColorContrastOnClick = 45;
            BackBtn.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            BackBtn.CustomizableEdges = borderEdges3;
            BackBtn.DialogResult = DialogResult.None;
            BackBtn.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            BackBtn.DisabledFillColor = Color.Empty;
            BackBtn.DisabledForecolor = Color.Empty;
            BackBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            BackBtn.Font = new Font("Segoe UI", 9F);
            BackBtn.ForeColor = Color.White;
            BackBtn.IconLeft = null;
            BackBtn.IconLeftAlign = ContentAlignment.MiddleLeft;
            BackBtn.IconLeftCursor = Cursors.Default;
            BackBtn.IconLeftPadding = new Padding(11, 3, 3, 3);
            BackBtn.IconMarginLeft = 11;
            BackBtn.IconPadding = 10;
            BackBtn.IconRight = null;
            BackBtn.IconRightAlign = ContentAlignment.MiddleRight;
            BackBtn.IconRightCursor = Cursors.Default;
            BackBtn.IconRightPadding = new Padding(3, 3, 7, 3);
            BackBtn.IconSize = 25;
            BackBtn.IdleBorderColor = Color.Empty;
            BackBtn.IdleBorderRadius = 0;
            BackBtn.IdleBorderThickness = 0;
            BackBtn.IdleFillColor = Color.Empty;
            BackBtn.IdleIconLeftImage = null;
            BackBtn.IdleIconRightImage = null;
            BackBtn.IndicateFocus = false;
            BackBtn.Location = new Point(412, 387);
            BackBtn.Name = "BackBtn";
            BackBtn.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            BackBtn.OnDisabledState.BorderRadius = 1;
            BackBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BackBtn.OnDisabledState.BorderThickness = 1;
            BackBtn.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            BackBtn.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            BackBtn.OnDisabledState.IconLeftImage = null;
            BackBtn.OnDisabledState.IconRightImage = null;
            BackBtn.onHoverState.BorderColor = Color.FromArgb(192, 74, 62);
            BackBtn.onHoverState.BorderRadius = 1;
            BackBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BackBtn.onHoverState.BorderThickness = 1;
            BackBtn.onHoverState.FillColor = Color.FromArgb(192, 74, 62);
            BackBtn.onHoverState.ForeColor = Color.White;
            BackBtn.onHoverState.IconLeftImage = null;
            BackBtn.onHoverState.IconRightImage = null;
            BackBtn.OnIdleState.BorderColor = Color.FromArgb(192, 57, 43);
            BackBtn.OnIdleState.BorderRadius = 1;
            BackBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BackBtn.OnIdleState.BorderThickness = 1;
            BackBtn.OnIdleState.FillColor = Color.FromArgb(192, 57, 43);
            BackBtn.OnIdleState.ForeColor = Color.White;
            BackBtn.OnIdleState.IconLeftImage = null;
            BackBtn.OnIdleState.IconRightImage = null;
            BackBtn.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            BackBtn.OnPressedState.BorderRadius = 1;
            BackBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BackBtn.OnPressedState.BorderThickness = 1;
            BackBtn.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            BackBtn.OnPressedState.ForeColor = Color.White;
            BackBtn.OnPressedState.IconLeftImage = null;
            BackBtn.OnPressedState.IconRightImage = null;
            BackBtn.Size = new Size(155, 39);
            BackBtn.TabIndex = 7;
            BackBtn.TextAlign = ContentAlignment.MiddleCenter;
            BackBtn.TextAlignment = HorizontalAlignment.Center;
            BackBtn.TextMarginLeft = 0;
            BackBtn.TextPadding = new Padding(0);
            BackBtn.UseDefaultRadiusAndThickness = true;
            // 
            // ValidateBtn
            // 
            ValidateBtn.AllowAnimations = true;
            ValidateBtn.AllowMouseEffects = true;
            ValidateBtn.AllowToggling = false;
            ValidateBtn.AnimationSpeed = 200;
            ValidateBtn.AutoGenerateColors = false;
            ValidateBtn.AutoRoundBorders = false;
            ValidateBtn.AutoSizeLeftIcon = true;
            ValidateBtn.AutoSizeRightIcon = true;
            ValidateBtn.BackColor = Color.Transparent;
            ValidateBtn.BackColor1 = Color.FromArgb(51, 122, 183);
            ValidateBtn.BackgroundImage = (Image)resources.GetObject("ValidateBtn.BackgroundImage");
            ValidateBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ValidateBtn.ButtonText = "Validate";
            ValidateBtn.ButtonTextMarginLeft = 0;
            ValidateBtn.ColorContrastOnClick = 45;
            ValidateBtn.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            ValidateBtn.CustomizableEdges = borderEdges4;
            ValidateBtn.DialogResult = DialogResult.None;
            ValidateBtn.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            ValidateBtn.DisabledFillColor = Color.Empty;
            ValidateBtn.DisabledForecolor = Color.Empty;
            ValidateBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            ValidateBtn.Font = new Font("Segoe UI", 9F);
            ValidateBtn.ForeColor = Color.White;
            ValidateBtn.IconLeft = null;
            ValidateBtn.IconLeftAlign = ContentAlignment.MiddleLeft;
            ValidateBtn.IconLeftCursor = Cursors.Default;
            ValidateBtn.IconLeftPadding = new Padding(11, 3, 3, 3);
            ValidateBtn.IconMarginLeft = 11;
            ValidateBtn.IconPadding = 10;
            ValidateBtn.IconRight = null;
            ValidateBtn.IconRightAlign = ContentAlignment.MiddleRight;
            ValidateBtn.IconRightCursor = Cursors.Default;
            ValidateBtn.IconRightPadding = new Padding(3, 3, 7, 3);
            ValidateBtn.IconSize = 25;
            ValidateBtn.IdleBorderColor = Color.Empty;
            ValidateBtn.IdleBorderRadius = 0;
            ValidateBtn.IdleBorderThickness = 0;
            ValidateBtn.IdleFillColor = Color.Empty;
            ValidateBtn.IdleIconLeftImage = null;
            ValidateBtn.IdleIconRightImage = null;
            ValidateBtn.IndicateFocus = false;
            ValidateBtn.Location = new Point(576, 387);
            ValidateBtn.Name = "ValidateBtn";
            ValidateBtn.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            ValidateBtn.OnDisabledState.BorderRadius = 1;
            ValidateBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ValidateBtn.OnDisabledState.BorderThickness = 1;
            ValidateBtn.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            ValidateBtn.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            ValidateBtn.OnDisabledState.IconLeftImage = null;
            ValidateBtn.OnDisabledState.IconRightImage = null;
            ValidateBtn.onHoverState.BorderColor = Color.FromArgb(192, 74, 62);
            ValidateBtn.onHoverState.BorderRadius = 1;
            ValidateBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ValidateBtn.onHoverState.BorderThickness = 1;
            ValidateBtn.onHoverState.FillColor = Color.FromArgb(192, 74, 62);
            ValidateBtn.onHoverState.ForeColor = Color.White;
            ValidateBtn.onHoverState.IconLeftImage = null;
            ValidateBtn.onHoverState.IconRightImage = null;
            ValidateBtn.OnIdleState.BorderColor = Color.FromArgb(192, 57, 43);
            ValidateBtn.OnIdleState.BorderRadius = 1;
            ValidateBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ValidateBtn.OnIdleState.BorderThickness = 1;
            ValidateBtn.OnIdleState.FillColor = Color.FromArgb(192, 57, 43);
            ValidateBtn.OnIdleState.ForeColor = Color.White;
            ValidateBtn.OnIdleState.IconLeftImage = null;
            ValidateBtn.OnIdleState.IconRightImage = null;
            ValidateBtn.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            ValidateBtn.OnPressedState.BorderRadius = 1;
            ValidateBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ValidateBtn.OnPressedState.BorderThickness = 1;
            ValidateBtn.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            ValidateBtn.OnPressedState.ForeColor = Color.White;
            ValidateBtn.OnPressedState.IconLeftImage = null;
            ValidateBtn.OnPressedState.IconRightImage = null;
            ValidateBtn.Size = new Size(155, 39);
            ValidateBtn.TabIndex = 6;
            ValidateBtn.TextAlign = ContentAlignment.MiddleCenter;
            ValidateBtn.TextAlignment = HorizontalAlignment.Center;
            ValidateBtn.TextMarginLeft = 0;
            ValidateBtn.TextPadding = new Padding(0);
            ValidateBtn.UseDefaultRadiusAndThickness = true;
            ValidateBtn.Click += ValidateBtn_Click;
            // 
            // Ans3txt
            // 
            Ans3txt.AcceptsReturn = false;
            Ans3txt.AcceptsTab = false;
            Ans3txt.AnimationSpeed = 200;
            Ans3txt.AutoCompleteMode = AutoCompleteMode.None;
            Ans3txt.AutoCompleteSource = AutoCompleteSource.None;
            Ans3txt.AutoSizeHeight = true;
            Ans3txt.BackColor = Color.Transparent;
            Ans3txt.BackgroundImage = (Image)resources.GetObject("Ans3txt.BackgroundImage");
            Ans3txt.BorderColorActive = Color.DodgerBlue;
            Ans3txt.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            Ans3txt.BorderColorHover = Color.FromArgb(105, 181, 255);
            Ans3txt.BorderColorIdle = Color.Silver;
            Ans3txt.BorderRadius = 1;
            Ans3txt.BorderThickness = 1;
            Ans3txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            Ans3txt.CharacterCasing = CharacterCasing.Normal;
            Ans3txt.DefaultFont = new Font("Segoe UI", 9.25F);
            Ans3txt.DefaultText = "";
            Ans3txt.FillColor = Color.White;
            Ans3txt.HideSelection = true;
            Ans3txt.IconLeft = null;
            Ans3txt.IconLeftCursor = Cursors.IBeam;
            Ans3txt.IconPadding = 10;
            Ans3txt.IconRight = null;
            Ans3txt.IconRightCursor = Cursors.IBeam;
            Ans3txt.Location = new Point(343, 321);
            Ans3txt.MaxLength = 32767;
            Ans3txt.MinimumSize = new Size(1, 1);
            Ans3txt.Modified = false;
            Ans3txt.Multiline = false;
            Ans3txt.Name = "Ans3txt";
            stateProperties5.BorderColor = Color.DodgerBlue;
            stateProperties5.FillColor = Color.Empty;
            stateProperties5.ForeColor = Color.Empty;
            stateProperties5.PlaceholderForeColor = Color.Empty;
            Ans3txt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties6.PlaceholderForeColor = Color.DarkGray;
            Ans3txt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties7.FillColor = Color.Empty;
            stateProperties7.ForeColor = Color.Empty;
            stateProperties7.PlaceholderForeColor = Color.Empty;
            Ans3txt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = Color.Silver;
            stateProperties8.FillColor = Color.White;
            stateProperties8.ForeColor = Color.Empty;
            stateProperties8.PlaceholderForeColor = Color.Empty;
            Ans3txt.OnIdleState = stateProperties8;
            Ans3txt.Padding = new Padding(3);
            Ans3txt.PasswordChar = '\0';
            Ans3txt.PlaceholderForeColor = Color.Silver;
            Ans3txt.PlaceholderText = "Enter text";
            Ans3txt.ReadOnly = false;
            Ans3txt.ScrollBars = ScrollBars.None;
            Ans3txt.SelectedText = "";
            Ans3txt.SelectionLength = 0;
            Ans3txt.SelectionStart = 0;
            Ans3txt.ShortcutsEnabled = true;
            Ans3txt.Size = new Size(388, 32);
            Ans3txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            Ans3txt.TabIndex = 5;
            Ans3txt.TextAlign = HorizontalAlignment.Left;
            Ans3txt.TextMarginBottom = 0;
            Ans3txt.TextMarginLeft = 3;
            Ans3txt.TextMarginTop = 1;
            Ans3txt.TextPlaceholder = "Enter text";
            Ans3txt.UseSystemPasswordChar = false;
            Ans3txt.WordWrap = true;
            // 
            // Ans2txt
            // 
            Ans2txt.AcceptsReturn = false;
            Ans2txt.AcceptsTab = false;
            Ans2txt.AnimationSpeed = 200;
            Ans2txt.AutoCompleteMode = AutoCompleteMode.None;
            Ans2txt.AutoCompleteSource = AutoCompleteSource.None;
            Ans2txt.AutoSizeHeight = true;
            Ans2txt.BackColor = Color.Transparent;
            Ans2txt.BackgroundImage = (Image)resources.GetObject("Ans2txt.BackgroundImage");
            Ans2txt.BorderColorActive = Color.DodgerBlue;
            Ans2txt.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            Ans2txt.BorderColorHover = Color.FromArgb(105, 181, 255);
            Ans2txt.BorderColorIdle = Color.Silver;
            Ans2txt.BorderRadius = 1;
            Ans2txt.BorderThickness = 1;
            Ans2txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            Ans2txt.CharacterCasing = CharacterCasing.Normal;
            Ans2txt.DefaultFont = new Font("Segoe UI", 9.25F);
            Ans2txt.DefaultText = "";
            Ans2txt.FillColor = Color.White;
            Ans2txt.HideSelection = true;
            Ans2txt.IconLeft = null;
            Ans2txt.IconLeftCursor = Cursors.IBeam;
            Ans2txt.IconPadding = 10;
            Ans2txt.IconRight = null;
            Ans2txt.IconRightCursor = Cursors.IBeam;
            Ans2txt.Location = new Point(343, 214);
            Ans2txt.MaxLength = 32767;
            Ans2txt.MinimumSize = new Size(1, 1);
            Ans2txt.Modified = false;
            Ans2txt.Multiline = false;
            Ans2txt.Name = "Ans2txt";
            stateProperties9.BorderColor = Color.DodgerBlue;
            stateProperties9.FillColor = Color.Empty;
            stateProperties9.ForeColor = Color.Empty;
            stateProperties9.PlaceholderForeColor = Color.Empty;
            Ans2txt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties10.PlaceholderForeColor = Color.DarkGray;
            Ans2txt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties11.FillColor = Color.Empty;
            stateProperties11.ForeColor = Color.Empty;
            stateProperties11.PlaceholderForeColor = Color.Empty;
            Ans2txt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = Color.Silver;
            stateProperties12.FillColor = Color.White;
            stateProperties12.ForeColor = Color.Empty;
            stateProperties12.PlaceholderForeColor = Color.Empty;
            Ans2txt.OnIdleState = stateProperties12;
            Ans2txt.Padding = new Padding(3);
            Ans2txt.PasswordChar = '\0';
            Ans2txt.PlaceholderForeColor = Color.Silver;
            Ans2txt.PlaceholderText = "Enter text";
            Ans2txt.ReadOnly = false;
            Ans2txt.ScrollBars = ScrollBars.None;
            Ans2txt.SelectedText = "";
            Ans2txt.SelectionLength = 0;
            Ans2txt.SelectionStart = 0;
            Ans2txt.ShortcutsEnabled = true;
            Ans2txt.Size = new Size(388, 32);
            Ans2txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            Ans2txt.TabIndex = 4;
            Ans2txt.TextAlign = HorizontalAlignment.Left;
            Ans2txt.TextMarginBottom = 0;
            Ans2txt.TextMarginLeft = 3;
            Ans2txt.TextMarginTop = 1;
            Ans2txt.TextPlaceholder = "Enter text";
            Ans2txt.UseSystemPasswordChar = false;
            Ans2txt.WordWrap = true;
            // 
            // Ans1txt
            // 
            Ans1txt.AcceptsReturn = false;
            Ans1txt.AcceptsTab = false;
            Ans1txt.AnimationSpeed = 200;
            Ans1txt.AutoCompleteMode = AutoCompleteMode.None;
            Ans1txt.AutoCompleteSource = AutoCompleteSource.None;
            Ans1txt.AutoSizeHeight = true;
            Ans1txt.BackColor = Color.Transparent;
            Ans1txt.BackgroundImage = (Image)resources.GetObject("Ans1txt.BackgroundImage");
            Ans1txt.BorderColorActive = Color.DodgerBlue;
            Ans1txt.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            Ans1txt.BorderColorHover = Color.FromArgb(105, 181, 255);
            Ans1txt.BorderColorIdle = Color.Silver;
            Ans1txt.BorderRadius = 1;
            Ans1txt.BorderThickness = 1;
            Ans1txt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            Ans1txt.CharacterCasing = CharacterCasing.Normal;
            Ans1txt.DefaultFont = new Font("Segoe UI", 9.25F);
            Ans1txt.DefaultText = "";
            Ans1txt.FillColor = Color.White;
            Ans1txt.HideSelection = true;
            Ans1txt.IconLeft = null;
            Ans1txt.IconLeftCursor = Cursors.IBeam;
            Ans1txt.IconPadding = 10;
            Ans1txt.IconRight = null;
            Ans1txt.IconRightCursor = Cursors.IBeam;
            Ans1txt.Location = new Point(343, 115);
            Ans1txt.MaxLength = 32767;
            Ans1txt.MinimumSize = new Size(1, 1);
            Ans1txt.Modified = false;
            Ans1txt.Multiline = false;
            Ans1txt.Name = "Ans1txt";
            stateProperties13.BorderColor = Color.DodgerBlue;
            stateProperties13.FillColor = Color.Empty;
            stateProperties13.ForeColor = Color.Empty;
            stateProperties13.PlaceholderForeColor = Color.Empty;
            Ans1txt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties14.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties14.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties14.PlaceholderForeColor = Color.DarkGray;
            Ans1txt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties15.FillColor = Color.Empty;
            stateProperties15.ForeColor = Color.Empty;
            stateProperties15.PlaceholderForeColor = Color.Empty;
            Ans1txt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = Color.Silver;
            stateProperties16.FillColor = Color.White;
            stateProperties16.ForeColor = Color.Empty;
            stateProperties16.PlaceholderForeColor = Color.Empty;
            Ans1txt.OnIdleState = stateProperties16;
            Ans1txt.Padding = new Padding(3);
            Ans1txt.PasswordChar = '\0';
            Ans1txt.PlaceholderForeColor = Color.Silver;
            Ans1txt.PlaceholderText = "Enter text";
            Ans1txt.ReadOnly = false;
            Ans1txt.ScrollBars = ScrollBars.None;
            Ans1txt.SelectedText = "";
            Ans1txt.SelectionLength = 0;
            Ans1txt.SelectionStart = 0;
            Ans1txt.ShortcutsEnabled = true;
            Ans1txt.Size = new Size(388, 32);
            Ans1txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            Ans1txt.TabIndex = 3;
            Ans1txt.TextAlign = HorizontalAlignment.Left;
            Ans1txt.TextMarginBottom = 0;
            Ans1txt.TextMarginLeft = 3;
            Ans1txt.TextMarginTop = 1;
            Ans1txt.TextPlaceholder = "Enter text";
            Ans1txt.UseSystemPasswordChar = false;
            Ans1txt.WordWrap = true;
            // 
            // ResetPassPanel
            // 
            ResetPassPanel.Controls.Add(label5);
            ResetPassPanel.Controls.Add(label4);
            ResetPassPanel.Controls.Add(bunifuTextBox2);
            ResetPassPanel.Controls.Add(bunifuTextBox1);
            ResetPassPanel.Controls.Add(panel4);
            ResetPassPanel.Controls.Add(panel2);
            ResetPassPanel.Location = new Point(0, 300);
            ResetPassPanel.Name = "ResetPassPanel";
            ResetPassPanel.Size = new Size(420, 260);
            ResetPassPanel.TabIndex = 7;
            // 
            // label5
            // 
            label5.BackColor = Color.Transparent;
            label5.Font = new Font("Courier New", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label5.Location = new Point(21, 134);
            label5.Name = "label5";
            label5.Size = new Size(190, 33);
            label5.TabIndex = 7;
            label5.Text = "Re-enter Password:";
            label5.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // label4
            // 
            label4.BackColor = Color.Transparent;
            label4.Font = new Font("Courier New", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label4.Location = new Point(21, 51);
            label4.Name = "label4";
            label4.Size = new Size(143, 33);
            label4.TabIndex = 6;
            label4.Text = "New Password:";
            label4.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // bunifuTextBox2
            // 
            bunifuTextBox2.AcceptsReturn = false;
            bunifuTextBox2.AcceptsTab = false;
            bunifuTextBox2.AnimationSpeed = 200;
            bunifuTextBox2.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox2.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox2.AutoSizeHeight = true;
            bunifuTextBox2.BackColor = Color.Transparent;
            bunifuTextBox2.BackgroundImage = (Image)resources.GetObject("bunifuTextBox2.BackgroundImage");
            bunifuTextBox2.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox2.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox2.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox2.BorderColorIdle = Color.Silver;
            bunifuTextBox2.BorderRadius = 1;
            bunifuTextBox2.BorderThickness = 1;
            bunifuTextBox2.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox2.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox2.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox2.DefaultText = "";
            bunifuTextBox2.FillColor = Color.White;
            bunifuTextBox2.HideSelection = true;
            bunifuTextBox2.IconLeft = null;
            bunifuTextBox2.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox2.IconPadding = 10;
            bunifuTextBox2.IconRight = null;
            bunifuTextBox2.IconRightCursor = Cursors.IBeam;
            bunifuTextBox2.Location = new Point(21, 175);
            bunifuTextBox2.MaxLength = 32767;
            bunifuTextBox2.MinimumSize = new Size(1, 1);
            bunifuTextBox2.Modified = false;
            bunifuTextBox2.Multiline = false;
            bunifuTextBox2.Name = "bunifuTextBox2";
            stateProperties17.BorderColor = Color.DodgerBlue;
            stateProperties17.FillColor = Color.Empty;
            stateProperties17.ForeColor = Color.Empty;
            stateProperties17.PlaceholderForeColor = Color.Empty;
            bunifuTextBox2.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties18.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties18.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties18.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox2.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties19.FillColor = Color.Empty;
            stateProperties19.ForeColor = Color.Empty;
            stateProperties19.PlaceholderForeColor = Color.Empty;
            bunifuTextBox2.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = Color.Silver;
            stateProperties20.FillColor = Color.White;
            stateProperties20.ForeColor = Color.Empty;
            stateProperties20.PlaceholderForeColor = Color.Empty;
            bunifuTextBox2.OnIdleState = stateProperties20;
            bunifuTextBox2.Padding = new Padding(3);
            bunifuTextBox2.PasswordChar = '\0';
            bunifuTextBox2.PlaceholderForeColor = Color.Silver;
            bunifuTextBox2.PlaceholderText = "Enter text";
            bunifuTextBox2.ReadOnly = false;
            bunifuTextBox2.ScrollBars = ScrollBars.None;
            bunifuTextBox2.SelectedText = "";
            bunifuTextBox2.SelectionLength = 0;
            bunifuTextBox2.SelectionStart = 0;
            bunifuTextBox2.ShortcutsEnabled = true;
            bunifuTextBox2.Size = new Size(374, 39);
            bunifuTextBox2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox2.TabIndex = 5;
            bunifuTextBox2.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox2.TextMarginBottom = 0;
            bunifuTextBox2.TextMarginLeft = 3;
            bunifuTextBox2.TextMarginTop = 1;
            bunifuTextBox2.TextPlaceholder = "Enter text";
            bunifuTextBox2.UseSystemPasswordChar = false;
            bunifuTextBox2.WordWrap = true;
            // 
            // bunifuTextBox1
            // 
            bunifuTextBox1.AcceptsReturn = false;
            bunifuTextBox1.AcceptsTab = false;
            bunifuTextBox1.AnimationSpeed = 200;
            bunifuTextBox1.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox1.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox1.AutoSizeHeight = true;
            bunifuTextBox1.BackColor = Color.Transparent;
            bunifuTextBox1.BackgroundImage = (Image)resources.GetObject("bunifuTextBox1.BackgroundImage");
            bunifuTextBox1.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox1.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox1.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox1.BorderColorIdle = Color.Silver;
            bunifuTextBox1.BorderRadius = 1;
            bunifuTextBox1.BorderThickness = 1;
            bunifuTextBox1.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox1.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox1.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox1.DefaultText = "";
            bunifuTextBox1.FillColor = Color.White;
            bunifuTextBox1.HideSelection = true;
            bunifuTextBox1.IconLeft = null;
            bunifuTextBox1.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox1.IconPadding = 10;
            bunifuTextBox1.IconRight = null;
            bunifuTextBox1.IconRightCursor = Cursors.IBeam;
            bunifuTextBox1.Location = new Point(21, 89);
            bunifuTextBox1.MaxLength = 32767;
            bunifuTextBox1.MinimumSize = new Size(1, 1);
            bunifuTextBox1.Modified = false;
            bunifuTextBox1.Multiline = false;
            bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties21.BorderColor = Color.DodgerBlue;
            stateProperties21.FillColor = Color.Empty;
            stateProperties21.ForeColor = Color.Empty;
            stateProperties21.PlaceholderForeColor = Color.Empty;
            bunifuTextBox1.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties22.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties22.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties22.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox1.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties23.FillColor = Color.Empty;
            stateProperties23.ForeColor = Color.Empty;
            stateProperties23.PlaceholderForeColor = Color.Empty;
            bunifuTextBox1.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = Color.Silver;
            stateProperties24.FillColor = Color.White;
            stateProperties24.ForeColor = Color.Empty;
            stateProperties24.PlaceholderForeColor = Color.Empty;
            bunifuTextBox1.OnIdleState = stateProperties24;
            bunifuTextBox1.Padding = new Padding(3);
            bunifuTextBox1.PasswordChar = '\0';
            bunifuTextBox1.PlaceholderForeColor = Color.Silver;
            bunifuTextBox1.PlaceholderText = "Enter text";
            bunifuTextBox1.ReadOnly = false;
            bunifuTextBox1.ScrollBars = ScrollBars.None;
            bunifuTextBox1.SelectedText = "";
            bunifuTextBox1.SelectionLength = 0;
            bunifuTextBox1.SelectionStart = 0;
            bunifuTextBox1.ShortcutsEnabled = true;
            bunifuTextBox1.Size = new Size(374, 39);
            bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox1.TabIndex = 4;
            bunifuTextBox1.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox1.TextMarginBottom = 0;
            bunifuTextBox1.TextMarginLeft = 3;
            bunifuTextBox1.TextMarginTop = 1;
            bunifuTextBox1.TextPlaceholder = "Enter text";
            bunifuTextBox1.UseSystemPasswordChar = false;
            bunifuTextBox1.WordWrap = true;
            // 
            // panel4
            // 
            panel4.Controls.Add(CancelBtn2);
            panel4.Controls.Add(ResetPassBtn);
            panel4.Dock = DockStyle.Bottom;
            panel4.Location = new Point(0, 225);
            panel4.Name = "panel4";
            panel4.Padding = new Padding(10, 2, 10, 2);
            panel4.Size = new Size(420, 35);
            panel4.TabIndex = 3;
            // 
            // CancelBtn2
            // 
            CancelBtn2.AllowAnimations = true;
            CancelBtn2.AllowMouseEffects = true;
            CancelBtn2.AllowToggling = false;
            CancelBtn2.AnimationSpeed = 200;
            CancelBtn2.AutoGenerateColors = false;
            CancelBtn2.AutoRoundBorders = false;
            CancelBtn2.AutoSizeLeftIcon = true;
            CancelBtn2.AutoSizeRightIcon = true;
            CancelBtn2.BackColor = Color.Transparent;
            CancelBtn2.BackColor1 = Color.FromArgb(51, 122, 183);
            CancelBtn2.BackgroundImage = (Image)resources.GetObject("CancelBtn2.BackgroundImage");
            CancelBtn2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            CancelBtn2.ButtonText = "Cancel";
            CancelBtn2.ButtonTextMarginLeft = 0;
            CancelBtn2.ColorContrastOnClick = 45;
            CancelBtn2.ColorContrastOnHover = 45;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            CancelBtn2.CustomizableEdges = borderEdges5;
            CancelBtn2.DialogResult = DialogResult.None;
            CancelBtn2.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            CancelBtn2.DisabledFillColor = Color.Empty;
            CancelBtn2.DisabledForecolor = Color.Empty;
            CancelBtn2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            CancelBtn2.Font = new Font("Courier New", 9F, FontStyle.Bold);
            CancelBtn2.ForeColor = Color.Black;
            CancelBtn2.IconLeft = null;
            CancelBtn2.IconLeftAlign = ContentAlignment.MiddleLeft;
            CancelBtn2.IconLeftCursor = Cursors.Default;
            CancelBtn2.IconLeftPadding = new Padding(11, 3, 3, 3);
            CancelBtn2.IconMarginLeft = 11;
            CancelBtn2.IconPadding = 10;
            CancelBtn2.IconRight = null;
            CancelBtn2.IconRightAlign = ContentAlignment.MiddleRight;
            CancelBtn2.IconRightCursor = Cursors.Default;
            CancelBtn2.IconRightPadding = new Padding(3, 3, 7, 3);
            CancelBtn2.IconSize = 25;
            CancelBtn2.IdleBorderColor = Color.Empty;
            CancelBtn2.IdleBorderRadius = 0;
            CancelBtn2.IdleBorderThickness = 0;
            CancelBtn2.IdleFillColor = Color.Empty;
            CancelBtn2.IdleIconLeftImage = null;
            CancelBtn2.IdleIconRightImage = null;
            CancelBtn2.IndicateFocus = false;
            CancelBtn2.Location = new Point(237, 2);
            CancelBtn2.Name = "CancelBtn2";
            CancelBtn2.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            CancelBtn2.OnDisabledState.BorderRadius = 1;
            CancelBtn2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            CancelBtn2.OnDisabledState.BorderThickness = 1;
            CancelBtn2.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            CancelBtn2.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            CancelBtn2.OnDisabledState.IconLeftImage = null;
            CancelBtn2.OnDisabledState.IconRightImage = null;
            CancelBtn2.onHoverState.BorderColor = Color.Black;
            CancelBtn2.onHoverState.BorderRadius = 1;
            CancelBtn2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            CancelBtn2.onHoverState.BorderThickness = 1;
            CancelBtn2.onHoverState.FillColor = Color.FromArgb(205, 205, 207);
            CancelBtn2.onHoverState.ForeColor = Color.Black;
            CancelBtn2.onHoverState.IconLeftImage = null;
            CancelBtn2.onHoverState.IconRightImage = null;
            CancelBtn2.OnIdleState.BorderColor = Color.FromArgb(220, 220, 221);
            CancelBtn2.OnIdleState.BorderRadius = 1;
            CancelBtn2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            CancelBtn2.OnIdleState.BorderThickness = 1;
            CancelBtn2.OnIdleState.FillColor = Color.FromArgb(220, 220, 221);
            CancelBtn2.OnIdleState.ForeColor = Color.Black;
            CancelBtn2.OnIdleState.IconLeftImage = null;
            CancelBtn2.OnIdleState.IconRightImage = null;
            CancelBtn2.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            CancelBtn2.OnPressedState.BorderRadius = 1;
            CancelBtn2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            CancelBtn2.OnPressedState.BorderThickness = 1;
            CancelBtn2.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            CancelBtn2.OnPressedState.ForeColor = Color.White;
            CancelBtn2.OnPressedState.IconLeftImage = null;
            CancelBtn2.OnPressedState.IconRightImage = null;
            CancelBtn2.Size = new Size(65, 30);
            CancelBtn2.TabIndex = 3;
            CancelBtn2.TextAlign = ContentAlignment.MiddleCenter;
            CancelBtn2.TextAlignment = HorizontalAlignment.Center;
            CancelBtn2.TextMarginLeft = 0;
            CancelBtn2.TextPadding = new Padding(0);
            CancelBtn2.UseDefaultRadiusAndThickness = true;
            // 
            // ResetPassBtn
            // 
            ResetPassBtn.AllowAnimations = true;
            ResetPassBtn.AllowMouseEffects = true;
            ResetPassBtn.AllowToggling = false;
            ResetPassBtn.AnimationSpeed = 200;
            ResetPassBtn.AutoGenerateColors = false;
            ResetPassBtn.AutoRoundBorders = false;
            ResetPassBtn.AutoSizeLeftIcon = true;
            ResetPassBtn.AutoSizeRightIcon = true;
            ResetPassBtn.BackColor = Color.Transparent;
            ResetPassBtn.BackColor1 = Color.FromArgb(51, 122, 183);
            ResetPassBtn.BackgroundImage = (Image)resources.GetObject("ResetPassBtn.BackgroundImage");
            ResetPassBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ResetPassBtn.ButtonText = "Reset Password";
            ResetPassBtn.ButtonTextMarginLeft = 0;
            ResetPassBtn.ColorContrastOnClick = 45;
            ResetPassBtn.ColorContrastOnHover = 45;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            ResetPassBtn.CustomizableEdges = borderEdges6;
            ResetPassBtn.DialogResult = DialogResult.None;
            ResetPassBtn.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            ResetPassBtn.DisabledFillColor = Color.Empty;
            ResetPassBtn.DisabledForecolor = Color.Empty;
            ResetPassBtn.Dock = DockStyle.Right;
            ResetPassBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            ResetPassBtn.Font = new Font("Courier New", 9F, FontStyle.Bold);
            ResetPassBtn.ForeColor = Color.White;
            ResetPassBtn.IconLeft = null;
            ResetPassBtn.IconLeftAlign = ContentAlignment.MiddleLeft;
            ResetPassBtn.IconLeftCursor = Cursors.Default;
            ResetPassBtn.IconLeftPadding = new Padding(11, 3, 3, 3);
            ResetPassBtn.IconMarginLeft = 11;
            ResetPassBtn.IconPadding = 10;
            ResetPassBtn.IconRight = null;
            ResetPassBtn.IconRightAlign = ContentAlignment.MiddleRight;
            ResetPassBtn.IconRightCursor = Cursors.Default;
            ResetPassBtn.IconRightPadding = new Padding(3, 3, 7, 3);
            ResetPassBtn.IconSize = 25;
            ResetPassBtn.IdleBorderColor = Color.Empty;
            ResetPassBtn.IdleBorderRadius = 0;
            ResetPassBtn.IdleBorderThickness = 0;
            ResetPassBtn.IdleFillColor = Color.Empty;
            ResetPassBtn.IdleIconLeftImage = null;
            ResetPassBtn.IdleIconRightImage = null;
            ResetPassBtn.IndicateFocus = false;
            ResetPassBtn.Location = new Point(308, 2);
            ResetPassBtn.Name = "ResetPassBtn";
            ResetPassBtn.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            ResetPassBtn.OnDisabledState.BorderRadius = 1;
            ResetPassBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ResetPassBtn.OnDisabledState.BorderThickness = 1;
            ResetPassBtn.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            ResetPassBtn.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            ResetPassBtn.OnDisabledState.IconLeftImage = null;
            ResetPassBtn.OnDisabledState.IconRightImage = null;
            ResetPassBtn.onHoverState.BorderColor = Color.FromArgb(50, 110, 5);
            ResetPassBtn.onHoverState.BorderRadius = 1;
            ResetPassBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ResetPassBtn.onHoverState.BorderThickness = 1;
            ResetPassBtn.onHoverState.FillColor = Color.FromArgb(50, 110, 5);
            ResetPassBtn.onHoverState.ForeColor = Color.White;
            ResetPassBtn.onHoverState.IconLeftImage = null;
            ResetPassBtn.onHoverState.IconRightImage = null;
            ResetPassBtn.OnIdleState.BorderColor = Color.FromArgb(78, 160, 21);
            ResetPassBtn.OnIdleState.BorderRadius = 1;
            ResetPassBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ResetPassBtn.OnIdleState.BorderThickness = 1;
            ResetPassBtn.OnIdleState.FillColor = Color.FromArgb(78, 160, 21);
            ResetPassBtn.OnIdleState.ForeColor = Color.White;
            ResetPassBtn.OnIdleState.IconLeftImage = null;
            ResetPassBtn.OnIdleState.IconRightImage = null;
            ResetPassBtn.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            ResetPassBtn.OnPressedState.BorderRadius = 1;
            ResetPassBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ResetPassBtn.OnPressedState.BorderThickness = 1;
            ResetPassBtn.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            ResetPassBtn.OnPressedState.ForeColor = Color.White;
            ResetPassBtn.OnPressedState.IconLeftImage = null;
            ResetPassBtn.OnPressedState.IconRightImage = null;
            ResetPassBtn.Size = new Size(102, 31);
            ResetPassBtn.TabIndex = 0;
            ResetPassBtn.TextAlign = ContentAlignment.MiddleCenter;
            ResetPassBtn.TextAlignment = HorizontalAlignment.Center;
            ResetPassBtn.TextMarginLeft = 0;
            ResetPassBtn.TextPadding = new Padding(0);
            ResetPassBtn.UseDefaultRadiusAndThickness = true;
            // 
            // panel2
            // 
            panel2.BackColor = Color.White;
            panel2.Controls.Add(panel3);
            panel2.Controls.Add(label3);
            panel2.Dock = DockStyle.Top;
            panel2.Location = new Point(0, 0);
            panel2.Name = "panel2";
            panel2.Size = new Size(420, 40);
            panel2.TabIndex = 2;
            // 
            // panel3
            // 
            panel3.BackColor = Color.Maroon;
            panel3.Dock = DockStyle.Bottom;
            panel3.Location = new Point(0, 35);
            panel3.Name = "panel3";
            panel3.Size = new Size(420, 5);
            panel3.TabIndex = 3;
            // 
            // label3
            // 
            label3.BackColor = Color.Transparent;
            label3.Font = new Font("Courier New", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label3.Location = new Point(10, 0);
            label3.Name = "label3";
            label3.Size = new Size(154, 33);
            label3.TabIndex = 0;
            label3.Text = "Reset Password";
            label3.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // panel6
            // 
            panel6.BackColor = Color.White;
            panel6.Controls.Add(panel7);
            panel6.Controls.Add(label7);
            panel6.Dock = DockStyle.Top;
            panel6.Location = new Point(0, 0);
            panel6.Name = "panel6";
            panel6.Size = new Size(800, 40);
            panel6.TabIndex = 10;
            // 
            // panel7
            // 
            panel7.BackColor = Color.Maroon;
            panel7.Dock = DockStyle.Bottom;
            panel7.Location = new Point(0, 35);
            panel7.Name = "panel7";
            panel7.Size = new Size(800, 5);
            panel7.TabIndex = 3;
            // 
            // label7
            // 
            label7.BackColor = Color.Transparent;
            label7.Font = new Font("Courier New", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label7.Location = new Point(10, 0);
            label7.Name = "label7";
            label7.Size = new Size(181, 33);
            label7.TabIndex = 0;
            label7.Text = "Forgot Password";
            label7.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // ForgotPasswordModal
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            ClientSize = new Size(800, 450);
            Controls.Add(ResetPassPanel);
            Controls.Add(QuestionPanel);
            Controls.Add(panel6);
            Controls.Add(ForgotEmailTxt);
            Controls.Add(label2);
            Controls.Add(btnNext);
            Controls.Add(label1);
            Controls.Add(btncancel);
            Controls.Add(pictureBox1);
            FormBorderStyle = FormBorderStyle.None;
            Name = "ForgotPasswordModal";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "ForgotPasswordModal";
            ((System.ComponentModel.ISupportInitialize)pictureBox1).EndInit();
            QuestionPanel.ResumeLayout(false);
            panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)pictureBox2).EndInit();
            ResetPassPanel.ResumeLayout(false);
            panel4.ResumeLayout(false);
            panel2.ResumeLayout(false);
            panel6.ResumeLayout(false);
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btncancel;
        private Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNext;
        private Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox ForgotEmailTxt;
        private Panel QuestionPanel;
        private PictureBox pictureBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BackBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ValidateBtn;
        private Bunifu.UI.WinForms.BunifuTextBox Ans3txt;
        private Bunifu.UI.WinForms.BunifuTextBox Ans2txt;
        private Bunifu.UI.WinForms.BunifuTextBox Ans1txt;
        private Panel ResetPassPanel;
        private Panel panel2;
        private Panel panel3;
        private Label label3;
        private Label label5;
        private Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox2;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        private Panel panel4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton CancelBtn2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ResetPassBtn;
        private Panel panel1;
        private Panel panel5;
        private Label label6;
        private Panel panel6;
        private Panel panel7;
        private Label label7;
        private Label label10;
        private Label label9;
        private Label label8;
    }
}