namespace DazaBestApplication.Modals
{
    partial class ForgotPasswordModal
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ForgotPasswordModal));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            pictureBox1 = new PictureBox();
            bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            label1 = new Label();
            bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            label2 = new Label();
            bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            QuestionPanel = new Panel();
            pictureBox2 = new PictureBox();
            bunifuButton4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            bunifuTextBox4 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuTextBox3 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuTextBox2 = new Bunifu.UI.WinForms.BunifuTextBox();
            bunifuDropdown3 = new Bunifu.UI.WinForms.BunifuDropdown();
            bunifuDropdown2 = new Bunifu.UI.WinForms.BunifuDropdown();
            bunifuDropdown1 = new Bunifu.UI.WinForms.BunifuDropdown();
            ((System.ComponentModel.ISupportInitialize)pictureBox1).BeginInit();
            QuestionPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox2).BeginInit();
            SuspendLayout();
            // 
            // pictureBox1
            // 
            pictureBox1.Image = Properties.Resources._try;
            pictureBox1.Location = new Point(37, 58);
            pictureBox1.Name = "pictureBox1";
            pictureBox1.Size = new Size(300, 300);
            pictureBox1.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox1.TabIndex = 0;
            pictureBox1.TabStop = false;
            // 
            // bunifuButton1
            // 
            bunifuButton1.AllowAnimations = true;
            bunifuButton1.AllowMouseEffects = true;
            bunifuButton1.AllowToggling = false;
            bunifuButton1.AnimationSpeed = 200;
            bunifuButton1.AutoGenerateColors = false;
            bunifuButton1.AutoRoundBorders = false;
            bunifuButton1.AutoSizeLeftIcon = true;
            bunifuButton1.AutoSizeRightIcon = true;
            bunifuButton1.BackColor = Color.Transparent;
            bunifuButton1.BackColor1 = Color.FromArgb(51, 122, 183);
            bunifuButton1.BackgroundImage = (Image)resources.GetObject("bunifuButton1.BackgroundImage");
            bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton1.ButtonText = "Cancel";
            bunifuButton1.ButtonTextMarginLeft = 0;
            bunifuButton1.ColorContrastOnClick = 45;
            bunifuButton1.ColorContrastOnHover = 45;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            bunifuButton1.CustomizableEdges = borderEdges1;
            bunifuButton1.DialogResult = DialogResult.None;
            bunifuButton1.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton1.DisabledFillColor = Color.Empty;
            bunifuButton1.DisabledForecolor = Color.Empty;
            bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            bunifuButton1.Font = new Font("Segoe UI", 9F);
            bunifuButton1.ForeColor = Color.White;
            bunifuButton1.IconLeft = null;
            bunifuButton1.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton1.IconLeftCursor = Cursors.Default;
            bunifuButton1.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton1.IconMarginLeft = 11;
            bunifuButton1.IconPadding = 10;
            bunifuButton1.IconRight = null;
            bunifuButton1.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton1.IconRightCursor = Cursors.Default;
            bunifuButton1.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton1.IconSize = 25;
            bunifuButton1.IdleBorderColor = Color.Empty;
            bunifuButton1.IdleBorderRadius = 0;
            bunifuButton1.IdleBorderThickness = 0;
            bunifuButton1.IdleFillColor = Color.Empty;
            bunifuButton1.IdleIconLeftImage = null;
            bunifuButton1.IdleIconRightImage = null;
            bunifuButton1.IndicateFocus = false;
            bunifuButton1.Location = new Point(417, 319);
            bunifuButton1.Name = "bunifuButton1";
            bunifuButton1.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton1.OnDisabledState.BorderRadius = 1;
            bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton1.OnDisabledState.BorderThickness = 1;
            bunifuButton1.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton1.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton1.OnDisabledState.IconLeftImage = null;
            bunifuButton1.OnDisabledState.IconRightImage = null;
            bunifuButton1.onHoverState.BorderColor = Color.FromArgb(192, 74, 62);
            bunifuButton1.onHoverState.BorderRadius = 1;
            bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton1.onHoverState.BorderThickness = 1;
            bunifuButton1.onHoverState.FillColor = Color.FromArgb(192, 74, 62);
            bunifuButton1.onHoverState.ForeColor = Color.White;
            bunifuButton1.onHoverState.IconLeftImage = null;
            bunifuButton1.onHoverState.IconRightImage = null;
            bunifuButton1.OnIdleState.BorderColor = Color.FromArgb(192, 57, 43);
            bunifuButton1.OnIdleState.BorderRadius = 1;
            bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton1.OnIdleState.BorderThickness = 1;
            bunifuButton1.OnIdleState.FillColor = Color.FromArgb(192, 57, 43);
            bunifuButton1.OnIdleState.ForeColor = Color.White;
            bunifuButton1.OnIdleState.IconLeftImage = null;
            bunifuButton1.OnIdleState.IconRightImage = null;
            bunifuButton1.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton1.OnPressedState.BorderRadius = 1;
            bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton1.OnPressedState.BorderThickness = 1;
            bunifuButton1.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton1.OnPressedState.ForeColor = Color.White;
            bunifuButton1.OnPressedState.IconLeftImage = null;
            bunifuButton1.OnPressedState.IconRightImage = null;
            bunifuButton1.Size = new Size(150, 39);
            bunifuButton1.TabIndex = 1;
            bunifuButton1.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton1.TextAlignment = HorizontalAlignment.Center;
            bunifuButton1.TextMarginLeft = 0;
            bunifuButton1.TextPadding = new Padding(0);
            bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Courier New", 27.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label1.ForeColor = Color.FromArgb(192, 57, 43);
            label1.Location = new Point(419, 59);
            label1.Name = "label1";
            label1.Size = new Size(216, 82);
            label1.TabIndex = 2;
            label1.Text = "Forgot\r\nPassword?";
            // 
            // bunifuButton2
            // 
            bunifuButton2.AllowAnimations = true;
            bunifuButton2.AllowMouseEffects = true;
            bunifuButton2.AllowToggling = false;
            bunifuButton2.AnimationSpeed = 200;
            bunifuButton2.AutoGenerateColors = false;
            bunifuButton2.AutoRoundBorders = false;
            bunifuButton2.AutoSizeLeftIcon = true;
            bunifuButton2.AutoSizeRightIcon = true;
            bunifuButton2.BackColor = Color.Transparent;
            bunifuButton2.BackColor1 = Color.FromArgb(51, 122, 183);
            bunifuButton2.BackgroundImage = (Image)resources.GetObject("bunifuButton2.BackgroundImage");
            bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton2.ButtonText = "Next";
            bunifuButton2.ButtonTextMarginLeft = 0;
            bunifuButton2.ColorContrastOnClick = 45;
            bunifuButton2.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            bunifuButton2.CustomizableEdges = borderEdges2;
            bunifuButton2.DialogResult = DialogResult.None;
            bunifuButton2.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton2.DisabledFillColor = Color.Empty;
            bunifuButton2.DisabledForecolor = Color.Empty;
            bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            bunifuButton2.Font = new Font("Segoe UI", 9F);
            bunifuButton2.ForeColor = Color.White;
            bunifuButton2.IconLeft = null;
            bunifuButton2.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton2.IconLeftCursor = Cursors.Default;
            bunifuButton2.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton2.IconMarginLeft = 11;
            bunifuButton2.IconPadding = 10;
            bunifuButton2.IconRight = null;
            bunifuButton2.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton2.IconRightCursor = Cursors.Default;
            bunifuButton2.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton2.IconSize = 25;
            bunifuButton2.IdleBorderColor = Color.Empty;
            bunifuButton2.IdleBorderRadius = 0;
            bunifuButton2.IdleBorderThickness = 0;
            bunifuButton2.IdleFillColor = Color.Empty;
            bunifuButton2.IdleIconLeftImage = null;
            bunifuButton2.IdleIconRightImage = null;
            bunifuButton2.IndicateFocus = false;
            bunifuButton2.Location = new Point(596, 319);
            bunifuButton2.Name = "bunifuButton2";
            bunifuButton2.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton2.OnDisabledState.BorderRadius = 1;
            bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton2.OnDisabledState.BorderThickness = 1;
            bunifuButton2.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton2.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton2.OnDisabledState.IconLeftImage = null;
            bunifuButton2.OnDisabledState.IconRightImage = null;
            bunifuButton2.onHoverState.BorderColor = Color.FromArgb(192, 74, 62);
            bunifuButton2.onHoverState.BorderRadius = 1;
            bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton2.onHoverState.BorderThickness = 1;
            bunifuButton2.onHoverState.FillColor = Color.FromArgb(192, 74, 62);
            bunifuButton2.onHoverState.ForeColor = Color.White;
            bunifuButton2.onHoverState.IconLeftImage = null;
            bunifuButton2.onHoverState.IconRightImage = null;
            bunifuButton2.OnIdleState.BorderColor = Color.FromArgb(192, 57, 43);
            bunifuButton2.OnIdleState.BorderRadius = 1;
            bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton2.OnIdleState.BorderThickness = 1;
            bunifuButton2.OnIdleState.FillColor = Color.FromArgb(192, 57, 43);
            bunifuButton2.OnIdleState.ForeColor = Color.White;
            bunifuButton2.OnIdleState.IconLeftImage = null;
            bunifuButton2.OnIdleState.IconRightImage = null;
            bunifuButton2.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton2.OnPressedState.BorderRadius = 1;
            bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton2.OnPressedState.BorderThickness = 1;
            bunifuButton2.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton2.OnPressedState.ForeColor = Color.White;
            bunifuButton2.OnPressedState.IconLeftImage = null;
            bunifuButton2.OnPressedState.IconRightImage = null;
            bunifuButton2.Size = new Size(150, 39);
            bunifuButton2.TabIndex = 3;
            bunifuButton2.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton2.TextAlignment = HorizontalAlignment.Center;
            bunifuButton2.TextMarginLeft = 0;
            bunifuButton2.TextPadding = new Padding(0);
            bunifuButton2.UseDefaultRadiusAndThickness = true;
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Courier New", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label2.Location = new Point(419, 178);
            label2.Name = "label2";
            label2.Size = new Size(327, 16);
            label2.TabIndex = 4;
            label2.Text = "Enter your username to find your account";
            // 
            // bunifuTextBox1
            // 
            bunifuTextBox1.AcceptsReturn = false;
            bunifuTextBox1.AcceptsTab = false;
            bunifuTextBox1.AnimationSpeed = 200;
            bunifuTextBox1.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox1.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox1.AutoSizeHeight = true;
            bunifuTextBox1.BackColor = Color.Transparent;
            bunifuTextBox1.BackgroundImage = (Image)resources.GetObject("bunifuTextBox1.BackgroundImage");
            bunifuTextBox1.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox1.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox1.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox1.BorderColorIdle = Color.Silver;
            bunifuTextBox1.BorderRadius = 1;
            bunifuTextBox1.BorderThickness = 1;
            bunifuTextBox1.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox1.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox1.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox1.DefaultText = "";
            bunifuTextBox1.FillColor = Color.White;
            bunifuTextBox1.HideSelection = true;
            bunifuTextBox1.IconLeft = null;
            bunifuTextBox1.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox1.IconPadding = 10;
            bunifuTextBox1.IconRight = null;
            bunifuTextBox1.IconRightCursor = Cursors.IBeam;
            bunifuTextBox1.Location = new Point(419, 229);
            bunifuTextBox1.MaxLength = 32767;
            bunifuTextBox1.MinimumSize = new Size(1, 1);
            bunifuTextBox1.Modified = false;
            bunifuTextBox1.Multiline = false;
            bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties1.BorderColor = Color.DodgerBlue;
            stateProperties1.FillColor = Color.Empty;
            stateProperties1.ForeColor = Color.Empty;
            stateProperties1.PlaceholderForeColor = Color.Empty;
            bunifuTextBox1.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties2.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox1.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties3.FillColor = Color.Empty;
            stateProperties3.ForeColor = Color.Empty;
            stateProperties3.PlaceholderForeColor = Color.Empty;
            bunifuTextBox1.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = Color.Silver;
            stateProperties4.FillColor = Color.White;
            stateProperties4.ForeColor = Color.Empty;
            stateProperties4.PlaceholderForeColor = Color.Empty;
            bunifuTextBox1.OnIdleState = stateProperties4;
            bunifuTextBox1.Padding = new Padding(3);
            bunifuTextBox1.PasswordChar = '\0';
            bunifuTextBox1.PlaceholderForeColor = Color.Silver;
            bunifuTextBox1.PlaceholderText = "Enter text";
            bunifuTextBox1.ReadOnly = false;
            bunifuTextBox1.ScrollBars = ScrollBars.None;
            bunifuTextBox1.SelectedText = "";
            bunifuTextBox1.SelectionLength = 0;
            bunifuTextBox1.SelectionStart = 0;
            bunifuTextBox1.ShortcutsEnabled = true;
            bunifuTextBox1.Size = new Size(329, 39);
            bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox1.TabIndex = 5;
            bunifuTextBox1.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox1.TextMarginBottom = 0;
            bunifuTextBox1.TextMarginLeft = 3;
            bunifuTextBox1.TextMarginTop = 1;
            bunifuTextBox1.TextPlaceholder = "Enter text";
            bunifuTextBox1.UseSystemPasswordChar = false;
            bunifuTextBox1.WordWrap = true;
            // 
            // QuestionPanel
            // 
            QuestionPanel.Controls.Add(pictureBox2);
            QuestionPanel.Controls.Add(bunifuButton4);
            QuestionPanel.Controls.Add(bunifuButton3);
            QuestionPanel.Controls.Add(bunifuTextBox4);
            QuestionPanel.Controls.Add(bunifuTextBox3);
            QuestionPanel.Controls.Add(bunifuTextBox2);
            QuestionPanel.Controls.Add(bunifuDropdown3);
            QuestionPanel.Controls.Add(bunifuDropdown2);
            QuestionPanel.Controls.Add(bunifuDropdown1);
            QuestionPanel.Location = new Point(500, 0);
            QuestionPanel.Name = "QuestionPanel";
            QuestionPanel.Size = new Size(800, 450);
            QuestionPanel.TabIndex = 6;
            // 
            // pictureBox2
            // 
            pictureBox2.Image = Properties.Resources._try;
            pictureBox2.Location = new Point(21, 39);
            pictureBox2.Name = "pictureBox2";
            pictureBox2.Size = new Size(300, 300);
            pictureBox2.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox2.TabIndex = 8;
            pictureBox2.TabStop = false;
            // 
            // bunifuButton4
            // 
            bunifuButton4.AllowAnimations = true;
            bunifuButton4.AllowMouseEffects = true;
            bunifuButton4.AllowToggling = false;
            bunifuButton4.AnimationSpeed = 200;
            bunifuButton4.AutoGenerateColors = false;
            bunifuButton4.AutoRoundBorders = false;
            bunifuButton4.AutoSizeLeftIcon = true;
            bunifuButton4.AutoSizeRightIcon = true;
            bunifuButton4.BackColor = Color.Transparent;
            bunifuButton4.BackColor1 = Color.FromArgb(51, 122, 183);
            bunifuButton4.BackgroundImage = (Image)resources.GetObject("bunifuButton4.BackgroundImage");
            bunifuButton4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton4.ButtonText = "Back";
            bunifuButton4.ButtonTextMarginLeft = 0;
            bunifuButton4.ColorContrastOnClick = 45;
            bunifuButton4.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            bunifuButton4.CustomizableEdges = borderEdges3;
            bunifuButton4.DialogResult = DialogResult.None;
            bunifuButton4.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton4.DisabledFillColor = Color.Empty;
            bunifuButton4.DisabledForecolor = Color.Empty;
            bunifuButton4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            bunifuButton4.Font = new Font("Segoe UI", 9F);
            bunifuButton4.ForeColor = Color.White;
            bunifuButton4.IconLeft = null;
            bunifuButton4.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton4.IconLeftCursor = Cursors.Default;
            bunifuButton4.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton4.IconMarginLeft = 11;
            bunifuButton4.IconPadding = 10;
            bunifuButton4.IconRight = null;
            bunifuButton4.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton4.IconRightCursor = Cursors.Default;
            bunifuButton4.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton4.IconSize = 25;
            bunifuButton4.IdleBorderColor = Color.Empty;
            bunifuButton4.IdleBorderRadius = 0;
            bunifuButton4.IdleBorderThickness = 0;
            bunifuButton4.IdleFillColor = Color.Empty;
            bunifuButton4.IdleIconLeftImage = null;
            bunifuButton4.IdleIconRightImage = null;
            bunifuButton4.IndicateFocus = false;
            bunifuButton4.Location = new Point(412, 364);
            bunifuButton4.Name = "bunifuButton4";
            bunifuButton4.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton4.OnDisabledState.BorderRadius = 1;
            bunifuButton4.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton4.OnDisabledState.BorderThickness = 1;
            bunifuButton4.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton4.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton4.OnDisabledState.IconLeftImage = null;
            bunifuButton4.OnDisabledState.IconRightImage = null;
            bunifuButton4.onHoverState.BorderColor = Color.FromArgb(192, 74, 62);
            bunifuButton4.onHoverState.BorderRadius = 1;
            bunifuButton4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton4.onHoverState.BorderThickness = 1;
            bunifuButton4.onHoverState.FillColor = Color.FromArgb(192, 74, 62);
            bunifuButton4.onHoverState.ForeColor = Color.White;
            bunifuButton4.onHoverState.IconLeftImage = null;
            bunifuButton4.onHoverState.IconRightImage = null;
            bunifuButton4.OnIdleState.BorderColor = Color.FromArgb(192, 57, 43);
            bunifuButton4.OnIdleState.BorderRadius = 1;
            bunifuButton4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton4.OnIdleState.BorderThickness = 1;
            bunifuButton4.OnIdleState.FillColor = Color.FromArgb(192, 57, 43);
            bunifuButton4.OnIdleState.ForeColor = Color.White;
            bunifuButton4.OnIdleState.IconLeftImage = null;
            bunifuButton4.OnIdleState.IconRightImage = null;
            bunifuButton4.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton4.OnPressedState.BorderRadius = 1;
            bunifuButton4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton4.OnPressedState.BorderThickness = 1;
            bunifuButton4.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton4.OnPressedState.ForeColor = Color.White;
            bunifuButton4.OnPressedState.IconLeftImage = null;
            bunifuButton4.OnPressedState.IconRightImage = null;
            bunifuButton4.Size = new Size(155, 39);
            bunifuButton4.TabIndex = 7;
            bunifuButton4.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton4.TextAlignment = HorizontalAlignment.Center;
            bunifuButton4.TextMarginLeft = 0;
            bunifuButton4.TextPadding = new Padding(0);
            bunifuButton4.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton3
            // 
            bunifuButton3.AllowAnimations = true;
            bunifuButton3.AllowMouseEffects = true;
            bunifuButton3.AllowToggling = false;
            bunifuButton3.AnimationSpeed = 200;
            bunifuButton3.AutoGenerateColors = false;
            bunifuButton3.AutoRoundBorders = false;
            bunifuButton3.AutoSizeLeftIcon = true;
            bunifuButton3.AutoSizeRightIcon = true;
            bunifuButton3.BackColor = Color.Transparent;
            bunifuButton3.BackColor1 = Color.FromArgb(51, 122, 183);
            bunifuButton3.BackgroundImage = (Image)resources.GetObject("bunifuButton3.BackgroundImage");
            bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton3.ButtonText = "Validate";
            bunifuButton3.ButtonTextMarginLeft = 0;
            bunifuButton3.ColorContrastOnClick = 45;
            bunifuButton3.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            bunifuButton3.CustomizableEdges = borderEdges4;
            bunifuButton3.DialogResult = DialogResult.None;
            bunifuButton3.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton3.DisabledFillColor = Color.Empty;
            bunifuButton3.DisabledForecolor = Color.Empty;
            bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            bunifuButton3.Font = new Font("Segoe UI", 9F);
            bunifuButton3.ForeColor = Color.White;
            bunifuButton3.IconLeft = null;
            bunifuButton3.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton3.IconLeftCursor = Cursors.Default;
            bunifuButton3.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton3.IconMarginLeft = 11;
            bunifuButton3.IconPadding = 10;
            bunifuButton3.IconRight = null;
            bunifuButton3.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton3.IconRightCursor = Cursors.Default;
            bunifuButton3.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton3.IconSize = 25;
            bunifuButton3.IdleBorderColor = Color.Empty;
            bunifuButton3.IdleBorderRadius = 0;
            bunifuButton3.IdleBorderThickness = 0;
            bunifuButton3.IdleFillColor = Color.Empty;
            bunifuButton3.IdleIconLeftImage = null;
            bunifuButton3.IdleIconRightImage = null;
            bunifuButton3.IndicateFocus = false;
            bunifuButton3.Location = new Point(576, 364);
            bunifuButton3.Name = "bunifuButton3";
            bunifuButton3.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton3.OnDisabledState.BorderRadius = 1;
            bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton3.OnDisabledState.BorderThickness = 1;
            bunifuButton3.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton3.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton3.OnDisabledState.IconLeftImage = null;
            bunifuButton3.OnDisabledState.IconRightImage = null;
            bunifuButton3.onHoverState.BorderColor = Color.FromArgb(192, 74, 62);
            bunifuButton3.onHoverState.BorderRadius = 1;
            bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton3.onHoverState.BorderThickness = 1;
            bunifuButton3.onHoverState.FillColor = Color.FromArgb(192, 74, 62);
            bunifuButton3.onHoverState.ForeColor = Color.White;
            bunifuButton3.onHoverState.IconLeftImage = null;
            bunifuButton3.onHoverState.IconRightImage = null;
            bunifuButton3.OnIdleState.BorderColor = Color.FromArgb(192, 57, 43);
            bunifuButton3.OnIdleState.BorderRadius = 1;
            bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton3.OnIdleState.BorderThickness = 1;
            bunifuButton3.OnIdleState.FillColor = Color.FromArgb(192, 57, 43);
            bunifuButton3.OnIdleState.ForeColor = Color.White;
            bunifuButton3.OnIdleState.IconLeftImage = null;
            bunifuButton3.OnIdleState.IconRightImage = null;
            bunifuButton3.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            bunifuButton3.OnPressedState.BorderRadius = 1;
            bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            bunifuButton3.OnPressedState.BorderThickness = 1;
            bunifuButton3.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            bunifuButton3.OnPressedState.ForeColor = Color.White;
            bunifuButton3.OnPressedState.IconLeftImage = null;
            bunifuButton3.OnPressedState.IconRightImage = null;
            bunifuButton3.Size = new Size(155, 39);
            bunifuButton3.TabIndex = 6;
            bunifuButton3.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton3.TextAlignment = HorizontalAlignment.Center;
            bunifuButton3.TextMarginLeft = 0;
            bunifuButton3.TextPadding = new Padding(0);
            bunifuButton3.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuTextBox4
            // 
            bunifuTextBox4.AcceptsReturn = false;
            bunifuTextBox4.AcceptsTab = false;
            bunifuTextBox4.AnimationSpeed = 200;
            bunifuTextBox4.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox4.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox4.AutoSizeHeight = true;
            bunifuTextBox4.BackColor = Color.Transparent;
            bunifuTextBox4.BackgroundImage = (Image)resources.GetObject("bunifuTextBox4.BackgroundImage");
            bunifuTextBox4.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox4.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox4.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox4.BorderColorIdle = Color.Silver;
            bunifuTextBox4.BorderRadius = 1;
            bunifuTextBox4.BorderThickness = 1;
            bunifuTextBox4.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox4.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox4.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox4.DefaultText = "";
            bunifuTextBox4.FillColor = Color.White;
            bunifuTextBox4.HideSelection = true;
            bunifuTextBox4.IconLeft = null;
            bunifuTextBox4.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox4.IconPadding = 10;
            bunifuTextBox4.IconRight = null;
            bunifuTextBox4.IconRightCursor = Cursors.IBeam;
            bunifuTextBox4.Location = new Point(343, 298);
            bunifuTextBox4.MaxLength = 32767;
            bunifuTextBox4.MinimumSize = new Size(1, 1);
            bunifuTextBox4.Modified = false;
            bunifuTextBox4.Multiline = false;
            bunifuTextBox4.Name = "bunifuTextBox4";
            stateProperties5.BorderColor = Color.DodgerBlue;
            stateProperties5.FillColor = Color.Empty;
            stateProperties5.ForeColor = Color.Empty;
            stateProperties5.PlaceholderForeColor = Color.Empty;
            bunifuTextBox4.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties6.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox4.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties7.FillColor = Color.Empty;
            stateProperties7.ForeColor = Color.Empty;
            stateProperties7.PlaceholderForeColor = Color.Empty;
            bunifuTextBox4.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = Color.Silver;
            stateProperties8.FillColor = Color.White;
            stateProperties8.ForeColor = Color.Empty;
            stateProperties8.PlaceholderForeColor = Color.Empty;
            bunifuTextBox4.OnIdleState = stateProperties8;
            bunifuTextBox4.Padding = new Padding(3);
            bunifuTextBox4.PasswordChar = '\0';
            bunifuTextBox4.PlaceholderForeColor = Color.Silver;
            bunifuTextBox4.PlaceholderText = "Enter text";
            bunifuTextBox4.ReadOnly = false;
            bunifuTextBox4.ScrollBars = ScrollBars.None;
            bunifuTextBox4.SelectedText = "";
            bunifuTextBox4.SelectionLength = 0;
            bunifuTextBox4.SelectionStart = 0;
            bunifuTextBox4.ShortcutsEnabled = true;
            bunifuTextBox4.Size = new Size(388, 32);
            bunifuTextBox4.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox4.TabIndex = 5;
            bunifuTextBox4.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox4.TextMarginBottom = 0;
            bunifuTextBox4.TextMarginLeft = 3;
            bunifuTextBox4.TextMarginTop = 1;
            bunifuTextBox4.TextPlaceholder = "Enter text";
            bunifuTextBox4.UseSystemPasswordChar = false;
            bunifuTextBox4.WordWrap = true;
            // 
            // bunifuTextBox3
            // 
            bunifuTextBox3.AcceptsReturn = false;
            bunifuTextBox3.AcceptsTab = false;
            bunifuTextBox3.AnimationSpeed = 200;
            bunifuTextBox3.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox3.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox3.AutoSizeHeight = true;
            bunifuTextBox3.BackColor = Color.Transparent;
            bunifuTextBox3.BackgroundImage = (Image)resources.GetObject("bunifuTextBox3.BackgroundImage");
            bunifuTextBox3.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox3.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox3.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox3.BorderColorIdle = Color.Silver;
            bunifuTextBox3.BorderRadius = 1;
            bunifuTextBox3.BorderThickness = 1;
            bunifuTextBox3.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox3.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox3.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox3.DefaultText = "";
            bunifuTextBox3.FillColor = Color.White;
            bunifuTextBox3.HideSelection = true;
            bunifuTextBox3.IconLeft = null;
            bunifuTextBox3.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox3.IconPadding = 10;
            bunifuTextBox3.IconRight = null;
            bunifuTextBox3.IconRightCursor = Cursors.IBeam;
            bunifuTextBox3.Location = new Point(343, 191);
            bunifuTextBox3.MaxLength = 32767;
            bunifuTextBox3.MinimumSize = new Size(1, 1);
            bunifuTextBox3.Modified = false;
            bunifuTextBox3.Multiline = false;
            bunifuTextBox3.Name = "bunifuTextBox3";
            stateProperties9.BorderColor = Color.DodgerBlue;
            stateProperties9.FillColor = Color.Empty;
            stateProperties9.ForeColor = Color.Empty;
            stateProperties9.PlaceholderForeColor = Color.Empty;
            bunifuTextBox3.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties10.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox3.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties11.FillColor = Color.Empty;
            stateProperties11.ForeColor = Color.Empty;
            stateProperties11.PlaceholderForeColor = Color.Empty;
            bunifuTextBox3.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = Color.Silver;
            stateProperties12.FillColor = Color.White;
            stateProperties12.ForeColor = Color.Empty;
            stateProperties12.PlaceholderForeColor = Color.Empty;
            bunifuTextBox3.OnIdleState = stateProperties12;
            bunifuTextBox3.Padding = new Padding(3);
            bunifuTextBox3.PasswordChar = '\0';
            bunifuTextBox3.PlaceholderForeColor = Color.Silver;
            bunifuTextBox3.PlaceholderText = "Enter text";
            bunifuTextBox3.ReadOnly = false;
            bunifuTextBox3.ScrollBars = ScrollBars.None;
            bunifuTextBox3.SelectedText = "";
            bunifuTextBox3.SelectionLength = 0;
            bunifuTextBox3.SelectionStart = 0;
            bunifuTextBox3.ShortcutsEnabled = true;
            bunifuTextBox3.Size = new Size(388, 32);
            bunifuTextBox3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox3.TabIndex = 4;
            bunifuTextBox3.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox3.TextMarginBottom = 0;
            bunifuTextBox3.TextMarginLeft = 3;
            bunifuTextBox3.TextMarginTop = 1;
            bunifuTextBox3.TextPlaceholder = "Enter text";
            bunifuTextBox3.UseSystemPasswordChar = false;
            bunifuTextBox3.WordWrap = true;
            // 
            // bunifuTextBox2
            // 
            bunifuTextBox2.AcceptsReturn = false;
            bunifuTextBox2.AcceptsTab = false;
            bunifuTextBox2.AnimationSpeed = 200;
            bunifuTextBox2.AutoCompleteMode = AutoCompleteMode.None;
            bunifuTextBox2.AutoCompleteSource = AutoCompleteSource.None;
            bunifuTextBox2.AutoSizeHeight = true;
            bunifuTextBox2.BackColor = Color.Transparent;
            bunifuTextBox2.BackgroundImage = (Image)resources.GetObject("bunifuTextBox2.BackgroundImage");
            bunifuTextBox2.BorderColorActive = Color.DodgerBlue;
            bunifuTextBox2.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            bunifuTextBox2.BorderColorHover = Color.FromArgb(105, 181, 255);
            bunifuTextBox2.BorderColorIdle = Color.Silver;
            bunifuTextBox2.BorderRadius = 1;
            bunifuTextBox2.BorderThickness = 1;
            bunifuTextBox2.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            bunifuTextBox2.CharacterCasing = CharacterCasing.Normal;
            bunifuTextBox2.DefaultFont = new Font("Segoe UI", 9.25F);
            bunifuTextBox2.DefaultText = "";
            bunifuTextBox2.FillColor = Color.White;
            bunifuTextBox2.HideSelection = true;
            bunifuTextBox2.IconLeft = null;
            bunifuTextBox2.IconLeftCursor = Cursors.IBeam;
            bunifuTextBox2.IconPadding = 10;
            bunifuTextBox2.IconRight = null;
            bunifuTextBox2.IconRightCursor = Cursors.IBeam;
            bunifuTextBox2.Location = new Point(343, 92);
            bunifuTextBox2.MaxLength = 32767;
            bunifuTextBox2.MinimumSize = new Size(1, 1);
            bunifuTextBox2.Modified = false;
            bunifuTextBox2.Multiline = false;
            bunifuTextBox2.Name = "bunifuTextBox2";
            stateProperties13.BorderColor = Color.DodgerBlue;
            stateProperties13.FillColor = Color.Empty;
            stateProperties13.ForeColor = Color.Empty;
            stateProperties13.PlaceholderForeColor = Color.Empty;
            bunifuTextBox2.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties14.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties14.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties14.PlaceholderForeColor = Color.DarkGray;
            bunifuTextBox2.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties15.FillColor = Color.Empty;
            stateProperties15.ForeColor = Color.Empty;
            stateProperties15.PlaceholderForeColor = Color.Empty;
            bunifuTextBox2.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = Color.Silver;
            stateProperties16.FillColor = Color.White;
            stateProperties16.ForeColor = Color.Empty;
            stateProperties16.PlaceholderForeColor = Color.Empty;
            bunifuTextBox2.OnIdleState = stateProperties16;
            bunifuTextBox2.Padding = new Padding(3);
            bunifuTextBox2.PasswordChar = '\0';
            bunifuTextBox2.PlaceholderForeColor = Color.Silver;
            bunifuTextBox2.PlaceholderText = "Enter text";
            bunifuTextBox2.ReadOnly = false;
            bunifuTextBox2.ScrollBars = ScrollBars.None;
            bunifuTextBox2.SelectedText = "";
            bunifuTextBox2.SelectionLength = 0;
            bunifuTextBox2.SelectionStart = 0;
            bunifuTextBox2.ShortcutsEnabled = true;
            bunifuTextBox2.Size = new Size(388, 32);
            bunifuTextBox2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            bunifuTextBox2.TabIndex = 3;
            bunifuTextBox2.TextAlign = HorizontalAlignment.Left;
            bunifuTextBox2.TextMarginBottom = 0;
            bunifuTextBox2.TextMarginLeft = 3;
            bunifuTextBox2.TextMarginTop = 1;
            bunifuTextBox2.TextPlaceholder = "Enter text";
            bunifuTextBox2.UseSystemPasswordChar = false;
            bunifuTextBox2.WordWrap = true;
            // 
            // bunifuDropdown3
            // 
            bunifuDropdown3.BackColor = Color.Transparent;
            bunifuDropdown3.BackgroundColor = Color.White;
            bunifuDropdown3.BorderColor = Color.Silver;
            bunifuDropdown3.BorderRadius = 1;
            bunifuDropdown3.Color = Color.Silver;
            bunifuDropdown3.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            bunifuDropdown3.DisabledBackColor = Color.FromArgb(240, 240, 240);
            bunifuDropdown3.DisabledBorderColor = Color.FromArgb(204, 204, 204);
            bunifuDropdown3.DisabledColor = Color.FromArgb(240, 240, 240);
            bunifuDropdown3.DisabledForeColor = Color.FromArgb(109, 109, 109);
            bunifuDropdown3.DisabledIndicatorColor = Color.DarkGray;
            bunifuDropdown3.DrawMode = DrawMode.OwnerDrawFixed;
            bunifuDropdown3.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            bunifuDropdown3.DropDownStyle = ComboBoxStyle.DropDownList;
            bunifuDropdown3.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            bunifuDropdown3.FillDropDown = true;
            bunifuDropdown3.FillIndicator = false;
            bunifuDropdown3.FlatStyle = FlatStyle.Flat;
            bunifuDropdown3.Font = new Font("Segoe UI", 9F);
            bunifuDropdown3.ForeColor = Color.Black;
            bunifuDropdown3.FormattingEnabled = true;
            bunifuDropdown3.Icon = null;
            bunifuDropdown3.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            bunifuDropdown3.IndicatorColor = Color.DarkGray;
            bunifuDropdown3.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            bunifuDropdown3.IndicatorThickness = 2;
            bunifuDropdown3.IsDropdownOpened = false;
            bunifuDropdown3.ItemBackColor = Color.White;
            bunifuDropdown3.ItemBorderColor = Color.White;
            bunifuDropdown3.ItemForeColor = Color.Black;
            bunifuDropdown3.ItemHeight = 26;
            bunifuDropdown3.ItemHighLightColor = Color.DodgerBlue;
            bunifuDropdown3.ItemHighLightForeColor = Color.White;
            bunifuDropdown3.ItemTopMargin = 3;
            bunifuDropdown3.Location = new Point(343, 245);
            bunifuDropdown3.Name = "bunifuDropdown3";
            bunifuDropdown3.Size = new Size(388, 32);
            bunifuDropdown3.TabIndex = 2;
            bunifuDropdown3.Text = null;
            bunifuDropdown3.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            bunifuDropdown3.TextLeftMargin = 5;
            // 
            // bunifuDropdown2
            // 
            bunifuDropdown2.BackColor = Color.Transparent;
            bunifuDropdown2.BackgroundColor = Color.White;
            bunifuDropdown2.BorderColor = Color.Silver;
            bunifuDropdown2.BorderRadius = 1;
            bunifuDropdown2.Color = Color.Silver;
            bunifuDropdown2.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            bunifuDropdown2.DisabledBackColor = Color.FromArgb(240, 240, 240);
            bunifuDropdown2.DisabledBorderColor = Color.FromArgb(204, 204, 204);
            bunifuDropdown2.DisabledColor = Color.FromArgb(240, 240, 240);
            bunifuDropdown2.DisabledForeColor = Color.FromArgb(109, 109, 109);
            bunifuDropdown2.DisabledIndicatorColor = Color.DarkGray;
            bunifuDropdown2.DrawMode = DrawMode.OwnerDrawFixed;
            bunifuDropdown2.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            bunifuDropdown2.DropDownStyle = ComboBoxStyle.DropDownList;
            bunifuDropdown2.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            bunifuDropdown2.FillDropDown = true;
            bunifuDropdown2.FillIndicator = false;
            bunifuDropdown2.FlatStyle = FlatStyle.Flat;
            bunifuDropdown2.Font = new Font("Segoe UI", 9F);
            bunifuDropdown2.ForeColor = Color.Black;
            bunifuDropdown2.FormattingEnabled = true;
            bunifuDropdown2.Icon = null;
            bunifuDropdown2.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            bunifuDropdown2.IndicatorColor = Color.DarkGray;
            bunifuDropdown2.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            bunifuDropdown2.IndicatorThickness = 2;
            bunifuDropdown2.IsDropdownOpened = false;
            bunifuDropdown2.ItemBackColor = Color.White;
            bunifuDropdown2.ItemBorderColor = Color.White;
            bunifuDropdown2.ItemForeColor = Color.Black;
            bunifuDropdown2.ItemHeight = 26;
            bunifuDropdown2.ItemHighLightColor = Color.DodgerBlue;
            bunifuDropdown2.ItemHighLightForeColor = Color.White;
            bunifuDropdown2.ItemTopMargin = 3;
            bunifuDropdown2.Location = new Point(343, 143);
            bunifuDropdown2.Name = "bunifuDropdown2";
            bunifuDropdown2.Size = new Size(388, 32);
            bunifuDropdown2.TabIndex = 1;
            bunifuDropdown2.Text = null;
            bunifuDropdown2.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            bunifuDropdown2.TextLeftMargin = 5;
            // 
            // bunifuDropdown1
            // 
            bunifuDropdown1.BackColor = Color.Transparent;
            bunifuDropdown1.BackgroundColor = Color.White;
            bunifuDropdown1.BorderColor = Color.Silver;
            bunifuDropdown1.BorderRadius = 1;
            bunifuDropdown1.Color = Color.Silver;
            bunifuDropdown1.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            bunifuDropdown1.DisabledBackColor = Color.FromArgb(240, 240, 240);
            bunifuDropdown1.DisabledBorderColor = Color.FromArgb(204, 204, 204);
            bunifuDropdown1.DisabledColor = Color.FromArgb(240, 240, 240);
            bunifuDropdown1.DisabledForeColor = Color.FromArgb(109, 109, 109);
            bunifuDropdown1.DisabledIndicatorColor = Color.DarkGray;
            bunifuDropdown1.DrawMode = DrawMode.OwnerDrawFixed;
            bunifuDropdown1.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            bunifuDropdown1.DropDownStyle = ComboBoxStyle.DropDownList;
            bunifuDropdown1.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            bunifuDropdown1.FillDropDown = true;
            bunifuDropdown1.FillIndicator = false;
            bunifuDropdown1.FlatStyle = FlatStyle.Flat;
            bunifuDropdown1.Font = new Font("Segoe UI", 9F);
            bunifuDropdown1.ForeColor = Color.Black;
            bunifuDropdown1.FormattingEnabled = true;
            bunifuDropdown1.Icon = null;
            bunifuDropdown1.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            bunifuDropdown1.IndicatorColor = Color.DarkGray;
            bunifuDropdown1.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            bunifuDropdown1.IndicatorThickness = 2;
            bunifuDropdown1.IsDropdownOpened = false;
            bunifuDropdown1.ItemBackColor = Color.White;
            bunifuDropdown1.ItemBorderColor = Color.White;
            bunifuDropdown1.ItemForeColor = Color.Black;
            bunifuDropdown1.ItemHeight = 26;
            bunifuDropdown1.ItemHighLightColor = Color.DodgerBlue;
            bunifuDropdown1.ItemHighLightForeColor = Color.White;
            bunifuDropdown1.ItemTopMargin = 3;
            bunifuDropdown1.Location = new Point(343, 39);
            bunifuDropdown1.Name = "bunifuDropdown1";
            bunifuDropdown1.Size = new Size(388, 32);
            bunifuDropdown1.TabIndex = 0;
            bunifuDropdown1.Text = null;
            bunifuDropdown1.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            bunifuDropdown1.TextLeftMargin = 5;
            // 
            // ForgotPasswordModal
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            ClientSize = new Size(800, 450);
            Controls.Add(QuestionPanel);
            Controls.Add(bunifuTextBox1);
            Controls.Add(label2);
            Controls.Add(bunifuButton2);
            Controls.Add(label1);
            Controls.Add(bunifuButton1);
            Controls.Add(pictureBox1);
            FormBorderStyle = FormBorderStyle.None;
            Name = "ForgotPasswordModal";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "ForgotPasswordModal";
            ((System.ComponentModel.ISupportInitialize)pictureBox1).EndInit();
            QuestionPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)pictureBox2).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        private Panel QuestionPanel;
        private PictureBox pictureBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox4;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox3;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox2;
        private Bunifu.UI.WinForms.BunifuDropdown bunifuDropdown3;
        private Bunifu.UI.WinForms.BunifuDropdown bunifuDropdown2;
        private Bunifu.UI.WinForms.BunifuDropdown bunifuDropdown1;
    }
}