namespace DazaBestApplication.Modals
{
    partial class ForgotPasswordModal
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ForgotPasswordModal));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            pictureBox1 = new PictureBox();
            btncancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            label1 = new Label();
            btnNext = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            label2 = new Label();
            ForgotUsernameTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            QuestionPanel = new Panel();
            question3 = new Label();
            question2 = new Label();
            question1 = new Label();
            panel1 = new Panel();
            panel5 = new Panel();
            label6 = new Label();
            pictureBox2 = new PictureBox();
            BackBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ValidateBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            answer3 = new Bunifu.UI.WinForms.BunifuTextBox();
            answer2 = new Bunifu.UI.WinForms.BunifuTextBox();
            answer1 = new Bunifu.UI.WinForms.BunifuTextBox();
            ResetPassPanel = new Panel();
            label5 = new Label();
            label4 = new Label();
            reenterpasswordtxt = new Bunifu.UI.WinForms.BunifuTextBox();
            newpasswordtxt = new Bunifu.UI.WinForms.BunifuTextBox();
            panel4 = new Panel();
            CancelBtn2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ResetPassBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            panel2 = new Panel();
            panel3 = new Panel();
            label3 = new Label();
            panel6 = new Panel();
            panel7 = new Panel();
            label7 = new Label();
            ((System.ComponentModel.ISupportInitialize)pictureBox1).BeginInit();
            QuestionPanel.SuspendLayout();
            panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox2).BeginInit();
            ResetPassPanel.SuspendLayout();
            panel4.SuspendLayout();
            panel2.SuspendLayout();
            panel6.SuspendLayout();
            SuspendLayout();
            // 
            // pictureBox1
            // 
            pictureBox1.Image = Properties.Resources._try;
            pictureBox1.Location = new Point(37, 58);
            pictureBox1.Name = "pictureBox1";
            pictureBox1.Size = new Size(300, 300);
            pictureBox1.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox1.TabIndex = 0;
            pictureBox1.TabStop = false;
            // 
            // btncancel
            // 
            btncancel.AllowAnimations = true;
            btncancel.AllowMouseEffects = true;
            btncancel.AllowToggling = false;
            btncancel.AnimationSpeed = 200;
            btncancel.AutoGenerateColors = false;
            btncancel.AutoRoundBorders = false;
            btncancel.AutoSizeLeftIcon = true;
            btncancel.AutoSizeRightIcon = true;
            btncancel.BackColor = Color.Transparent;
            btncancel.BackColor1 = Color.FromArgb(51, 122, 183);
            btncancel.BackgroundImage = (Image)resources.GetObject("btncancel.BackgroundImage");
            btncancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btncancel.ButtonText = "Cancel";
            btncancel.ButtonTextMarginLeft = 0;
            btncancel.ColorContrastOnClick = 45;
            btncancel.ColorContrastOnHover = 45;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            btncancel.CustomizableEdges = borderEdges1;
            btncancel.DialogResult = DialogResult.None;
            btncancel.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btncancel.DisabledFillColor = Color.Empty;
            btncancel.DisabledForecolor = Color.Empty;
            btncancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            btncancel.Font = new Font("Segoe UI", 9F);
            btncancel.ForeColor = Color.White;
            btncancel.IconLeft = null;
            btncancel.IconLeftAlign = ContentAlignment.MiddleLeft;
            btncancel.IconLeftCursor = Cursors.Default;
            btncancel.IconLeftPadding = new Padding(11, 3, 3, 3);
            btncancel.IconMarginLeft = 11;
            btncancel.IconPadding = 10;
            btncancel.IconRight = null;
            btncancel.IconRightAlign = ContentAlignment.MiddleRight;
            btncancel.IconRightCursor = Cursors.Default;
            btncancel.IconRightPadding = new Padding(3, 3, 7, 3);
            btncancel.IconSize = 25;
            btncancel.IdleBorderColor = Color.Empty;
            btncancel.IdleBorderRadius = 0;
            btncancel.IdleBorderThickness = 0;
            btncancel.IdleFillColor = Color.Empty;
            btncancel.IdleIconLeftImage = null;
            btncancel.IdleIconRightImage = null;
            btncancel.IndicateFocus = false;
            btncancel.Location = new Point(417, 319);
            btncancel.Name = "btncancel";
            btncancel.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btncancel.OnDisabledState.BorderRadius = 1;
            btncancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btncancel.OnDisabledState.BorderThickness = 1;
            btncancel.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btncancel.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btncancel.OnDisabledState.IconLeftImage = null;
            btncancel.OnDisabledState.IconRightImage = null;
            btncancel.onHoverState.BorderColor = Color.FromArgb(192, 74, 62);
            btncancel.onHoverState.BorderRadius = 1;
            btncancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btncancel.onHoverState.BorderThickness = 1;
            btncancel.onHoverState.FillColor = Color.FromArgb(192, 74, 62);
            btncancel.onHoverState.ForeColor = Color.White;
            btncancel.onHoverState.IconLeftImage = null;
            btncancel.onHoverState.IconRightImage = null;
            btncancel.OnIdleState.BorderColor = Color.FromArgb(192, 57, 43);
            btncancel.OnIdleState.BorderRadius = 1;
            btncancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btncancel.OnIdleState.BorderThickness = 1;
            btncancel.OnIdleState.FillColor = Color.FromArgb(192, 57, 43);
            btncancel.OnIdleState.ForeColor = Color.White;
            btncancel.OnIdleState.IconLeftImage = null;
            btncancel.OnIdleState.IconRightImage = null;
            btncancel.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btncancel.OnPressedState.BorderRadius = 1;
            btncancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btncancel.OnPressedState.BorderThickness = 1;
            btncancel.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btncancel.OnPressedState.ForeColor = Color.White;
            btncancel.OnPressedState.IconLeftImage = null;
            btncancel.OnPressedState.IconRightImage = null;
            btncancel.Size = new Size(150, 39);
            btncancel.TabIndex = 1;
            btncancel.TextAlign = ContentAlignment.MiddleCenter;
            btncancel.TextAlignment = HorizontalAlignment.Center;
            btncancel.TextMarginLeft = 0;
            btncancel.TextPadding = new Padding(0);
            btncancel.UseDefaultRadiusAndThickness = true;
            btncancel.Click += btncancel_Click;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Courier New", 27.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label1.ForeColor = Color.FromArgb(192, 57, 43);
            label1.Location = new Point(419, 59);
            label1.Name = "label1";
            label1.Size = new Size(216, 82);
            label1.TabIndex = 2;
            label1.Text = "Forgot\r\nPassword?";
            // 
            // btnNext
            // 
            btnNext.AllowAnimations = true;
            btnNext.AllowMouseEffects = true;
            btnNext.AllowToggling = false;
            btnNext.AnimationSpeed = 200;
            btnNext.AutoGenerateColors = false;
            btnNext.AutoRoundBorders = false;
            btnNext.AutoSizeLeftIcon = true;
            btnNext.AutoSizeRightIcon = true;
            btnNext.BackColor = Color.Transparent;
            btnNext.BackColor1 = Color.FromArgb(51, 122, 183);
            btnNext.BackgroundImage = (Image)resources.GetObject("btnNext.BackgroundImage");
            btnNext.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnNext.ButtonText = "Next";
            btnNext.ButtonTextMarginLeft = 0;
            btnNext.ColorContrastOnClick = 45;
            btnNext.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            btnNext.CustomizableEdges = borderEdges2;
            btnNext.DialogResult = DialogResult.None;
            btnNext.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnNext.DisabledFillColor = Color.Empty;
            btnNext.DisabledForecolor = Color.Empty;
            btnNext.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            btnNext.Font = new Font("Segoe UI", 9F);
            btnNext.ForeColor = Color.White;
            btnNext.IconLeft = null;
            btnNext.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnNext.IconLeftCursor = Cursors.Default;
            btnNext.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnNext.IconMarginLeft = 11;
            btnNext.IconPadding = 10;
            btnNext.IconRight = null;
            btnNext.IconRightAlign = ContentAlignment.MiddleRight;
            btnNext.IconRightCursor = Cursors.Default;
            btnNext.IconRightPadding = new Padding(3, 3, 7, 3);
            btnNext.IconSize = 25;
            btnNext.IdleBorderColor = Color.Empty;
            btnNext.IdleBorderRadius = 0;
            btnNext.IdleBorderThickness = 0;
            btnNext.IdleFillColor = Color.Empty;
            btnNext.IdleIconLeftImage = null;
            btnNext.IdleIconRightImage = null;
            btnNext.IndicateFocus = false;
            btnNext.Location = new Point(596, 319);
            btnNext.Name = "btnNext";
            btnNext.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnNext.OnDisabledState.BorderRadius = 1;
            btnNext.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnNext.OnDisabledState.BorderThickness = 1;
            btnNext.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnNext.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnNext.OnDisabledState.IconLeftImage = null;
            btnNext.OnDisabledState.IconRightImage = null;
            btnNext.onHoverState.BorderColor = Color.FromArgb(192, 74, 62);
            btnNext.onHoverState.BorderRadius = 1;
            btnNext.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnNext.onHoverState.BorderThickness = 1;
            btnNext.onHoverState.FillColor = Color.FromArgb(192, 74, 62);
            btnNext.onHoverState.ForeColor = Color.White;
            btnNext.onHoverState.IconLeftImage = null;
            btnNext.onHoverState.IconRightImage = null;
            btnNext.OnIdleState.BorderColor = Color.FromArgb(192, 57, 43);
            btnNext.OnIdleState.BorderRadius = 1;
            btnNext.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnNext.OnIdleState.BorderThickness = 1;
            btnNext.OnIdleState.FillColor = Color.FromArgb(192, 57, 43);
            btnNext.OnIdleState.ForeColor = Color.White;
            btnNext.OnIdleState.IconLeftImage = null;
            btnNext.OnIdleState.IconRightImage = null;
            btnNext.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnNext.OnPressedState.BorderRadius = 1;
            btnNext.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnNext.OnPressedState.BorderThickness = 1;
            btnNext.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnNext.OnPressedState.ForeColor = Color.White;
            btnNext.OnPressedState.IconLeftImage = null;
            btnNext.OnPressedState.IconRightImage = null;
            btnNext.Size = new Size(150, 39);
            btnNext.TabIndex = 3;
            btnNext.TextAlign = ContentAlignment.MiddleCenter;
            btnNext.TextAlignment = HorizontalAlignment.Center;
            btnNext.TextMarginLeft = 0;
            btnNext.TextPadding = new Padding(0);
            btnNext.UseDefaultRadiusAndThickness = true;
            btnNext.Click += btnNext_Click;
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Courier New", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label2.Location = new Point(419, 178);
            label2.Name = "label2";
            label2.Size = new Size(327, 16);
            label2.TabIndex = 4;
            label2.Text = "Enter your username to find your account";
            // 
            // ForgotUsernameTxt
            // 
            ForgotUsernameTxt.AcceptsReturn = false;
            ForgotUsernameTxt.AcceptsTab = false;
            ForgotUsernameTxt.AnimationSpeed = 200;
            ForgotUsernameTxt.AutoCompleteMode = AutoCompleteMode.None;
            ForgotUsernameTxt.AutoCompleteSource = AutoCompleteSource.None;
            ForgotUsernameTxt.AutoSizeHeight = true;
            ForgotUsernameTxt.BackColor = Color.Transparent;
            ForgotUsernameTxt.BackgroundImage = (Image)resources.GetObject("ForgotUsernameTxt.BackgroundImage");
            ForgotUsernameTxt.BorderColorActive = Color.DodgerBlue;
            ForgotUsernameTxt.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            ForgotUsernameTxt.BorderColorHover = Color.FromArgb(105, 181, 255);
            ForgotUsernameTxt.BorderColorIdle = Color.Silver;
            ForgotUsernameTxt.BorderRadius = 1;
            ForgotUsernameTxt.BorderThickness = 1;
            ForgotUsernameTxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            ForgotUsernameTxt.CharacterCasing = CharacterCasing.Normal;
            ForgotUsernameTxt.DefaultFont = new Font("Segoe UI", 9.25F);
            ForgotUsernameTxt.DefaultText = "";
            ForgotUsernameTxt.FillColor = Color.White;
            ForgotUsernameTxt.HideSelection = true;
            ForgotUsernameTxt.IconLeft = null;
            ForgotUsernameTxt.IconLeftCursor = Cursors.IBeam;
            ForgotUsernameTxt.IconPadding = 10;
            ForgotUsernameTxt.IconRight = null;
            ForgotUsernameTxt.IconRightCursor = Cursors.IBeam;
            ForgotUsernameTxt.Location = new Point(419, 229);
            ForgotUsernameTxt.MaxLength = 32767;
            ForgotUsernameTxt.MinimumSize = new Size(1, 1);
            ForgotUsernameTxt.Modified = false;
            ForgotUsernameTxt.Multiline = false;
            ForgotUsernameTxt.Name = "ForgotUsernameTxt";
            stateProperties1.BorderColor = Color.DodgerBlue;
            stateProperties1.FillColor = Color.Empty;
            stateProperties1.ForeColor = Color.Empty;
            stateProperties1.PlaceholderForeColor = Color.Empty;
            ForgotUsernameTxt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties2.PlaceholderForeColor = Color.DarkGray;
            ForgotUsernameTxt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties3.FillColor = Color.Empty;
            stateProperties3.ForeColor = Color.Empty;
            stateProperties3.PlaceholderForeColor = Color.Empty;
            ForgotUsernameTxt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = Color.Silver;
            stateProperties4.FillColor = Color.White;
            stateProperties4.ForeColor = Color.Empty;
            stateProperties4.PlaceholderForeColor = Color.Empty;
            ForgotUsernameTxt.OnIdleState = stateProperties4;
            ForgotUsernameTxt.Padding = new Padding(3);
            ForgotUsernameTxt.PasswordChar = '\0';
            ForgotUsernameTxt.PlaceholderForeColor = Color.Silver;
            ForgotUsernameTxt.PlaceholderText = "Enter text";
            ForgotUsernameTxt.ReadOnly = false;
            ForgotUsernameTxt.ScrollBars = ScrollBars.None;
            ForgotUsernameTxt.SelectedText = "";
            ForgotUsernameTxt.SelectionLength = 0;
            ForgotUsernameTxt.SelectionStart = 0;
            ForgotUsernameTxt.ShortcutsEnabled = true;
            ForgotUsernameTxt.Size = new Size(329, 39);
            ForgotUsernameTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            ForgotUsernameTxt.TabIndex = 5;
            ForgotUsernameTxt.TextAlign = HorizontalAlignment.Left;
            ForgotUsernameTxt.TextMarginBottom = 0;
            ForgotUsernameTxt.TextMarginLeft = 3;
            ForgotUsernameTxt.TextMarginTop = 1;
            ForgotUsernameTxt.TextPlaceholder = "Enter text";
            ForgotUsernameTxt.UseSystemPasswordChar = false;
            ForgotUsernameTxt.WordWrap = true;
            // 
            // QuestionPanel
            // 
            QuestionPanel.Controls.Add(question3);
            QuestionPanel.Controls.Add(question2);
            QuestionPanel.Controls.Add(question1);
            QuestionPanel.Controls.Add(panel1);
            QuestionPanel.Controls.Add(pictureBox2);
            QuestionPanel.Controls.Add(BackBtn);
            QuestionPanel.Controls.Add(ValidateBtn);
            QuestionPanel.Controls.Add(answer3);
            QuestionPanel.Controls.Add(answer2);
            QuestionPanel.Controls.Add(answer1);
            QuestionPanel.Location = new Point(1121, 46);
            QuestionPanel.Name = "QuestionPanel";
            QuestionPanel.Size = new Size(800, 450);
            QuestionPanel.TabIndex = 6;
            // 
            // question3
            // 
            question3.BorderStyle = BorderStyle.FixedSingle;
            question3.Font = new Font("Courier New", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            question3.Location = new Point(343, 271);
            question3.Name = "question3";
            question3.Size = new Size(388, 32);
            question3.TabIndex = 12;
            question3.Text = "Question3";
            // 
            // question2
            // 
            question2.BorderStyle = BorderStyle.FixedSingle;
            question2.Font = new Font("Courier New", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            question2.Location = new Point(343, 171);
            question2.Name = "question2";
            question2.Size = new Size(388, 32);
            question2.TabIndex = 11;
            question2.Text = "Question2";
            // 
            // question1
            // 
            question1.BorderStyle = BorderStyle.FixedSingle;
            question1.Font = new Font("Courier New", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            question1.Location = new Point(343, 70);
            question1.Name = "question1";
            question1.Size = new Size(388, 32);
            question1.TabIndex = 10;
            question1.Text = "Question1";
            // 
            // panel1
            // 
            panel1.BackColor = Color.White;
            panel1.Controls.Add(panel5);
            panel1.Controls.Add(label6);
            panel1.Dock = DockStyle.Top;
            panel1.Location = new Point(0, 0);
            panel1.Name = "panel1";
            panel1.Size = new Size(800, 40);
            panel1.TabIndex = 9;
            // 
            // panel5
            // 
            panel5.BackColor = Color.Maroon;
            panel5.Dock = DockStyle.Bottom;
            panel5.Location = new Point(0, 35);
            panel5.Name = "panel5";
            panel5.Size = new Size(800, 5);
            panel5.TabIndex = 3;
            // 
            // label6
            // 
            label6.BackColor = Color.Transparent;
            label6.Font = new Font("Courier New", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label6.Location = new Point(10, 0);
            label6.Name = "label6";
            label6.Size = new Size(154, 33);
            label6.TabIndex = 0;
            label6.Text = "Reset Password";
            label6.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // pictureBox2
            // 
            pictureBox2.Image = Properties.Resources._try;
            pictureBox2.Location = new Point(21, 62);
            pictureBox2.Name = "pictureBox2";
            pictureBox2.Size = new Size(300, 300);
            pictureBox2.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox2.TabIndex = 8;
            pictureBox2.TabStop = false;
            // 
            // BackBtn
            // 
            BackBtn.AllowAnimations = true;
            BackBtn.AllowMouseEffects = true;
            BackBtn.AllowToggling = false;
            BackBtn.AnimationSpeed = 200;
            BackBtn.AutoGenerateColors = false;
            BackBtn.AutoRoundBorders = false;
            BackBtn.AutoSizeLeftIcon = true;
            BackBtn.AutoSizeRightIcon = true;
            BackBtn.BackColor = Color.Transparent;
            BackBtn.BackColor1 = Color.FromArgb(51, 122, 183);
            BackBtn.BackgroundImage = (Image)resources.GetObject("BackBtn.BackgroundImage");
            BackBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BackBtn.ButtonText = "Back";
            BackBtn.ButtonTextMarginLeft = 0;
            BackBtn.ColorContrastOnClick = 45;
            BackBtn.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            BackBtn.CustomizableEdges = borderEdges3;
            BackBtn.DialogResult = DialogResult.None;
            BackBtn.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            BackBtn.DisabledFillColor = Color.Empty;
            BackBtn.DisabledForecolor = Color.Empty;
            BackBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            BackBtn.Font = new Font("Segoe UI", 9F);
            BackBtn.ForeColor = Color.White;
            BackBtn.IconLeft = null;
            BackBtn.IconLeftAlign = ContentAlignment.MiddleLeft;
            BackBtn.IconLeftCursor = Cursors.Default;
            BackBtn.IconLeftPadding = new Padding(11, 3, 3, 3);
            BackBtn.IconMarginLeft = 11;
            BackBtn.IconPadding = 10;
            BackBtn.IconRight = null;
            BackBtn.IconRightAlign = ContentAlignment.MiddleRight;
            BackBtn.IconRightCursor = Cursors.Default;
            BackBtn.IconRightPadding = new Padding(3, 3, 7, 3);
            BackBtn.IconSize = 25;
            BackBtn.IdleBorderColor = Color.Empty;
            BackBtn.IdleBorderRadius = 0;
            BackBtn.IdleBorderThickness = 0;
            BackBtn.IdleFillColor = Color.Empty;
            BackBtn.IdleIconLeftImage = null;
            BackBtn.IdleIconRightImage = null;
            BackBtn.IndicateFocus = false;
            BackBtn.Location = new Point(412, 387);
            BackBtn.Name = "BackBtn";
            BackBtn.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            BackBtn.OnDisabledState.BorderRadius = 1;
            BackBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BackBtn.OnDisabledState.BorderThickness = 1;
            BackBtn.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            BackBtn.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            BackBtn.OnDisabledState.IconLeftImage = null;
            BackBtn.OnDisabledState.IconRightImage = null;
            BackBtn.onHoverState.BorderColor = Color.FromArgb(192, 74, 62);
            BackBtn.onHoverState.BorderRadius = 1;
            BackBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BackBtn.onHoverState.BorderThickness = 1;
            BackBtn.onHoverState.FillColor = Color.FromArgb(192, 74, 62);
            BackBtn.onHoverState.ForeColor = Color.White;
            BackBtn.onHoverState.IconLeftImage = null;
            BackBtn.onHoverState.IconRightImage = null;
            BackBtn.OnIdleState.BorderColor = Color.FromArgb(192, 57, 43);
            BackBtn.OnIdleState.BorderRadius = 1;
            BackBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BackBtn.OnIdleState.BorderThickness = 1;
            BackBtn.OnIdleState.FillColor = Color.FromArgb(192, 57, 43);
            BackBtn.OnIdleState.ForeColor = Color.White;
            BackBtn.OnIdleState.IconLeftImage = null;
            BackBtn.OnIdleState.IconRightImage = null;
            BackBtn.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            BackBtn.OnPressedState.BorderRadius = 1;
            BackBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            BackBtn.OnPressedState.BorderThickness = 1;
            BackBtn.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            BackBtn.OnPressedState.ForeColor = Color.White;
            BackBtn.OnPressedState.IconLeftImage = null;
            BackBtn.OnPressedState.IconRightImage = null;
            BackBtn.Size = new Size(155, 39);
            BackBtn.TabIndex = 7;
            BackBtn.TextAlign = ContentAlignment.MiddleCenter;
            BackBtn.TextAlignment = HorizontalAlignment.Center;
            BackBtn.TextMarginLeft = 0;
            BackBtn.TextPadding = new Padding(0);
            BackBtn.UseDefaultRadiusAndThickness = true;
            BackBtn.Click += BackBtn_Click;
            // 
            // ValidateBtn
            // 
            ValidateBtn.AllowAnimations = true;
            ValidateBtn.AllowMouseEffects = true;
            ValidateBtn.AllowToggling = false;
            ValidateBtn.AnimationSpeed = 200;
            ValidateBtn.AutoGenerateColors = false;
            ValidateBtn.AutoRoundBorders = false;
            ValidateBtn.AutoSizeLeftIcon = true;
            ValidateBtn.AutoSizeRightIcon = true;
            ValidateBtn.BackColor = Color.Transparent;
            ValidateBtn.BackColor1 = Color.FromArgb(51, 122, 183);
            ValidateBtn.BackgroundImage = (Image)resources.GetObject("ValidateBtn.BackgroundImage");
            ValidateBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ValidateBtn.ButtonText = "Validate";
            ValidateBtn.ButtonTextMarginLeft = 0;
            ValidateBtn.ColorContrastOnClick = 45;
            ValidateBtn.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            ValidateBtn.CustomizableEdges = borderEdges4;
            ValidateBtn.DialogResult = DialogResult.None;
            ValidateBtn.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            ValidateBtn.DisabledFillColor = Color.Empty;
            ValidateBtn.DisabledForecolor = Color.Empty;
            ValidateBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            ValidateBtn.Font = new Font("Segoe UI", 9F);
            ValidateBtn.ForeColor = Color.White;
            ValidateBtn.IconLeft = null;
            ValidateBtn.IconLeftAlign = ContentAlignment.MiddleLeft;
            ValidateBtn.IconLeftCursor = Cursors.Default;
            ValidateBtn.IconLeftPadding = new Padding(11, 3, 3, 3);
            ValidateBtn.IconMarginLeft = 11;
            ValidateBtn.IconPadding = 10;
            ValidateBtn.IconRight = null;
            ValidateBtn.IconRightAlign = ContentAlignment.MiddleRight;
            ValidateBtn.IconRightCursor = Cursors.Default;
            ValidateBtn.IconRightPadding = new Padding(3, 3, 7, 3);
            ValidateBtn.IconSize = 25;
            ValidateBtn.IdleBorderColor = Color.Empty;
            ValidateBtn.IdleBorderRadius = 0;
            ValidateBtn.IdleBorderThickness = 0;
            ValidateBtn.IdleFillColor = Color.Empty;
            ValidateBtn.IdleIconLeftImage = null;
            ValidateBtn.IdleIconRightImage = null;
            ValidateBtn.IndicateFocus = false;
            ValidateBtn.Location = new Point(576, 387);
            ValidateBtn.Name = "ValidateBtn";
            ValidateBtn.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            ValidateBtn.OnDisabledState.BorderRadius = 1;
            ValidateBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ValidateBtn.OnDisabledState.BorderThickness = 1;
            ValidateBtn.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            ValidateBtn.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            ValidateBtn.OnDisabledState.IconLeftImage = null;
            ValidateBtn.OnDisabledState.IconRightImage = null;
            ValidateBtn.onHoverState.BorderColor = Color.FromArgb(192, 74, 62);
            ValidateBtn.onHoverState.BorderRadius = 1;
            ValidateBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ValidateBtn.onHoverState.BorderThickness = 1;
            ValidateBtn.onHoverState.FillColor = Color.FromArgb(192, 74, 62);
            ValidateBtn.onHoverState.ForeColor = Color.White;
            ValidateBtn.onHoverState.IconLeftImage = null;
            ValidateBtn.onHoverState.IconRightImage = null;
            ValidateBtn.OnIdleState.BorderColor = Color.FromArgb(192, 57, 43);
            ValidateBtn.OnIdleState.BorderRadius = 1;
            ValidateBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ValidateBtn.OnIdleState.BorderThickness = 1;
            ValidateBtn.OnIdleState.FillColor = Color.FromArgb(192, 57, 43);
            ValidateBtn.OnIdleState.ForeColor = Color.White;
            ValidateBtn.OnIdleState.IconLeftImage = null;
            ValidateBtn.OnIdleState.IconRightImage = null;
            ValidateBtn.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            ValidateBtn.OnPressedState.BorderRadius = 1;
            ValidateBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ValidateBtn.OnPressedState.BorderThickness = 1;
            ValidateBtn.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            ValidateBtn.OnPressedState.ForeColor = Color.White;
            ValidateBtn.OnPressedState.IconLeftImage = null;
            ValidateBtn.OnPressedState.IconRightImage = null;
            ValidateBtn.Size = new Size(155, 39);
            ValidateBtn.TabIndex = 6;
            ValidateBtn.TextAlign = ContentAlignment.MiddleCenter;
            ValidateBtn.TextAlignment = HorizontalAlignment.Center;
            ValidateBtn.TextMarginLeft = 0;
            ValidateBtn.TextPadding = new Padding(0);
            ValidateBtn.UseDefaultRadiusAndThickness = true;
            ValidateBtn.Click += ValidateBtn_Click;
            // 
            // answer3
            // 
            answer3.AcceptsReturn = false;
            answer3.AcceptsTab = false;
            answer3.AnimationSpeed = 200;
            answer3.AutoCompleteMode = AutoCompleteMode.None;
            answer3.AutoCompleteSource = AutoCompleteSource.None;
            answer3.AutoSizeHeight = true;
            answer3.BackColor = Color.Transparent;
            answer3.BackgroundImage = (Image)resources.GetObject("answer3.BackgroundImage");
            answer3.BorderColorActive = Color.DodgerBlue;
            answer3.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            answer3.BorderColorHover = Color.FromArgb(105, 181, 255);
            answer3.BorderColorIdle = Color.Silver;
            answer3.BorderRadius = 1;
            answer3.BorderThickness = 1;
            answer3.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            answer3.CharacterCasing = CharacterCasing.Normal;
            answer3.DefaultFont = new Font("Segoe UI", 9.25F);
            answer3.DefaultText = "";
            answer3.FillColor = Color.White;
            answer3.HideSelection = true;
            answer3.IconLeft = null;
            answer3.IconLeftCursor = Cursors.IBeam;
            answer3.IconPadding = 10;
            answer3.IconRight = null;
            answer3.IconRightCursor = Cursors.IBeam;
            answer3.Location = new Point(343, 321);
            answer3.MaxLength = 32767;
            answer3.MinimumSize = new Size(1, 1);
            answer3.Modified = false;
            answer3.Multiline = false;
            answer3.Name = "answer3";
            stateProperties5.BorderColor = Color.DodgerBlue;
            stateProperties5.FillColor = Color.Empty;
            stateProperties5.ForeColor = Color.Empty;
            stateProperties5.PlaceholderForeColor = Color.Empty;
            answer3.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties6.PlaceholderForeColor = Color.DarkGray;
            answer3.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties7.FillColor = Color.Empty;
            stateProperties7.ForeColor = Color.Empty;
            stateProperties7.PlaceholderForeColor = Color.Empty;
            answer3.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = Color.Silver;
            stateProperties8.FillColor = Color.White;
            stateProperties8.ForeColor = Color.Empty;
            stateProperties8.PlaceholderForeColor = Color.Empty;
            answer3.OnIdleState = stateProperties8;
            answer3.Padding = new Padding(3);
            answer3.PasswordChar = '\0';
            answer3.PlaceholderForeColor = Color.Silver;
            answer3.PlaceholderText = "Enter text";
            answer3.ReadOnly = false;
            answer3.ScrollBars = ScrollBars.None;
            answer3.SelectedText = "";
            answer3.SelectionLength = 0;
            answer3.SelectionStart = 0;
            answer3.ShortcutsEnabled = true;
            answer3.Size = new Size(388, 32);
            answer3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            answer3.TabIndex = 5;
            answer3.TextAlign = HorizontalAlignment.Left;
            answer3.TextMarginBottom = 0;
            answer3.TextMarginLeft = 3;
            answer3.TextMarginTop = 1;
            answer3.TextPlaceholder = "Enter text";
            answer3.UseSystemPasswordChar = false;
            answer3.WordWrap = true;
            // 
            // answer2
            // 
            answer2.AcceptsReturn = false;
            answer2.AcceptsTab = false;
            answer2.AnimationSpeed = 200;
            answer2.AutoCompleteMode = AutoCompleteMode.None;
            answer2.AutoCompleteSource = AutoCompleteSource.None;
            answer2.AutoSizeHeight = true;
            answer2.BackColor = Color.Transparent;
            answer2.BackgroundImage = (Image)resources.GetObject("answer2.BackgroundImage");
            answer2.BorderColorActive = Color.DodgerBlue;
            answer2.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            answer2.BorderColorHover = Color.FromArgb(105, 181, 255);
            answer2.BorderColorIdle = Color.Silver;
            answer2.BorderRadius = 1;
            answer2.BorderThickness = 1;
            answer2.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            answer2.CharacterCasing = CharacterCasing.Normal;
            answer2.DefaultFont = new Font("Segoe UI", 9.25F);
            answer2.DefaultText = "";
            answer2.FillColor = Color.White;
            answer2.HideSelection = true;
            answer2.IconLeft = null;
            answer2.IconLeftCursor = Cursors.IBeam;
            answer2.IconPadding = 10;
            answer2.IconRight = null;
            answer2.IconRightCursor = Cursors.IBeam;
            answer2.Location = new Point(343, 214);
            answer2.MaxLength = 32767;
            answer2.MinimumSize = new Size(1, 1);
            answer2.Modified = false;
            answer2.Multiline = false;
            answer2.Name = "answer2";
            stateProperties9.BorderColor = Color.DodgerBlue;
            stateProperties9.FillColor = Color.Empty;
            stateProperties9.ForeColor = Color.Empty;
            stateProperties9.PlaceholderForeColor = Color.Empty;
            answer2.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties10.PlaceholderForeColor = Color.DarkGray;
            answer2.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties11.FillColor = Color.Empty;
            stateProperties11.ForeColor = Color.Empty;
            stateProperties11.PlaceholderForeColor = Color.Empty;
            answer2.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = Color.Silver;
            stateProperties12.FillColor = Color.White;
            stateProperties12.ForeColor = Color.Empty;
            stateProperties12.PlaceholderForeColor = Color.Empty;
            answer2.OnIdleState = stateProperties12;
            answer2.Padding = new Padding(3);
            answer2.PasswordChar = '\0';
            answer2.PlaceholderForeColor = Color.Silver;
            answer2.PlaceholderText = "Enter text";
            answer2.ReadOnly = false;
            answer2.ScrollBars = ScrollBars.None;
            answer2.SelectedText = "";
            answer2.SelectionLength = 0;
            answer2.SelectionStart = 0;
            answer2.ShortcutsEnabled = true;
            answer2.Size = new Size(388, 32);
            answer2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            answer2.TabIndex = 4;
            answer2.TextAlign = HorizontalAlignment.Left;
            answer2.TextMarginBottom = 0;
            answer2.TextMarginLeft = 3;
            answer2.TextMarginTop = 1;
            answer2.TextPlaceholder = "Enter text";
            answer2.UseSystemPasswordChar = false;
            answer2.WordWrap = true;
            // 
            // answer1
            // 
            answer1.AcceptsReturn = false;
            answer1.AcceptsTab = false;
            answer1.AnimationSpeed = 200;
            answer1.AutoCompleteMode = AutoCompleteMode.None;
            answer1.AutoCompleteSource = AutoCompleteSource.None;
            answer1.AutoSizeHeight = true;
            answer1.BackColor = Color.Transparent;
            answer1.BackgroundImage = (Image)resources.GetObject("answer1.BackgroundImage");
            answer1.BorderColorActive = Color.DodgerBlue;
            answer1.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            answer1.BorderColorHover = Color.FromArgb(105, 181, 255);
            answer1.BorderColorIdle = Color.Silver;
            answer1.BorderRadius = 1;
            answer1.BorderThickness = 1;
            answer1.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            answer1.CharacterCasing = CharacterCasing.Normal;
            answer1.DefaultFont = new Font("Segoe UI", 9.25F);
            answer1.DefaultText = "";
            answer1.FillColor = Color.White;
            answer1.HideSelection = true;
            answer1.IconLeft = null;
            answer1.IconLeftCursor = Cursors.IBeam;
            answer1.IconPadding = 10;
            answer1.IconRight = null;
            answer1.IconRightCursor = Cursors.IBeam;
            answer1.Location = new Point(343, 115);
            answer1.MaxLength = 32767;
            answer1.MinimumSize = new Size(1, 1);
            answer1.Modified = false;
            answer1.Multiline = false;
            answer1.Name = "answer1";
            stateProperties13.BorderColor = Color.DodgerBlue;
            stateProperties13.FillColor = Color.Empty;
            stateProperties13.ForeColor = Color.Empty;
            stateProperties13.PlaceholderForeColor = Color.Empty;
            answer1.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties14.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties14.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties14.PlaceholderForeColor = Color.DarkGray;
            answer1.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties15.FillColor = Color.Empty;
            stateProperties15.ForeColor = Color.Empty;
            stateProperties15.PlaceholderForeColor = Color.Empty;
            answer1.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = Color.Silver;
            stateProperties16.FillColor = Color.White;
            stateProperties16.ForeColor = Color.Empty;
            stateProperties16.PlaceholderForeColor = Color.Empty;
            answer1.OnIdleState = stateProperties16;
            answer1.Padding = new Padding(3);
            answer1.PasswordChar = '\0';
            answer1.PlaceholderForeColor = Color.Silver;
            answer1.PlaceholderText = "Enter text";
            answer1.ReadOnly = false;
            answer1.ScrollBars = ScrollBars.None;
            answer1.SelectedText = "";
            answer1.SelectionLength = 0;
            answer1.SelectionStart = 0;
            answer1.ShortcutsEnabled = true;
            answer1.Size = new Size(388, 32);
            answer1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            answer1.TabIndex = 3;
            answer1.TextAlign = HorizontalAlignment.Left;
            answer1.TextMarginBottom = 0;
            answer1.TextMarginLeft = 3;
            answer1.TextMarginTop = 1;
            answer1.TextPlaceholder = "Enter text";
            answer1.UseSystemPasswordChar = false;
            answer1.WordWrap = true;
            // 
            // ResetPassPanel
            // 
            ResetPassPanel.Controls.Add(label5);
            ResetPassPanel.Controls.Add(label4);
            ResetPassPanel.Controls.Add(reenterpasswordtxt);
            ResetPassPanel.Controls.Add(newpasswordtxt);
            ResetPassPanel.Controls.Add(panel4);
            ResetPassPanel.Controls.Add(panel2);
            ResetPassPanel.Location = new Point(1215, 81);
            ResetPassPanel.Name = "ResetPassPanel";
            ResetPassPanel.Size = new Size(420, 268);
            ResetPassPanel.TabIndex = 7;
            // 
            // label5
            // 
            label5.BackColor = Color.Transparent;
            label5.Font = new Font("Courier New", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label5.Location = new Point(21, 134);
            label5.Name = "label5";
            label5.Size = new Size(190, 33);
            label5.TabIndex = 7;
            label5.Text = "Re-enter Password:";
            label5.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // label4
            // 
            label4.BackColor = Color.Transparent;
            label4.Font = new Font("Courier New", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label4.Location = new Point(21, 51);
            label4.Name = "label4";
            label4.Size = new Size(143, 33);
            label4.TabIndex = 6;
            label4.Text = "New Password:";
            label4.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // reenterpasswordtxt
            // 
            reenterpasswordtxt.AcceptsReturn = false;
            reenterpasswordtxt.AcceptsTab = false;
            reenterpasswordtxt.AnimationSpeed = 200;
            reenterpasswordtxt.AutoCompleteMode = AutoCompleteMode.None;
            reenterpasswordtxt.AutoCompleteSource = AutoCompleteSource.None;
            reenterpasswordtxt.AutoSizeHeight = true;
            reenterpasswordtxt.BackColor = Color.Transparent;
            reenterpasswordtxt.BackgroundImage = (Image)resources.GetObject("reenterpasswordtxt.BackgroundImage");
            reenterpasswordtxt.BorderColorActive = Color.DodgerBlue;
            reenterpasswordtxt.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            reenterpasswordtxt.BorderColorHover = Color.FromArgb(105, 181, 255);
            reenterpasswordtxt.BorderColorIdle = Color.Silver;
            reenterpasswordtxt.BorderRadius = 1;
            reenterpasswordtxt.BorderThickness = 1;
            reenterpasswordtxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            reenterpasswordtxt.CharacterCasing = CharacterCasing.Normal;
            reenterpasswordtxt.DefaultFont = new Font("Segoe UI", 9.25F);
            reenterpasswordtxt.DefaultText = "";
            reenterpasswordtxt.FillColor = Color.White;
            reenterpasswordtxt.HideSelection = true;
            reenterpasswordtxt.IconLeft = null;
            reenterpasswordtxt.IconLeftCursor = Cursors.IBeam;
            reenterpasswordtxt.IconPadding = 10;
            reenterpasswordtxt.IconRight = null;
            reenterpasswordtxt.IconRightCursor = Cursors.IBeam;
            reenterpasswordtxt.Location = new Point(21, 175);
            reenterpasswordtxt.MaxLength = 32767;
            reenterpasswordtxt.MinimumSize = new Size(1, 1);
            reenterpasswordtxt.Modified = false;
            reenterpasswordtxt.Multiline = false;
            reenterpasswordtxt.Name = "reenterpasswordtxt";
            stateProperties17.BorderColor = Color.DodgerBlue;
            stateProperties17.FillColor = Color.Empty;
            stateProperties17.ForeColor = Color.Empty;
            stateProperties17.PlaceholderForeColor = Color.Empty;
            reenterpasswordtxt.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties18.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties18.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties18.PlaceholderForeColor = Color.DarkGray;
            reenterpasswordtxt.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties19.FillColor = Color.Empty;
            stateProperties19.ForeColor = Color.Empty;
            stateProperties19.PlaceholderForeColor = Color.Empty;
            reenterpasswordtxt.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = Color.Silver;
            stateProperties20.FillColor = Color.White;
            stateProperties20.ForeColor = Color.Empty;
            stateProperties20.PlaceholderForeColor = Color.Empty;
            reenterpasswordtxt.OnIdleState = stateProperties20;
            reenterpasswordtxt.Padding = new Padding(3);
            reenterpasswordtxt.PasswordChar = '\0';
            reenterpasswordtxt.PlaceholderForeColor = Color.Silver;
            reenterpasswordtxt.PlaceholderText = "Enter text";
            reenterpasswordtxt.ReadOnly = false;
            reenterpasswordtxt.ScrollBars = ScrollBars.None;
            reenterpasswordtxt.SelectedText = "";
            reenterpasswordtxt.SelectionLength = 0;
            reenterpasswordtxt.SelectionStart = 0;
            reenterpasswordtxt.ShortcutsEnabled = true;
            reenterpasswordtxt.Size = new Size(374, 39);
            reenterpasswordtxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            reenterpasswordtxt.TabIndex = 5;
            reenterpasswordtxt.TextAlign = HorizontalAlignment.Left;
            reenterpasswordtxt.TextMarginBottom = 0;
            reenterpasswordtxt.TextMarginLeft = 3;
            reenterpasswordtxt.TextMarginTop = 1;
            reenterpasswordtxt.TextPlaceholder = "Enter text";
            reenterpasswordtxt.UseSystemPasswordChar = false;
            reenterpasswordtxt.WordWrap = true;
            // 
            // newpasswordtxt
            // 
            newpasswordtxt.AcceptsReturn = false;
            newpasswordtxt.AcceptsTab = false;
            newpasswordtxt.AnimationSpeed = 200;
            newpasswordtxt.AutoCompleteMode = AutoCompleteMode.None;
            newpasswordtxt.AutoCompleteSource = AutoCompleteSource.None;
            newpasswordtxt.AutoSizeHeight = true;
            newpasswordtxt.BackColor = Color.Transparent;
            newpasswordtxt.BackgroundImage = (Image)resources.GetObject("newpasswordtxt.BackgroundImage");
            newpasswordtxt.BorderColorActive = Color.DodgerBlue;
            newpasswordtxt.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            newpasswordtxt.BorderColorHover = Color.FromArgb(105, 181, 255);
            newpasswordtxt.BorderColorIdle = Color.Silver;
            newpasswordtxt.BorderRadius = 1;
            newpasswordtxt.BorderThickness = 1;
            newpasswordtxt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            newpasswordtxt.CharacterCasing = CharacterCasing.Normal;
            newpasswordtxt.DefaultFont = new Font("Segoe UI", 9.25F);
            newpasswordtxt.DefaultText = "";
            newpasswordtxt.FillColor = Color.White;
            newpasswordtxt.HideSelection = true;
            newpasswordtxt.IconLeft = null;
            newpasswordtxt.IconLeftCursor = Cursors.IBeam;
            newpasswordtxt.IconPadding = 10;
            newpasswordtxt.IconRight = null;
            newpasswordtxt.IconRightCursor = Cursors.IBeam;
            newpasswordtxt.Location = new Point(21, 89);
            newpasswordtxt.MaxLength = 32767;
            newpasswordtxt.MinimumSize = new Size(1, 1);
            newpasswordtxt.Modified = false;
            newpasswordtxt.Multiline = false;
            newpasswordtxt.Name = "newpasswordtxt";
            stateProperties21.BorderColor = Color.DodgerBlue;
            stateProperties21.FillColor = Color.Empty;
            stateProperties21.ForeColor = Color.Empty;
            stateProperties21.PlaceholderForeColor = Color.Empty;
            newpasswordtxt.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties22.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties22.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties22.PlaceholderForeColor = Color.DarkGray;
            newpasswordtxt.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties23.FillColor = Color.Empty;
            stateProperties23.ForeColor = Color.Empty;
            stateProperties23.PlaceholderForeColor = Color.Empty;
            newpasswordtxt.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = Color.Silver;
            stateProperties24.FillColor = Color.White;
            stateProperties24.ForeColor = Color.Empty;
            stateProperties24.PlaceholderForeColor = Color.Empty;
            newpasswordtxt.OnIdleState = stateProperties24;
            newpasswordtxt.Padding = new Padding(3);
            newpasswordtxt.PasswordChar = '\0';
            newpasswordtxt.PlaceholderForeColor = Color.Silver;
            newpasswordtxt.PlaceholderText = "Enter text";
            newpasswordtxt.ReadOnly = false;
            newpasswordtxt.ScrollBars = ScrollBars.None;
            newpasswordtxt.SelectedText = "";
            newpasswordtxt.SelectionLength = 0;
            newpasswordtxt.SelectionStart = 0;
            newpasswordtxt.ShortcutsEnabled = true;
            newpasswordtxt.Size = new Size(374, 39);
            newpasswordtxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            newpasswordtxt.TabIndex = 4;
            newpasswordtxt.TextAlign = HorizontalAlignment.Left;
            newpasswordtxt.TextMarginBottom = 0;
            newpasswordtxt.TextMarginLeft = 3;
            newpasswordtxt.TextMarginTop = 1;
            newpasswordtxt.TextPlaceholder = "Enter text";
            newpasswordtxt.UseSystemPasswordChar = false;
            newpasswordtxt.WordWrap = true;
            // 
            // panel4
            // 
            panel4.Controls.Add(CancelBtn2);
            panel4.Controls.Add(ResetPassBtn);
            panel4.Dock = DockStyle.Bottom;
            panel4.Location = new Point(0, 233);
            panel4.Name = "panel4";
            panel4.Padding = new Padding(10, 5, 10, 2);
            panel4.Size = new Size(420, 35);
            panel4.TabIndex = 3;
            // 
            // CancelBtn2
            // 
            CancelBtn2.AllowAnimations = true;
            CancelBtn2.AllowMouseEffects = true;
            CancelBtn2.AllowToggling = false;
            CancelBtn2.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            CancelBtn2.AnimationSpeed = 200;
            CancelBtn2.AutoGenerateColors = false;
            CancelBtn2.AutoRoundBorders = false;
            CancelBtn2.AutoSizeLeftIcon = true;
            CancelBtn2.AutoSizeRightIcon = true;
            CancelBtn2.BackColor = Color.Transparent;
            CancelBtn2.BackColor1 = Color.FromArgb(51, 122, 183);
            CancelBtn2.BackgroundImage = (Image)resources.GetObject("CancelBtn2.BackgroundImage");
            CancelBtn2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            CancelBtn2.ButtonText = "Cancel";
            CancelBtn2.ButtonTextMarginLeft = 0;
            CancelBtn2.ColorContrastOnClick = 45;
            CancelBtn2.ColorContrastOnHover = 45;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            CancelBtn2.CustomizableEdges = borderEdges5;
            CancelBtn2.DialogResult = DialogResult.None;
            CancelBtn2.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            CancelBtn2.DisabledFillColor = Color.Empty;
            CancelBtn2.DisabledForecolor = Color.Empty;
            CancelBtn2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            CancelBtn2.Font = new Font("Courier New", 9F, FontStyle.Bold);
            CancelBtn2.ForeColor = Color.Black;
            CancelBtn2.IconLeft = null;
            CancelBtn2.IconLeftAlign = ContentAlignment.MiddleLeft;
            CancelBtn2.IconLeftCursor = Cursors.Default;
            CancelBtn2.IconLeftPadding = new Padding(11, 3, 3, 3);
            CancelBtn2.IconMarginLeft = 11;
            CancelBtn2.IconPadding = 10;
            CancelBtn2.IconRight = null;
            CancelBtn2.IconRightAlign = ContentAlignment.MiddleRight;
            CancelBtn2.IconRightCursor = Cursors.Default;
            CancelBtn2.IconRightPadding = new Padding(3, 3, 7, 3);
            CancelBtn2.IconSize = 25;
            CancelBtn2.IdleBorderColor = Color.Empty;
            CancelBtn2.IdleBorderRadius = 0;
            CancelBtn2.IdleBorderThickness = 0;
            CancelBtn2.IdleFillColor = Color.Empty;
            CancelBtn2.IdleIconLeftImage = null;
            CancelBtn2.IdleIconRightImage = null;
            CancelBtn2.IndicateFocus = false;
            CancelBtn2.Location = new Point(237, 2);
            CancelBtn2.Name = "CancelBtn2";
            CancelBtn2.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            CancelBtn2.OnDisabledState.BorderRadius = 1;
            CancelBtn2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            CancelBtn2.OnDisabledState.BorderThickness = 1;
            CancelBtn2.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            CancelBtn2.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            CancelBtn2.OnDisabledState.IconLeftImage = null;
            CancelBtn2.OnDisabledState.IconRightImage = null;
            CancelBtn2.onHoverState.BorderColor = Color.Black;
            CancelBtn2.onHoverState.BorderRadius = 1;
            CancelBtn2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            CancelBtn2.onHoverState.BorderThickness = 1;
            CancelBtn2.onHoverState.FillColor = Color.FromArgb(205, 205, 207);
            CancelBtn2.onHoverState.ForeColor = Color.Black;
            CancelBtn2.onHoverState.IconLeftImage = null;
            CancelBtn2.onHoverState.IconRightImage = null;
            CancelBtn2.OnIdleState.BorderColor = Color.FromArgb(220, 220, 221);
            CancelBtn2.OnIdleState.BorderRadius = 1;
            CancelBtn2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            CancelBtn2.OnIdleState.BorderThickness = 1;
            CancelBtn2.OnIdleState.FillColor = Color.FromArgb(220, 220, 221);
            CancelBtn2.OnIdleState.ForeColor = Color.Black;
            CancelBtn2.OnIdleState.IconLeftImage = null;
            CancelBtn2.OnIdleState.IconRightImage = null;
            CancelBtn2.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            CancelBtn2.OnPressedState.BorderRadius = 1;
            CancelBtn2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            CancelBtn2.OnPressedState.BorderThickness = 1;
            CancelBtn2.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            CancelBtn2.OnPressedState.ForeColor = Color.White;
            CancelBtn2.OnPressedState.IconLeftImage = null;
            CancelBtn2.OnPressedState.IconRightImage = null;
            CancelBtn2.Size = new Size(65, 30);
            CancelBtn2.TabIndex = 3;
            CancelBtn2.TextAlign = ContentAlignment.MiddleCenter;
            CancelBtn2.TextAlignment = HorizontalAlignment.Center;
            CancelBtn2.TextMarginLeft = 0;
            CancelBtn2.TextPadding = new Padding(0);
            CancelBtn2.UseDefaultRadiusAndThickness = true;
            CancelBtn2.Click += CancelBtn2_Click;
            // 
            // ResetPassBtn
            // 
            ResetPassBtn.AllowAnimations = true;
            ResetPassBtn.AllowMouseEffects = true;
            ResetPassBtn.AllowToggling = false;
            ResetPassBtn.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            ResetPassBtn.AnimationSpeed = 200;
            ResetPassBtn.AutoGenerateColors = false;
            ResetPassBtn.AutoRoundBorders = false;
            ResetPassBtn.AutoSizeLeftIcon = true;
            ResetPassBtn.AutoSizeRightIcon = true;
            ResetPassBtn.BackColor = Color.Transparent;
            ResetPassBtn.BackColor1 = Color.FromArgb(51, 122, 183);
            ResetPassBtn.BackgroundImage = (Image)resources.GetObject("ResetPassBtn.BackgroundImage");
            ResetPassBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ResetPassBtn.ButtonText = "Reset Password";
            ResetPassBtn.ButtonTextMarginLeft = 0;
            ResetPassBtn.ColorContrastOnClick = 45;
            ResetPassBtn.ColorContrastOnHover = 45;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            ResetPassBtn.CustomizableEdges = borderEdges6;
            ResetPassBtn.DialogResult = DialogResult.None;
            ResetPassBtn.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            ResetPassBtn.DisabledFillColor = Color.Empty;
            ResetPassBtn.DisabledForecolor = Color.Empty;
            ResetPassBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            ResetPassBtn.Font = new Font("Courier New", 9F, FontStyle.Bold);
            ResetPassBtn.ForeColor = Color.White;
            ResetPassBtn.IconLeft = null;
            ResetPassBtn.IconLeftAlign = ContentAlignment.MiddleLeft;
            ResetPassBtn.IconLeftCursor = Cursors.Default;
            ResetPassBtn.IconLeftPadding = new Padding(11, 3, 3, 3);
            ResetPassBtn.IconMarginLeft = 11;
            ResetPassBtn.IconPadding = 10;
            ResetPassBtn.IconRight = null;
            ResetPassBtn.IconRightAlign = ContentAlignment.MiddleRight;
            ResetPassBtn.IconRightCursor = Cursors.Default;
            ResetPassBtn.IconRightPadding = new Padding(3, 3, 7, 3);
            ResetPassBtn.IconSize = 25;
            ResetPassBtn.IdleBorderColor = Color.Empty;
            ResetPassBtn.IdleBorderRadius = 0;
            ResetPassBtn.IdleBorderThickness = 0;
            ResetPassBtn.IdleFillColor = Color.Empty;
            ResetPassBtn.IdleIconLeftImage = null;
            ResetPassBtn.IdleIconRightImage = null;
            ResetPassBtn.IndicateFocus = false;
            ResetPassBtn.Location = new Point(308, 2);
            ResetPassBtn.Name = "ResetPassBtn";
            ResetPassBtn.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            ResetPassBtn.OnDisabledState.BorderRadius = 1;
            ResetPassBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ResetPassBtn.OnDisabledState.BorderThickness = 1;
            ResetPassBtn.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            ResetPassBtn.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            ResetPassBtn.OnDisabledState.IconLeftImage = null;
            ResetPassBtn.OnDisabledState.IconRightImage = null;
            ResetPassBtn.onHoverState.BorderColor = Color.FromArgb(50, 110, 5);
            ResetPassBtn.onHoverState.BorderRadius = 1;
            ResetPassBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ResetPassBtn.onHoverState.BorderThickness = 1;
            ResetPassBtn.onHoverState.FillColor = Color.FromArgb(50, 110, 5);
            ResetPassBtn.onHoverState.ForeColor = Color.White;
            ResetPassBtn.onHoverState.IconLeftImage = null;
            ResetPassBtn.onHoverState.IconRightImage = null;
            ResetPassBtn.OnIdleState.BorderColor = Color.FromArgb(78, 160, 21);
            ResetPassBtn.OnIdleState.BorderRadius = 1;
            ResetPassBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ResetPassBtn.OnIdleState.BorderThickness = 1;
            ResetPassBtn.OnIdleState.FillColor = Color.FromArgb(78, 160, 21);
            ResetPassBtn.OnIdleState.ForeColor = Color.White;
            ResetPassBtn.OnIdleState.IconLeftImage = null;
            ResetPassBtn.OnIdleState.IconRightImage = null;
            ResetPassBtn.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            ResetPassBtn.OnPressedState.BorderRadius = 1;
            ResetPassBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            ResetPassBtn.OnPressedState.BorderThickness = 1;
            ResetPassBtn.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            ResetPassBtn.OnPressedState.ForeColor = Color.White;
            ResetPassBtn.OnPressedState.IconLeftImage = null;
            ResetPassBtn.OnPressedState.IconRightImage = null;
            ResetPassBtn.Size = new Size(102, 30);
            ResetPassBtn.TabIndex = 0;
            ResetPassBtn.TextAlign = ContentAlignment.MiddleCenter;
            ResetPassBtn.TextAlignment = HorizontalAlignment.Center;
            ResetPassBtn.TextMarginLeft = 0;
            ResetPassBtn.TextPadding = new Padding(0);
            ResetPassBtn.UseDefaultRadiusAndThickness = true;
            ResetPassBtn.Click += ResetPassBtn_Click;
            // 
            // panel2
            // 
            panel2.BackColor = Color.White;
            panel2.Controls.Add(panel3);
            panel2.Controls.Add(label3);
            panel2.Dock = DockStyle.Top;
            panel2.Location = new Point(0, 0);
            panel2.Name = "panel2";
            panel2.Size = new Size(420, 40);
            panel2.TabIndex = 2;
            // 
            // panel3
            // 
            panel3.BackColor = Color.Maroon;
            panel3.Dock = DockStyle.Bottom;
            panel3.Location = new Point(0, 35);
            panel3.Name = "panel3";
            panel3.Size = new Size(420, 5);
            panel3.TabIndex = 3;
            // 
            // label3
            // 
            label3.BackColor = Color.Transparent;
            label3.Font = new Font("Courier New", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label3.Location = new Point(10, 0);
            label3.Name = "label3";
            label3.Size = new Size(154, 33);
            label3.TabIndex = 0;
            label3.Text = "Reset Password";
            label3.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // panel6
            // 
            panel6.BackColor = Color.White;
            panel6.Controls.Add(panel7);
            panel6.Controls.Add(label7);
            panel6.Dock = DockStyle.Top;
            panel6.Location = new Point(0, 0);
            panel6.Name = "panel6";
            panel6.Size = new Size(800, 40);
            panel6.TabIndex = 10;
            // 
            // panel7
            // 
            panel7.BackColor = Color.Maroon;
            panel7.Dock = DockStyle.Bottom;
            panel7.Location = new Point(0, 35);
            panel7.Name = "panel7";
            panel7.Size = new Size(800, 5);
            panel7.TabIndex = 3;
            // 
            // label7
            // 
            label7.BackColor = Color.Transparent;
            label7.Font = new Font("Courier New", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label7.Location = new Point(10, 0);
            label7.Name = "label7";
            label7.Size = new Size(181, 33);
            label7.TabIndex = 0;
            label7.Text = "Forgot Password";
            label7.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // ForgotPasswordModal
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            ClientSize = new Size(800, 450);
            Controls.Add(ResetPassPanel);
            Controls.Add(QuestionPanel);
            Controls.Add(panel6);
            Controls.Add(ForgotUsernameTxt);
            Controls.Add(label2);
            Controls.Add(btnNext);
            Controls.Add(label1);
            Controls.Add(btncancel);
            Controls.Add(pictureBox1);
            FormBorderStyle = FormBorderStyle.None;
            Name = "ForgotPasswordModal";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "ForgotPasswordModal";
            Load += ForgotPasswordModal_Load;
            ((System.ComponentModel.ISupportInitialize)pictureBox1).EndInit();
            QuestionPanel.ResumeLayout(false);
            panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)pictureBox2).EndInit();
            ResetPassPanel.ResumeLayout(false);
            panel4.ResumeLayout(false);
            panel2.ResumeLayout(false);
            panel6.ResumeLayout(false);
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btncancel;
        private Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnNext;
        private Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox ForgotUsernameTxt;
        private Panel QuestionPanel;
        private PictureBox pictureBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BackBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ValidateBtn;
        private Bunifu.UI.WinForms.BunifuTextBox answer3;
        private Bunifu.UI.WinForms.BunifuTextBox answer2;
        private Bunifu.UI.WinForms.BunifuTextBox answer1;
        private Panel ResetPassPanel;
        private Panel panel2;
        private Panel panel3;
        private Label label3;
        private Label label5;
        private Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox reenterpasswordtxt;
        private Bunifu.UI.WinForms.BunifuTextBox newpasswordtxt;
        private Panel panel4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton CancelBtn2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ResetPassBtn;
        private Panel panel1;
        private Panel panel5;
        private Label label6;
        private Panel panel6;
        private Panel panel7;
        private Label label7;
        private Label question3;
        private Label question2;
        private Label question1;
    }
}