namespace DazaBestApplication
{
    partial class MainPage
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainPage));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            TopNav = new Panel();
            bunifuIconButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            FormControlBox = new Bunifu.UI.WinForms.BunifuFormControlBox();
            CompanyName = new Bunifu.UI.WinForms.BunifuLabel();
            SideNav = new Panel();
            bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            NavButton_Reports = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            NavButton_Products = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            NavButton_Item = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            NavButton_Home = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            MainContainer = new Panel();
            FormDragFeature = new Bunifu.UI.WinForms.BunifuFormDrag();
            LogOut_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            TopNav.SuspendLayout();
            SideNav.SuspendLayout();
            SuspendLayout();
            // 
            // TopNav
            // 
            TopNav.BackColor = Color.FromArgb(33, 33, 33);
            TopNav.Controls.Add(bunifuIconButton1);
            TopNav.Controls.Add(FormControlBox);
            TopNav.Controls.Add(CompanyName);
            TopNav.Dock = DockStyle.Top;
            TopNav.Location = new Point(0, 0);
            TopNav.Name = "TopNav";
            TopNav.Padding = new Padding(10, 0, 0, 0);
            TopNav.Size = new Size(1100, 30);
            TopNav.TabIndex = 2;
            // 
            // bunifuIconButton1
            // 
            bunifuIconButton1.AllowAnimations = true;
            bunifuIconButton1.AllowBorderColorChanges = true;
            bunifuIconButton1.AllowMouseEffects = true;
            bunifuIconButton1.AnimationSpeed = 200;
            bunifuIconButton1.BackColor = Color.Transparent;
            bunifuIconButton1.BackgroundColor = Color.Transparent;
            bunifuIconButton1.BorderColor = Color.Transparent;
            bunifuIconButton1.BorderRadius = 1;
            bunifuIconButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            bunifuIconButton1.BorderThickness = 1;
            bunifuIconButton1.ColorContrastOnClick = 30;
            bunifuIconButton1.ColorContrastOnHover = 30;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            bunifuIconButton1.CustomizableEdges = borderEdges8;
            bunifuIconButton1.DialogResult = DialogResult.None;
            bunifuIconButton1.Dock = DockStyle.Left;
            bunifuIconButton1.Image = Properties.Resources._477622848_2102876326812470_7082635694266922336_n;
            bunifuIconButton1.ImageMargin = new Padding(0);
            bunifuIconButton1.Location = new Point(10, 0);
            bunifuIconButton1.Name = "bunifuIconButton1";
            bunifuIconButton1.RoundBorders = false;
            bunifuIconButton1.ShowBorders = true;
            bunifuIconButton1.Size = new Size(30, 30);
            bunifuIconButton1.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Flat;
            bunifuIconButton1.TabIndex = 1;
            // 
            // FormControlBox
            // 
            FormControlBox.BackColor = Color.White;
            FormControlBox.BunifuFormDrag = null;
            FormControlBox.CloseBoxOptions.BackColor = Color.Transparent;
            FormControlBox.CloseBoxOptions.BorderRadius = 0;
            FormControlBox.CloseBoxOptions.Enabled = true;
            FormControlBox.CloseBoxOptions.EnableDefaultAction = true;
            FormControlBox.CloseBoxOptions.HoverColor = Color.FromArgb(232, 17, 35);
            FormControlBox.CloseBoxOptions.Icon = (Image)resources.GetObject("FormControlBox.CloseBoxOptions.Icon");
            FormControlBox.CloseBoxOptions.IconAlt = null;
            FormControlBox.CloseBoxOptions.IconColor = Color.Black;
            FormControlBox.CloseBoxOptions.IconHoverColor = Color.White;
            FormControlBox.CloseBoxOptions.IconPressedColor = Color.White;
            FormControlBox.CloseBoxOptions.IconSize = new Size(18, 18);
            FormControlBox.CloseBoxOptions.PressedColor = Color.FromArgb(232, 17, 35);
            FormControlBox.Dock = DockStyle.Right;
            FormControlBox.ForeColor = Color.White;
            FormControlBox.HelpBox = false;
            FormControlBox.HelpBoxOptions.BackColor = Color.Transparent;
            FormControlBox.HelpBoxOptions.BorderRadius = 0;
            FormControlBox.HelpBoxOptions.Enabled = true;
            FormControlBox.HelpBoxOptions.EnableDefaultAction = true;
            FormControlBox.HelpBoxOptions.HoverColor = Color.LightGray;
            FormControlBox.HelpBoxOptions.Icon = (Image)resources.GetObject("FormControlBox.HelpBoxOptions.Icon");
            FormControlBox.HelpBoxOptions.IconAlt = null;
            FormControlBox.HelpBoxOptions.IconColor = Color.Black;
            FormControlBox.HelpBoxOptions.IconHoverColor = Color.Black;
            FormControlBox.HelpBoxOptions.IconPressedColor = Color.Black;
            FormControlBox.HelpBoxOptions.IconSize = new Size(22, 22);
            FormControlBox.HelpBoxOptions.PressedColor = Color.Silver;
            FormControlBox.Location = new Point(947, 0);
            FormControlBox.MaximizeBox = true;
            FormControlBox.MaximizeBoxOptions.BackColor = Color.Transparent;
            FormControlBox.MaximizeBoxOptions.BorderRadius = 0;
            FormControlBox.MaximizeBoxOptions.Enabled = true;
            FormControlBox.MaximizeBoxOptions.EnableDefaultAction = true;
            FormControlBox.MaximizeBoxOptions.HoverColor = Color.LightGray;
            FormControlBox.MaximizeBoxOptions.Icon = (Image)resources.GetObject("FormControlBox.MaximizeBoxOptions.Icon");
            FormControlBox.MaximizeBoxOptions.IconAlt = (Image)resources.GetObject("FormControlBox.MaximizeBoxOptions.IconAlt");
            FormControlBox.MaximizeBoxOptions.IconColor = Color.Black;
            FormControlBox.MaximizeBoxOptions.IconHoverColor = Color.Black;
            FormControlBox.MaximizeBoxOptions.IconPressedColor = Color.Black;
            FormControlBox.MaximizeBoxOptions.IconSize = new Size(16, 16);
            FormControlBox.MaximizeBoxOptions.PressedColor = Color.Silver;
            FormControlBox.MinimizeBox = true;
            FormControlBox.MinimizeBoxOptions.BackColor = Color.Transparent;
            FormControlBox.MinimizeBoxOptions.BorderRadius = 0;
            FormControlBox.MinimizeBoxOptions.Enabled = true;
            FormControlBox.MinimizeBoxOptions.EnableDefaultAction = true;
            FormControlBox.MinimizeBoxOptions.HoverColor = Color.LightGray;
            FormControlBox.MinimizeBoxOptions.Icon = (Image)resources.GetObject("FormControlBox.MinimizeBoxOptions.Icon");
            FormControlBox.MinimizeBoxOptions.IconAlt = null;
            FormControlBox.MinimizeBoxOptions.IconColor = Color.Black;
            FormControlBox.MinimizeBoxOptions.IconHoverColor = Color.Black;
            FormControlBox.MinimizeBoxOptions.IconPressedColor = Color.Black;
            FormControlBox.MinimizeBoxOptions.IconSize = new Size(14, 14);
            FormControlBox.MinimizeBoxOptions.PressedColor = Color.Silver;
            FormControlBox.Name = "FormControlBox";
            FormControlBox.ShowDesignBorders = false;
            FormControlBox.Size = new Size(153, 30);
            FormControlBox.TabIndex = 5;
            // 
            // CompanyName
            // 
            CompanyName.AllowParentOverrides = false;
            CompanyName.AutoEllipsis = false;
            CompanyName.AutoSize = false;
            CompanyName.CursorType = Cursors.Default;
            CompanyName.Font = new Font("Times New Roman", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            CompanyName.ForeColor = Color.Coral;
            CompanyName.Location = new Point(52, 0);
            CompanyName.Name = "CompanyName";
            CompanyName.RightToLeft = RightToLeft.No;
            CompanyName.Size = new Size(181, 30);
            CompanyName.TabIndex = 1;
            CompanyName.Text = "Daza's Best";
            CompanyName.TextAlignment = ContentAlignment.MiddleLeft;
            CompanyName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // SideNav
            // 
            SideNav.BackColor = Color.FromArgb(230, 126, 34);
            SideNav.Controls.Add(LogOut_btn);
            SideNav.Controls.Add(bunifuButton21);
            SideNav.Controls.Add(NavButton_Reports);
            SideNav.Controls.Add(NavButton_Products);
            SideNav.Controls.Add(NavButton_Item);
            SideNav.Controls.Add(NavButton_Home);
            SideNav.Dock = DockStyle.Left;
            SideNav.Location = new Point(0, 30);
            SideNav.Name = "SideNav";
            SideNav.Padding = new Padding(0, 20, 0, 10);
            SideNav.Size = new Size(200, 670);
            SideNav.TabIndex = 3;
            // 
            // bunifuButton21
            // 
            bunifuButton21.AllowAnimations = true;
            bunifuButton21.AllowMouseEffects = true;
            bunifuButton21.AllowToggling = false;
            bunifuButton21.AnimationSpeed = 200;
            bunifuButton21.AutoGenerateColors = false;
            bunifuButton21.AutoRoundBorders = false;
            bunifuButton21.AutoSizeLeftIcon = true;
            bunifuButton21.AutoSizeRightIcon = true;
            bunifuButton21.BackColor = Color.Transparent;
            bunifuButton21.BackColor1 = Color.Transparent;
            bunifuButton21.BackgroundImage = (Image)resources.GetObject("bunifuButton21.BackgroundImage");
            bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.ButtonText = "Settings";
            bunifuButton21.ButtonTextMarginLeft = 0;
            bunifuButton21.ColorContrastOnClick = 45;
            bunifuButton21.ColorContrastOnHover = 45;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            bunifuButton21.CustomizableEdges = borderEdges9;
            bunifuButton21.DialogResult = DialogResult.None;
            bunifuButton21.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton21.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton21.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton21.Dock = DockStyle.Top;
            bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton21.Font = new Font("Times New Roman", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuButton21.ForeColor = Color.White;
            bunifuButton21.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton21.IconLeftCursor = Cursors.Default;
            bunifuButton21.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton21.IconMarginLeft = 11;
            bunifuButton21.IconPadding = 10;
            bunifuButton21.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton21.IconRightCursor = Cursors.Default;
            bunifuButton21.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton21.IconSize = 25;
            bunifuButton21.IdleBorderColor = Color.Transparent;
            bunifuButton21.IdleBorderRadius = 1;
            bunifuButton21.IdleBorderThickness = 1;
            bunifuButton21.IdleFillColor = Color.Transparent;
            bunifuButton21.IdleIconLeftImage = null;
            bunifuButton21.IdleIconRightImage = null;
            bunifuButton21.IndicateFocus = false;
            bunifuButton21.Location = new Point(0, 180);
            bunifuButton21.Name = "bunifuButton21";
            bunifuButton21.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton21.OnDisabledState.BorderRadius = 1;
            bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.OnDisabledState.BorderThickness = 1;
            bunifuButton21.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton21.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton21.OnDisabledState.IconLeftImage = null;
            bunifuButton21.OnDisabledState.IconRightImage = null;
            bunifuButton21.onHoverState.BorderColor = Color.Transparent;
            bunifuButton21.onHoverState.BorderRadius = 1;
            bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.onHoverState.BorderThickness = 1;
            bunifuButton21.onHoverState.FillColor = Color.FromArgb(251, 205, 119);
            bunifuButton21.onHoverState.ForeColor = Color.Black;
            bunifuButton21.onHoverState.IconLeftImage = null;
            bunifuButton21.onHoverState.IconRightImage = null;
            bunifuButton21.OnIdleState.BorderColor = Color.Transparent;
            bunifuButton21.OnIdleState.BorderRadius = 1;
            bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.OnIdleState.BorderThickness = 1;
            bunifuButton21.OnIdleState.FillColor = Color.Transparent;
            bunifuButton21.OnIdleState.ForeColor = Color.White;
            bunifuButton21.OnIdleState.IconLeftImage = null;
            bunifuButton21.OnIdleState.IconRightImage = null;
            bunifuButton21.OnPressedState.BorderColor = Color.FromArgb(198, 40, 40);
            bunifuButton21.OnPressedState.BorderRadius = 1;
            bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.OnPressedState.BorderThickness = 1;
            bunifuButton21.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            bunifuButton21.OnPressedState.ForeColor = Color.White;
            bunifuButton21.OnPressedState.IconLeftImage = null;
            bunifuButton21.OnPressedState.IconRightImage = null;
            bunifuButton21.Size = new Size(200, 40);
            bunifuButton21.TabIndex = 4;
            bunifuButton21.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton21.TextAlignment = HorizontalAlignment.Center;
            bunifuButton21.TextMarginLeft = 0;
            bunifuButton21.TextPadding = new Padding(0);
            bunifuButton21.UseDefaultRadiusAndThickness = true;
            // 
            // NavButton_Reports
            // 
            NavButton_Reports.AllowAnimations = true;
            NavButton_Reports.AllowMouseEffects = true;
            NavButton_Reports.AllowToggling = false;
            NavButton_Reports.AnimationSpeed = 200;
            NavButton_Reports.AutoGenerateColors = false;
            NavButton_Reports.AutoRoundBorders = false;
            NavButton_Reports.AutoSizeLeftIcon = true;
            NavButton_Reports.AutoSizeRightIcon = true;
            NavButton_Reports.BackColor = Color.Transparent;
            NavButton_Reports.BackColor1 = Color.Transparent;
            NavButton_Reports.BackgroundImage = (Image)resources.GetObject("NavButton_Reports.BackgroundImage");
            NavButton_Reports.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Reports.ButtonText = "Reports";
            NavButton_Reports.ButtonTextMarginLeft = 0;
            NavButton_Reports.ColorContrastOnClick = 45;
            NavButton_Reports.ColorContrastOnHover = 45;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            NavButton_Reports.CustomizableEdges = borderEdges10;
            NavButton_Reports.DialogResult = DialogResult.None;
            NavButton_Reports.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Reports.DisabledFillColor = Color.FromArgb(204, 204, 204);
            NavButton_Reports.DisabledForecolor = Color.FromArgb(168, 160, 168);
            NavButton_Reports.Dock = DockStyle.Top;
            NavButton_Reports.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            NavButton_Reports.Font = new Font("Times New Roman", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            NavButton_Reports.ForeColor = Color.White;
            NavButton_Reports.IconLeftAlign = ContentAlignment.MiddleLeft;
            NavButton_Reports.IconLeftCursor = Cursors.Default;
            NavButton_Reports.IconLeftPadding = new Padding(11, 3, 3, 3);
            NavButton_Reports.IconMarginLeft = 11;
            NavButton_Reports.IconPadding = 10;
            NavButton_Reports.IconRightAlign = ContentAlignment.MiddleRight;
            NavButton_Reports.IconRightCursor = Cursors.Default;
            NavButton_Reports.IconRightPadding = new Padding(3, 3, 7, 3);
            NavButton_Reports.IconSize = 25;
            NavButton_Reports.IdleBorderColor = Color.Transparent;
            NavButton_Reports.IdleBorderRadius = 1;
            NavButton_Reports.IdleBorderThickness = 1;
            NavButton_Reports.IdleFillColor = Color.Transparent;
            NavButton_Reports.IdleIconLeftImage = null;
            NavButton_Reports.IdleIconRightImage = null;
            NavButton_Reports.IndicateFocus = false;
            NavButton_Reports.Location = new Point(0, 140);
            NavButton_Reports.Name = "NavButton_Reports";
            NavButton_Reports.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Reports.OnDisabledState.BorderRadius = 1;
            NavButton_Reports.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Reports.OnDisabledState.BorderThickness = 1;
            NavButton_Reports.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            NavButton_Reports.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            NavButton_Reports.OnDisabledState.IconLeftImage = null;
            NavButton_Reports.OnDisabledState.IconRightImage = null;
            NavButton_Reports.onHoverState.BorderColor = Color.Transparent;
            NavButton_Reports.onHoverState.BorderRadius = 1;
            NavButton_Reports.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Reports.onHoverState.BorderThickness = 1;
            NavButton_Reports.onHoverState.FillColor = Color.FromArgb(251, 205, 119);
            NavButton_Reports.onHoverState.ForeColor = Color.Black;
            NavButton_Reports.onHoverState.IconLeftImage = null;
            NavButton_Reports.onHoverState.IconRightImage = null;
            NavButton_Reports.OnIdleState.BorderColor = Color.Transparent;
            NavButton_Reports.OnIdleState.BorderRadius = 1;
            NavButton_Reports.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Reports.OnIdleState.BorderThickness = 1;
            NavButton_Reports.OnIdleState.FillColor = Color.Transparent;
            NavButton_Reports.OnIdleState.ForeColor = Color.White;
            NavButton_Reports.OnIdleState.IconLeftImage = null;
            NavButton_Reports.OnIdleState.IconRightImage = null;
            NavButton_Reports.OnPressedState.BorderColor = Color.FromArgb(198, 40, 40);
            NavButton_Reports.OnPressedState.BorderRadius = 1;
            NavButton_Reports.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Reports.OnPressedState.BorderThickness = 1;
            NavButton_Reports.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            NavButton_Reports.OnPressedState.ForeColor = Color.White;
            NavButton_Reports.OnPressedState.IconLeftImage = null;
            NavButton_Reports.OnPressedState.IconRightImage = null;
            NavButton_Reports.Size = new Size(200, 40);
            NavButton_Reports.TabIndex = 3;
            NavButton_Reports.TextAlign = ContentAlignment.MiddleCenter;
            NavButton_Reports.TextAlignment = HorizontalAlignment.Center;
            NavButton_Reports.TextMarginLeft = 0;
            NavButton_Reports.TextPadding = new Padding(0);
            NavButton_Reports.UseDefaultRadiusAndThickness = true;
            // 
            // NavButton_Products
            // 
            NavButton_Products.AllowAnimations = true;
            NavButton_Products.AllowMouseEffects = true;
            NavButton_Products.AllowToggling = false;
            NavButton_Products.AnimationSpeed = 200;
            NavButton_Products.AutoGenerateColors = false;
            NavButton_Products.AutoRoundBorders = false;
            NavButton_Products.AutoSizeLeftIcon = true;
            NavButton_Products.AutoSizeRightIcon = true;
            NavButton_Products.BackColor = Color.Transparent;
            NavButton_Products.BackColor1 = Color.Transparent;
            NavButton_Products.BackgroundImage = (Image)resources.GetObject("NavButton_Products.BackgroundImage");
            NavButton_Products.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Products.ButtonText = "Products";
            NavButton_Products.ButtonTextMarginLeft = 0;
            NavButton_Products.ColorContrastOnClick = 45;
            NavButton_Products.ColorContrastOnHover = 45;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            NavButton_Products.CustomizableEdges = borderEdges11;
            NavButton_Products.DialogResult = DialogResult.None;
            NavButton_Products.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Products.DisabledFillColor = Color.FromArgb(204, 204, 204);
            NavButton_Products.DisabledForecolor = Color.FromArgb(168, 160, 168);
            NavButton_Products.Dock = DockStyle.Top;
            NavButton_Products.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            NavButton_Products.Font = new Font("Times New Roman", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            NavButton_Products.ForeColor = Color.White;
            NavButton_Products.IconLeftAlign = ContentAlignment.MiddleLeft;
            NavButton_Products.IconLeftCursor = Cursors.Default;
            NavButton_Products.IconLeftPadding = new Padding(11, 3, 3, 3);
            NavButton_Products.IconMarginLeft = 11;
            NavButton_Products.IconPadding = 10;
            NavButton_Products.IconRightAlign = ContentAlignment.MiddleRight;
            NavButton_Products.IconRightCursor = Cursors.Default;
            NavButton_Products.IconRightPadding = new Padding(3, 3, 7, 3);
            NavButton_Products.IconSize = 25;
            NavButton_Products.IdleBorderColor = Color.Transparent;
            NavButton_Products.IdleBorderRadius = 1;
            NavButton_Products.IdleBorderThickness = 1;
            NavButton_Products.IdleFillColor = Color.Transparent;
            NavButton_Products.IdleIconLeftImage = null;
            NavButton_Products.IdleIconRightImage = null;
            NavButton_Products.IndicateFocus = false;
            NavButton_Products.Location = new Point(0, 100);
            NavButton_Products.Name = "NavButton_Products";
            NavButton_Products.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Products.OnDisabledState.BorderRadius = 1;
            NavButton_Products.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Products.OnDisabledState.BorderThickness = 1;
            NavButton_Products.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            NavButton_Products.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            NavButton_Products.OnDisabledState.IconLeftImage = null;
            NavButton_Products.OnDisabledState.IconRightImage = null;
            NavButton_Products.onHoverState.BorderColor = Color.Transparent;
            NavButton_Products.onHoverState.BorderRadius = 1;
            NavButton_Products.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Products.onHoverState.BorderThickness = 1;
            NavButton_Products.onHoverState.FillColor = Color.FromArgb(251, 205, 119);
            NavButton_Products.onHoverState.ForeColor = Color.Black;
            NavButton_Products.onHoverState.IconLeftImage = null;
            NavButton_Products.onHoverState.IconRightImage = null;
            NavButton_Products.OnIdleState.BorderColor = Color.Transparent;
            NavButton_Products.OnIdleState.BorderRadius = 1;
            NavButton_Products.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Products.OnIdleState.BorderThickness = 1;
            NavButton_Products.OnIdleState.FillColor = Color.Transparent;
            NavButton_Products.OnIdleState.ForeColor = Color.White;
            NavButton_Products.OnIdleState.IconLeftImage = null;
            NavButton_Products.OnIdleState.IconRightImage = null;
            NavButton_Products.OnPressedState.BorderColor = Color.FromArgb(198, 40, 40);
            NavButton_Products.OnPressedState.BorderRadius = 1;
            NavButton_Products.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Products.OnPressedState.BorderThickness = 1;
            NavButton_Products.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            NavButton_Products.OnPressedState.ForeColor = Color.White;
            NavButton_Products.OnPressedState.IconLeftImage = null;
            NavButton_Products.OnPressedState.IconRightImage = null;
            NavButton_Products.Size = new Size(200, 40);
            NavButton_Products.TabIndex = 2;
            NavButton_Products.TextAlign = ContentAlignment.MiddleCenter;
            NavButton_Products.TextAlignment = HorizontalAlignment.Center;
            NavButton_Products.TextMarginLeft = 0;
            NavButton_Products.TextPadding = new Padding(0);
            NavButton_Products.UseDefaultRadiusAndThickness = true;
            // 
            // NavButton_Item
            // 
            NavButton_Item.AllowAnimations = true;
            NavButton_Item.AllowMouseEffects = true;
            NavButton_Item.AllowToggling = false;
            NavButton_Item.AnimationSpeed = 200;
            NavButton_Item.AutoGenerateColors = false;
            NavButton_Item.AutoRoundBorders = false;
            NavButton_Item.AutoSizeLeftIcon = true;
            NavButton_Item.AutoSizeRightIcon = true;
            NavButton_Item.BackColor = Color.Transparent;
            NavButton_Item.BackColor1 = Color.Transparent;
            NavButton_Item.BackgroundImage = (Image)resources.GetObject("NavButton_Item.BackgroundImage");
            NavButton_Item.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Item.ButtonText = "Items";
            NavButton_Item.ButtonTextMarginLeft = 0;
            NavButton_Item.ColorContrastOnClick = 45;
            NavButton_Item.ColorContrastOnHover = 45;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            NavButton_Item.CustomizableEdges = borderEdges12;
            NavButton_Item.DialogResult = DialogResult.None;
            NavButton_Item.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Item.DisabledFillColor = Color.FromArgb(204, 204, 204);
            NavButton_Item.DisabledForecolor = Color.FromArgb(168, 160, 168);
            NavButton_Item.Dock = DockStyle.Top;
            NavButton_Item.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            NavButton_Item.Font = new Font("Times New Roman", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            NavButton_Item.ForeColor = Color.White;
            NavButton_Item.IconLeftAlign = ContentAlignment.MiddleLeft;
            NavButton_Item.IconLeftCursor = Cursors.Default;
            NavButton_Item.IconLeftPadding = new Padding(11, 3, 3, 3);
            NavButton_Item.IconMarginLeft = 11;
            NavButton_Item.IconPadding = 10;
            NavButton_Item.IconRightAlign = ContentAlignment.MiddleRight;
            NavButton_Item.IconRightCursor = Cursors.Default;
            NavButton_Item.IconRightPadding = new Padding(3, 3, 7, 3);
            NavButton_Item.IconSize = 25;
            NavButton_Item.IdleBorderColor = Color.Transparent;
            NavButton_Item.IdleBorderRadius = 1;
            NavButton_Item.IdleBorderThickness = 1;
            NavButton_Item.IdleFillColor = Color.Transparent;
            NavButton_Item.IdleIconLeftImage = null;
            NavButton_Item.IdleIconRightImage = null;
            NavButton_Item.IndicateFocus = false;
            NavButton_Item.Location = new Point(0, 60);
            NavButton_Item.Name = "NavButton_Item";
            NavButton_Item.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Item.OnDisabledState.BorderRadius = 1;
            NavButton_Item.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Item.OnDisabledState.BorderThickness = 1;
            NavButton_Item.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            NavButton_Item.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            NavButton_Item.OnDisabledState.IconLeftImage = null;
            NavButton_Item.OnDisabledState.IconRightImage = null;
            NavButton_Item.onHoverState.BorderColor = Color.Transparent;
            NavButton_Item.onHoverState.BorderRadius = 1;
            NavButton_Item.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Item.onHoverState.BorderThickness = 1;
            NavButton_Item.onHoverState.FillColor = Color.FromArgb(251, 205, 119);
            NavButton_Item.onHoverState.ForeColor = Color.Black;
            NavButton_Item.onHoverState.IconLeftImage = null;
            NavButton_Item.onHoverState.IconRightImage = null;
            NavButton_Item.OnIdleState.BorderColor = Color.Transparent;
            NavButton_Item.OnIdleState.BorderRadius = 1;
            NavButton_Item.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Item.OnIdleState.BorderThickness = 1;
            NavButton_Item.OnIdleState.FillColor = Color.Transparent;
            NavButton_Item.OnIdleState.ForeColor = Color.White;
            NavButton_Item.OnIdleState.IconLeftImage = null;
            NavButton_Item.OnIdleState.IconRightImage = null;
            NavButton_Item.OnPressedState.BorderColor = Color.FromArgb(198, 40, 40);
            NavButton_Item.OnPressedState.BorderRadius = 1;
            NavButton_Item.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Item.OnPressedState.BorderThickness = 1;
            NavButton_Item.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            NavButton_Item.OnPressedState.ForeColor = Color.White;
            NavButton_Item.OnPressedState.IconLeftImage = null;
            NavButton_Item.OnPressedState.IconRightImage = null;
            NavButton_Item.Size = new Size(200, 40);
            NavButton_Item.TabIndex = 1;
            NavButton_Item.TextAlign = ContentAlignment.MiddleCenter;
            NavButton_Item.TextAlignment = HorizontalAlignment.Center;
            NavButton_Item.TextMarginLeft = 0;
            NavButton_Item.TextPadding = new Padding(0);
            NavButton_Item.UseDefaultRadiusAndThickness = true;
            NavButton_Item.Click += NavButton_Item_Click;
            // 
            // NavButton_Home
            // 
            NavButton_Home.AllowAnimations = true;
            NavButton_Home.AllowMouseEffects = true;
            NavButton_Home.AllowToggling = false;
            NavButton_Home.AnimationSpeed = 200;
            NavButton_Home.AutoGenerateColors = false;
            NavButton_Home.AutoRoundBorders = false;
            NavButton_Home.AutoSizeLeftIcon = true;
            NavButton_Home.AutoSizeRightIcon = true;
            NavButton_Home.BackColor = Color.Transparent;
            NavButton_Home.BackColor1 = Color.Transparent;
            NavButton_Home.BackgroundImage = (Image)resources.GetObject("NavButton_Home.BackgroundImage");
            NavButton_Home.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Home.ButtonText = "Home";
            NavButton_Home.ButtonTextMarginLeft = 0;
            NavButton_Home.ColorContrastOnClick = 45;
            NavButton_Home.ColorContrastOnHover = 45;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            NavButton_Home.CustomizableEdges = borderEdges13;
            NavButton_Home.DialogResult = DialogResult.None;
            NavButton_Home.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Home.DisabledFillColor = Color.FromArgb(204, 204, 204);
            NavButton_Home.DisabledForecolor = Color.FromArgb(168, 160, 168);
            NavButton_Home.Dock = DockStyle.Top;
            NavButton_Home.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            NavButton_Home.Font = new Font("Times New Roman", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            NavButton_Home.ForeColor = Color.White;
            NavButton_Home.IconLeftAlign = ContentAlignment.MiddleLeft;
            NavButton_Home.IconLeftCursor = Cursors.Default;
            NavButton_Home.IconLeftPadding = new Padding(11, 3, 3, 3);
            NavButton_Home.IconMarginLeft = 11;
            NavButton_Home.IconPadding = 10;
            NavButton_Home.IconRightAlign = ContentAlignment.MiddleRight;
            NavButton_Home.IconRightCursor = Cursors.Default;
            NavButton_Home.IconRightPadding = new Padding(3, 3, 7, 3);
            NavButton_Home.IconSize = 25;
            NavButton_Home.IdleBorderColor = Color.Transparent;
            NavButton_Home.IdleBorderRadius = 1;
            NavButton_Home.IdleBorderThickness = 1;
            NavButton_Home.IdleFillColor = Color.Transparent;
            NavButton_Home.IdleIconLeftImage = null;
            NavButton_Home.IdleIconRightImage = null;
            NavButton_Home.IndicateFocus = false;
            NavButton_Home.Location = new Point(0, 20);
            NavButton_Home.Name = "NavButton_Home";
            NavButton_Home.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Home.OnDisabledState.BorderRadius = 1;
            NavButton_Home.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Home.OnDisabledState.BorderThickness = 1;
            NavButton_Home.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            NavButton_Home.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            NavButton_Home.OnDisabledState.IconLeftImage = null;
            NavButton_Home.OnDisabledState.IconRightImage = null;
            NavButton_Home.onHoverState.BorderColor = Color.Transparent;
            NavButton_Home.onHoverState.BorderRadius = 1;
            NavButton_Home.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Home.onHoverState.BorderThickness = 1;
            NavButton_Home.onHoverState.FillColor = Color.FromArgb(251, 205, 119);
            NavButton_Home.onHoverState.ForeColor = Color.Black;
            NavButton_Home.onHoverState.IconLeftImage = null;
            NavButton_Home.onHoverState.IconRightImage = null;
            NavButton_Home.OnIdleState.BorderColor = Color.Transparent;
            NavButton_Home.OnIdleState.BorderRadius = 1;
            NavButton_Home.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Home.OnIdleState.BorderThickness = 1;
            NavButton_Home.OnIdleState.FillColor = Color.Transparent;
            NavButton_Home.OnIdleState.ForeColor = Color.White;
            NavButton_Home.OnIdleState.IconLeftImage = null;
            NavButton_Home.OnIdleState.IconRightImage = null;
            NavButton_Home.OnPressedState.BorderColor = Color.FromArgb(198, 40, 40);
            NavButton_Home.OnPressedState.BorderRadius = 1;
            NavButton_Home.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Home.OnPressedState.BorderThickness = 1;
            NavButton_Home.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            NavButton_Home.OnPressedState.ForeColor = Color.White;
            NavButton_Home.OnPressedState.IconLeftImage = null;
            NavButton_Home.OnPressedState.IconRightImage = null;
            NavButton_Home.Size = new Size(200, 40);
            NavButton_Home.TabIndex = 0;
            NavButton_Home.TextAlign = ContentAlignment.MiddleCenter;
            NavButton_Home.TextAlignment = HorizontalAlignment.Center;
            NavButton_Home.TextMarginLeft = 0;
            NavButton_Home.TextPadding = new Padding(0);
            NavButton_Home.UseDefaultRadiusAndThickness = true;
            // 
            // MainContainer
            // 
            MainContainer.Dock = DockStyle.Fill;
            MainContainer.Location = new Point(200, 30);
            MainContainer.Name = "MainContainer";
            MainContainer.Padding = new Padding(10);
            MainContainer.Size = new Size(900, 670);
            MainContainer.TabIndex = 4;
            // 
            // FormDragFeature
            // 
            FormDragFeature.AllowOpacityChangesWhileDragging = false;
            FormDragFeature.ContainerControl = this;
            FormDragFeature.DockIndicatorsOpacity = 0.5D;
            FormDragFeature.DockingIndicatorsColor = Color.FromArgb(202, 215, 233);
            FormDragFeature.DockingOptions.DockAll = false;
            FormDragFeature.DockingOptions.DockBottomLeft = false;
            FormDragFeature.DockingOptions.DockBottomRight = false;
            FormDragFeature.DockingOptions.DockFullScreen = false;
            FormDragFeature.DockingOptions.DockLeft = false;
            FormDragFeature.DockingOptions.DockRight = false;
            FormDragFeature.DockingOptions.DockTopLeft = false;
            FormDragFeature.DockingOptions.DockTopRight = false;
            FormDragFeature.DragOpacity = 0.9D;
            FormDragFeature.Enabled = false;
            FormDragFeature.ParentForm = this;
            FormDragFeature.ShowCursorChanges = true;
            FormDragFeature.ShowDockingIndicators = true;
            FormDragFeature.TitleBarOptions.BunifuFormDrag = FormDragFeature;
            FormDragFeature.TitleBarOptions.DoubleClickToExpandWindow = false;
            FormDragFeature.TitleBarOptions.Enabled = true;
            FormDragFeature.TitleBarOptions.TitleBarControl = TopNav;
            FormDragFeature.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // LogOut_btn
            // 
            LogOut_btn.AllowAnimations = true;
            LogOut_btn.AllowMouseEffects = true;
            LogOut_btn.AllowToggling = false;
            LogOut_btn.AnimationSpeed = 200;
            LogOut_btn.AutoGenerateColors = false;
            LogOut_btn.AutoRoundBorders = false;
            LogOut_btn.AutoSizeLeftIcon = true;
            LogOut_btn.AutoSizeRightIcon = true;
            LogOut_btn.BackColor = Color.Transparent;
            LogOut_btn.BackColor1 = Color.Transparent;
            LogOut_btn.BackgroundImage = (Image)resources.GetObject("LogOut_btn.BackgroundImage");
            LogOut_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            LogOut_btn.ButtonText = "Log Out";
            LogOut_btn.ButtonTextMarginLeft = 0;
            LogOut_btn.ColorContrastOnClick = 45;
            LogOut_btn.ColorContrastOnHover = 45;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            LogOut_btn.CustomizableEdges = borderEdges14;
            LogOut_btn.DialogResult = DialogResult.None;
            LogOut_btn.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            LogOut_btn.DisabledFillColor = Color.FromArgb(204, 204, 204);
            LogOut_btn.DisabledForecolor = Color.FromArgb(168, 160, 168);
            LogOut_btn.Dock = DockStyle.Top;
            LogOut_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            LogOut_btn.Font = new Font("Times New Roman", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            LogOut_btn.ForeColor = Color.White;
            LogOut_btn.IconLeftAlign = ContentAlignment.MiddleLeft;
            LogOut_btn.IconLeftCursor = Cursors.Default;
            LogOut_btn.IconLeftPadding = new Padding(11, 3, 3, 3);
            LogOut_btn.IconMarginLeft = 11;
            LogOut_btn.IconPadding = 10;
            LogOut_btn.IconRightAlign = ContentAlignment.MiddleRight;
            LogOut_btn.IconRightCursor = Cursors.Default;
            LogOut_btn.IconRightPadding = new Padding(3, 3, 7, 3);
            LogOut_btn.IconSize = 25;
            LogOut_btn.IdleBorderColor = Color.Transparent;
            LogOut_btn.IdleBorderRadius = 1;
            LogOut_btn.IdleBorderThickness = 1;
            LogOut_btn.IdleFillColor = Color.Transparent;
            LogOut_btn.IdleIconLeftImage = null;
            LogOut_btn.IdleIconRightImage = null;
            LogOut_btn.IndicateFocus = false;
            LogOut_btn.Location = new Point(0, 220);
            LogOut_btn.Name = "LogOut_btn";
            LogOut_btn.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            LogOut_btn.OnDisabledState.BorderRadius = 1;
            LogOut_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            LogOut_btn.OnDisabledState.BorderThickness = 1;
            LogOut_btn.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            LogOut_btn.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            LogOut_btn.OnDisabledState.IconLeftImage = null;
            LogOut_btn.OnDisabledState.IconRightImage = null;
            LogOut_btn.onHoverState.BorderColor = Color.Transparent;
            LogOut_btn.onHoverState.BorderRadius = 1;
            LogOut_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            LogOut_btn.onHoverState.BorderThickness = 1;
            LogOut_btn.onHoverState.FillColor = Color.FromArgb(251, 205, 119);
            LogOut_btn.onHoverState.ForeColor = Color.Black;
            LogOut_btn.onHoverState.IconLeftImage = null;
            LogOut_btn.onHoverState.IconRightImage = null;
            LogOut_btn.OnIdleState.BorderColor = Color.Transparent;
            LogOut_btn.OnIdleState.BorderRadius = 1;
            LogOut_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            LogOut_btn.OnIdleState.BorderThickness = 1;
            LogOut_btn.OnIdleState.FillColor = Color.Transparent;
            LogOut_btn.OnIdleState.ForeColor = Color.White;
            LogOut_btn.OnIdleState.IconLeftImage = null;
            LogOut_btn.OnIdleState.IconRightImage = null;
            LogOut_btn.OnPressedState.BorderColor = Color.FromArgb(198, 40, 40);
            LogOut_btn.OnPressedState.BorderRadius = 1;
            LogOut_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            LogOut_btn.OnPressedState.BorderThickness = 1;
            LogOut_btn.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            LogOut_btn.OnPressedState.ForeColor = Color.White;
            LogOut_btn.OnPressedState.IconLeftImage = null;
            LogOut_btn.OnPressedState.IconRightImage = null;
            LogOut_btn.Size = new Size(200, 40);
            LogOut_btn.TabIndex = 5;
            LogOut_btn.TextAlign = ContentAlignment.MiddleCenter;
            LogOut_btn.TextAlignment = HorizontalAlignment.Center;
            LogOut_btn.TextMarginLeft = 0;
            LogOut_btn.TextPadding = new Padding(0);
            LogOut_btn.UseDefaultRadiusAndThickness = true;
            // 
            // MainPage
            // 
            AutoScaleDimensions = new SizeF(8F, 17F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            ClientSize = new Size(1100, 700);
            Controls.Add(MainContainer);
            Controls.Add(SideNav);
            Controls.Add(TopNav);
            Font = new Font("Times New Roman", 11.25F, FontStyle.Regular, GraphicsUnit.Point, 0);
            FormBorderStyle = FormBorderStyle.None;
            Icon = (Icon)resources.GetObject("$this.Icon");
            Margin = new Padding(4);
            Name = "MainPage";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Daza's Best";
            Load += MainPage_Load;
            TopNav.ResumeLayout(false);
            SideNav.ResumeLayout(false);
            ResumeLayout(false);
        }

        #endregion

        private Panel TopNav;
        private Panel SideNav;
        private Panel MainContainer;
        private Bunifu.UI.WinForms.BunifuLabel CompanyName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 NavButton_Home;
        private Bunifu.UI.WinForms.BunifuFormControlBox FormControlBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton bunifuIconButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 NavButton_Reports;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 NavButton_Products;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 NavButton_Item;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuFormDrag FormDragFeature;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 LogOut_btn;
    }
}
