namespace DazaBestApplication
{
    partial class MainPage
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainPage));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            SideNav = new Panel();
            NavButton_PurchaseItem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            LogOut_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            NavButton_Reports = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            NavButton_Products = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            NavButton_Item = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            NavButton_Home = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            MainContainer = new Panel();
            FormDragFeature = new Bunifu.UI.WinForms.BunifuFormDrag();
            sqliteCommand1 = new Microsoft.Data.Sqlite.SqliteCommand();
            POSButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            SideNav.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)bunifuPictureBox1).BeginInit();
            SuspendLayout();
            // 
            // SideNav
            // 
            SideNav.BackColor = Color.FromArgb(67, 66, 66);
            SideNav.Controls.Add(POSButton);
            SideNav.Controls.Add(NavButton_PurchaseItem);
            SideNav.Controls.Add(bunifuPictureBox1);
            SideNav.Controls.Add(LogOut_btn);
            SideNav.Controls.Add(bunifuButton21);
            SideNav.Controls.Add(NavButton_Reports);
            SideNav.Controls.Add(NavButton_Products);
            SideNav.Controls.Add(NavButton_Item);
            SideNav.Controls.Add(NavButton_Home);
            SideNav.Dock = DockStyle.Left;
            SideNav.Font = new Font("Courier New", 12F, FontStyle.Bold);
            SideNav.Location = new Point(0, 0);
            SideNav.Name = "SideNav";
            SideNav.Padding = new Padding(0, 20, 0, 10);
            SideNav.Size = new Size(200, 700);
            SideNav.TabIndex = 3;
            // 
            // NavButton_PurchaseItem
            // 
            NavButton_PurchaseItem.AllowAnimations = true;
            NavButton_PurchaseItem.AllowMouseEffects = true;
            NavButton_PurchaseItem.AllowToggling = false;
            NavButton_PurchaseItem.AnimationSpeed = 200;
            NavButton_PurchaseItem.AutoGenerateColors = false;
            NavButton_PurchaseItem.AutoRoundBorders = false;
            NavButton_PurchaseItem.AutoSizeLeftIcon = true;
            NavButton_PurchaseItem.AutoSizeRightIcon = true;
            NavButton_PurchaseItem.BackColor = Color.Transparent;
            NavButton_PurchaseItem.BackColor1 = Color.Transparent;
            NavButton_PurchaseItem.BackgroundImage = (Image)resources.GetObject("NavButton_PurchaseItem.BackgroundImage");
            NavButton_PurchaseItem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_PurchaseItem.ButtonText = "Item Adjustment";
            NavButton_PurchaseItem.ButtonTextMarginLeft = 0;
            NavButton_PurchaseItem.ColorContrastOnClick = 45;
            NavButton_PurchaseItem.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            NavButton_PurchaseItem.CustomizableEdges = borderEdges2;
            NavButton_PurchaseItem.DialogResult = DialogResult.None;
            NavButton_PurchaseItem.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            NavButton_PurchaseItem.DisabledFillColor = Color.FromArgb(204, 204, 204);
            NavButton_PurchaseItem.DisabledForecolor = Color.FromArgb(168, 160, 168);
            NavButton_PurchaseItem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            NavButton_PurchaseItem.Font = new Font("Courier New", 12F, FontStyle.Bold);
            NavButton_PurchaseItem.ForeColor = Color.White;
            NavButton_PurchaseItem.IconLeftAlign = ContentAlignment.MiddleLeft;
            NavButton_PurchaseItem.IconLeftCursor = Cursors.Default;
            NavButton_PurchaseItem.IconLeftPadding = new Padding(11, 3, 3, 3);
            NavButton_PurchaseItem.IconMarginLeft = 11;
            NavButton_PurchaseItem.IconPadding = 10;
            NavButton_PurchaseItem.IconRightAlign = ContentAlignment.MiddleRight;
            NavButton_PurchaseItem.IconRightCursor = Cursors.Default;
            NavButton_PurchaseItem.IconRightPadding = new Padding(3, 3, 7, 3);
            NavButton_PurchaseItem.IconSize = 25;
            NavButton_PurchaseItem.IdleBorderColor = Color.Transparent;
            NavButton_PurchaseItem.IdleBorderRadius = 1;
            NavButton_PurchaseItem.IdleBorderThickness = 2;
            NavButton_PurchaseItem.IdleFillColor = Color.Transparent;
            NavButton_PurchaseItem.IdleIconLeftImage = Properties.Resources.logistics__1_;
            NavButton_PurchaseItem.IdleIconRightImage = null;
            NavButton_PurchaseItem.IndicateFocus = false;
            NavButton_PurchaseItem.Location = new Point(0, 308);
            NavButton_PurchaseItem.Name = "NavButton_PurchaseItem";
            NavButton_PurchaseItem.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            NavButton_PurchaseItem.OnDisabledState.BorderRadius = 1;
            NavButton_PurchaseItem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_PurchaseItem.OnDisabledState.BorderThickness = 2;
            NavButton_PurchaseItem.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            NavButton_PurchaseItem.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            NavButton_PurchaseItem.OnDisabledState.IconLeftImage = null;
            NavButton_PurchaseItem.OnDisabledState.IconRightImage = null;
            NavButton_PurchaseItem.onHoverState.BorderColor = Color.Black;
            NavButton_PurchaseItem.onHoverState.BorderRadius = 1;
            NavButton_PurchaseItem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_PurchaseItem.onHoverState.BorderThickness = 2;
            NavButton_PurchaseItem.onHoverState.FillColor = Color.FromArgb(255, 240, 221);
            NavButton_PurchaseItem.onHoverState.ForeColor = Color.Black;
            NavButton_PurchaseItem.onHoverState.IconLeftImage = Properties.Resources.logistics;
            NavButton_PurchaseItem.onHoverState.IconRightImage = null;
            NavButton_PurchaseItem.OnIdleState.BorderColor = Color.Transparent;
            NavButton_PurchaseItem.OnIdleState.BorderRadius = 1;
            NavButton_PurchaseItem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_PurchaseItem.OnIdleState.BorderThickness = 2;
            NavButton_PurchaseItem.OnIdleState.FillColor = Color.Transparent;
            NavButton_PurchaseItem.OnIdleState.ForeColor = Color.White;
            NavButton_PurchaseItem.OnIdleState.IconLeftImage = Properties.Resources.logistics__1_;
            NavButton_PurchaseItem.OnIdleState.IconRightImage = null;
            NavButton_PurchaseItem.OnPressedState.BorderColor = Color.Black;
            NavButton_PurchaseItem.OnPressedState.BorderRadius = 1;
            NavButton_PurchaseItem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_PurchaseItem.OnPressedState.BorderThickness = 2;
            NavButton_PurchaseItem.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            NavButton_PurchaseItem.OnPressedState.ForeColor = Color.White;
            NavButton_PurchaseItem.OnPressedState.IconLeftImage = Properties.Resources.logistics__1_;
            NavButton_PurchaseItem.OnPressedState.IconRightImage = null;
            NavButton_PurchaseItem.Size = new Size(200, 40);
            NavButton_PurchaseItem.TabIndex = 7;
            NavButton_PurchaseItem.TextAlign = ContentAlignment.MiddleLeft;
            NavButton_PurchaseItem.TextAlignment = HorizontalAlignment.Center;
            NavButton_PurchaseItem.TextMarginLeft = 0;
            NavButton_PurchaseItem.TextPadding = new Padding(35, 0, 0, 0);
            NavButton_PurchaseItem.UseDefaultRadiusAndThickness = true;
            NavButton_PurchaseItem.Click += NavButton_PurchaseItem_Click;
            // 
            // bunifuPictureBox1
            // 
            bunifuPictureBox1.AllowFocused = false;
            bunifuPictureBox1.AutoSizeHeight = true;
            bunifuPictureBox1.BorderRadius = 100;
            bunifuPictureBox1.Dock = DockStyle.Top;
            bunifuPictureBox1.Image = Properties.Resources.clean;
            bunifuPictureBox1.IsCircle = true;
            bunifuPictureBox1.Location = new Point(0, 20);
            bunifuPictureBox1.Name = "bunifuPictureBox1";
            bunifuPictureBox1.Size = new Size(200, 200);
            bunifuPictureBox1.SizeMode = PictureBoxSizeMode.Zoom;
            bunifuPictureBox1.TabIndex = 6;
            bunifuPictureBox1.TabStop = false;
            bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // LogOut_btn
            // 
            LogOut_btn.AllowAnimations = true;
            LogOut_btn.AllowMouseEffects = true;
            LogOut_btn.AllowToggling = false;
            LogOut_btn.AnimationSpeed = 200;
            LogOut_btn.AutoGenerateColors = false;
            LogOut_btn.AutoRoundBorders = false;
            LogOut_btn.AutoSizeLeftIcon = true;
            LogOut_btn.AutoSizeRightIcon = true;
            LogOut_btn.BackColor = Color.Transparent;
            LogOut_btn.BackColor1 = Color.Transparent;
            LogOut_btn.BackgroundImage = (Image)resources.GetObject("LogOut_btn.BackgroundImage");
            LogOut_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            LogOut_btn.ButtonText = "Log Out";
            LogOut_btn.ButtonTextMarginLeft = 0;
            LogOut_btn.ColorContrastOnClick = 45;
            LogOut_btn.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            LogOut_btn.CustomizableEdges = borderEdges3;
            LogOut_btn.DialogResult = DialogResult.None;
            LogOut_btn.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            LogOut_btn.DisabledFillColor = Color.FromArgb(204, 204, 204);
            LogOut_btn.DisabledForecolor = Color.FromArgb(168, 160, 168);
            LogOut_btn.Dock = DockStyle.Bottom;
            LogOut_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            LogOut_btn.Font = new Font("Courier New", 12F, FontStyle.Bold);
            LogOut_btn.ForeColor = Color.White;
            LogOut_btn.IconLeftAlign = ContentAlignment.MiddleLeft;
            LogOut_btn.IconLeftCursor = Cursors.Default;
            LogOut_btn.IconLeftPadding = new Padding(11, 3, 3, 3);
            LogOut_btn.IconMarginLeft = 11;
            LogOut_btn.IconPadding = 10;
            LogOut_btn.IconRightAlign = ContentAlignment.MiddleRight;
            LogOut_btn.IconRightCursor = Cursors.Default;
            LogOut_btn.IconRightPadding = new Padding(3, 3, 7, 3);
            LogOut_btn.IconSize = 25;
            LogOut_btn.IdleBorderColor = Color.White;
            LogOut_btn.IdleBorderRadius = 1;
            LogOut_btn.IdleBorderThickness = 2;
            LogOut_btn.IdleFillColor = Color.Transparent;
            LogOut_btn.IdleIconLeftImage = null;
            LogOut_btn.IdleIconRightImage = null;
            LogOut_btn.IndicateFocus = false;
            LogOut_btn.Location = new Point(0, 650);
            LogOut_btn.Name = "LogOut_btn";
            LogOut_btn.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            LogOut_btn.OnDisabledState.BorderRadius = 1;
            LogOut_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            LogOut_btn.OnDisabledState.BorderThickness = 2;
            LogOut_btn.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            LogOut_btn.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            LogOut_btn.OnDisabledState.IconLeftImage = null;
            LogOut_btn.OnDisabledState.IconRightImage = null;
            LogOut_btn.onHoverState.BorderColor = Color.Black;
            LogOut_btn.onHoverState.BorderRadius = 1;
            LogOut_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            LogOut_btn.onHoverState.BorderThickness = 2;
            LogOut_btn.onHoverState.FillColor = Color.FromArgb(255, 240, 221);
            LogOut_btn.onHoverState.ForeColor = Color.Black;
            LogOut_btn.onHoverState.IconLeftImage = null;
            LogOut_btn.onHoverState.IconRightImage = null;
            LogOut_btn.OnIdleState.BorderColor = Color.White;
            LogOut_btn.OnIdleState.BorderRadius = 1;
            LogOut_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            LogOut_btn.OnIdleState.BorderThickness = 2;
            LogOut_btn.OnIdleState.FillColor = Color.Transparent;
            LogOut_btn.OnIdleState.ForeColor = Color.White;
            LogOut_btn.OnIdleState.IconLeftImage = null;
            LogOut_btn.OnIdleState.IconRightImage = null;
            LogOut_btn.OnPressedState.BorderColor = Color.Black;
            LogOut_btn.OnPressedState.BorderRadius = 1;
            LogOut_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            LogOut_btn.OnPressedState.BorderThickness = 2;
            LogOut_btn.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            LogOut_btn.OnPressedState.ForeColor = Color.White;
            LogOut_btn.OnPressedState.IconLeftImage = null;
            LogOut_btn.OnPressedState.IconRightImage = null;
            LogOut_btn.Size = new Size(200, 40);
            LogOut_btn.TabIndex = 5;
            LogOut_btn.TextAlign = ContentAlignment.MiddleCenter;
            LogOut_btn.TextAlignment = HorizontalAlignment.Center;
            LogOut_btn.TextMarginLeft = 0;
            LogOut_btn.TextPadding = new Padding(0);
            LogOut_btn.UseDefaultRadiusAndThickness = true;
            LogOut_btn.Click += LogOut_btn_Click;
            // 
            // bunifuButton21
            // 
            bunifuButton21.AllowAnimations = true;
            bunifuButton21.AllowMouseEffects = true;
            bunifuButton21.AllowToggling = false;
            bunifuButton21.AnimationSpeed = 200;
            bunifuButton21.AutoGenerateColors = false;
            bunifuButton21.AutoRoundBorders = false;
            bunifuButton21.AutoSizeLeftIcon = true;
            bunifuButton21.AutoSizeRightIcon = true;
            bunifuButton21.BackColor = Color.Transparent;
            bunifuButton21.BackColor1 = Color.Transparent;
            bunifuButton21.BackgroundImage = (Image)resources.GetObject("bunifuButton21.BackgroundImage");
            bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.ButtonText = "Settings";
            bunifuButton21.ButtonTextMarginLeft = 0;
            bunifuButton21.ColorContrastOnClick = 45;
            bunifuButton21.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            bunifuButton21.CustomizableEdges = borderEdges4;
            bunifuButton21.DialogResult = DialogResult.None;
            bunifuButton21.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton21.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton21.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton21.Font = new Font("Courier New", 12F, FontStyle.Bold);
            bunifuButton21.ForeColor = Color.White;
            bunifuButton21.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton21.IconLeftCursor = Cursors.Default;
            bunifuButton21.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton21.IconMarginLeft = 11;
            bunifuButton21.IconPadding = 10;
            bunifuButton21.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton21.IconRightCursor = Cursors.Default;
            bunifuButton21.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton21.IconSize = 25;
            bunifuButton21.IdleBorderColor = Color.Transparent;
            bunifuButton21.IdleBorderRadius = 1;
            bunifuButton21.IdleBorderThickness = 2;
            bunifuButton21.IdleFillColor = Color.Transparent;
            bunifuButton21.IdleIconLeftImage = Properties.Resources.settings__1_;
            bunifuButton21.IdleIconRightImage = null;
            bunifuButton21.IndicateFocus = false;
            bunifuButton21.Location = new Point(-1, 429);
            bunifuButton21.Name = "bunifuButton21";
            bunifuButton21.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton21.OnDisabledState.BorderRadius = 1;
            bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.OnDisabledState.BorderThickness = 2;
            bunifuButton21.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton21.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton21.OnDisabledState.IconLeftImage = null;
            bunifuButton21.OnDisabledState.IconRightImage = null;
            bunifuButton21.onHoverState.BorderColor = Color.Black;
            bunifuButton21.onHoverState.BorderRadius = 1;
            bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.onHoverState.BorderThickness = 2;
            bunifuButton21.onHoverState.FillColor = Color.FromArgb(255, 240, 221);
            bunifuButton21.onHoverState.ForeColor = Color.Black;
            bunifuButton21.onHoverState.IconLeftImage = Properties.Resources.gear;
            bunifuButton21.onHoverState.IconRightImage = null;
            bunifuButton21.OnIdleState.BorderColor = Color.Transparent;
            bunifuButton21.OnIdleState.BorderRadius = 1;
            bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.OnIdleState.BorderThickness = 2;
            bunifuButton21.OnIdleState.FillColor = Color.Transparent;
            bunifuButton21.OnIdleState.ForeColor = Color.White;
            bunifuButton21.OnIdleState.IconLeftImage = Properties.Resources.settings__1_;
            bunifuButton21.OnIdleState.IconRightImage = null;
            bunifuButton21.OnPressedState.BorderColor = Color.Black;
            bunifuButton21.OnPressedState.BorderRadius = 1;
            bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.OnPressedState.BorderThickness = 2;
            bunifuButton21.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            bunifuButton21.OnPressedState.ForeColor = Color.White;
            bunifuButton21.OnPressedState.IconLeftImage = Properties.Resources.settings__1_;
            bunifuButton21.OnPressedState.IconRightImage = null;
            bunifuButton21.Size = new Size(200, 40);
            bunifuButton21.TabIndex = 4;
            bunifuButton21.TextAlign = ContentAlignment.MiddleLeft;
            bunifuButton21.TextAlignment = HorizontalAlignment.Center;
            bunifuButton21.TextMarginLeft = 0;
            bunifuButton21.TextPadding = new Padding(35, 0, 0, 0);
            bunifuButton21.UseDefaultRadiusAndThickness = true;
            bunifuButton21.Click += bunifuButton21_Click;
            // 
            // NavButton_Reports
            // 
            NavButton_Reports.AllowAnimations = true;
            NavButton_Reports.AllowMouseEffects = true;
            NavButton_Reports.AllowToggling = false;
            NavButton_Reports.AnimationSpeed = 200;
            NavButton_Reports.AutoGenerateColors = false;
            NavButton_Reports.AutoRoundBorders = false;
            NavButton_Reports.AutoSizeLeftIcon = true;
            NavButton_Reports.AutoSizeRightIcon = true;
            NavButton_Reports.BackColor = Color.Transparent;
            NavButton_Reports.BackColor1 = Color.Transparent;
            NavButton_Reports.BackgroundImage = (Image)resources.GetObject("NavButton_Reports.BackgroundImage");
            NavButton_Reports.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Reports.ButtonText = "Reports";
            NavButton_Reports.ButtonTextMarginLeft = 0;
            NavButton_Reports.ColorContrastOnClick = 45;
            NavButton_Reports.ColorContrastOnHover = 45;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            NavButton_Reports.CustomizableEdges = borderEdges5;
            NavButton_Reports.DialogResult = DialogResult.None;
            NavButton_Reports.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Reports.DisabledFillColor = Color.FromArgb(204, 204, 204);
            NavButton_Reports.DisabledForecolor = Color.FromArgb(168, 160, 168);
            NavButton_Reports.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            NavButton_Reports.Font = new Font("Courier New", 12F, FontStyle.Bold);
            NavButton_Reports.ForeColor = Color.White;
            NavButton_Reports.IconLeftAlign = ContentAlignment.MiddleLeft;
            NavButton_Reports.IconLeftCursor = Cursors.Default;
            NavButton_Reports.IconLeftPadding = new Padding(11, 3, 3, 3);
            NavButton_Reports.IconMarginLeft = 11;
            NavButton_Reports.IconPadding = 10;
            NavButton_Reports.IconRightAlign = ContentAlignment.MiddleRight;
            NavButton_Reports.IconRightCursor = Cursors.Default;
            NavButton_Reports.IconRightPadding = new Padding(3, 3, 7, 3);
            NavButton_Reports.IconSize = 25;
            NavButton_Reports.IdleBorderColor = Color.Transparent;
            NavButton_Reports.IdleBorderRadius = 1;
            NavButton_Reports.IdleBorderThickness = 2;
            NavButton_Reports.IdleFillColor = Color.Transparent;
            NavButton_Reports.IdleIconLeftImage = Properties.Resources.folder__1_;
            NavButton_Reports.IdleIconRightImage = null;
            NavButton_Reports.IndicateFocus = false;
            NavButton_Reports.Location = new Point(0, 389);
            NavButton_Reports.Name = "NavButton_Reports";
            NavButton_Reports.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Reports.OnDisabledState.BorderRadius = 1;
            NavButton_Reports.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Reports.OnDisabledState.BorderThickness = 2;
            NavButton_Reports.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            NavButton_Reports.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            NavButton_Reports.OnDisabledState.IconLeftImage = null;
            NavButton_Reports.OnDisabledState.IconRightImage = null;
            NavButton_Reports.onHoverState.BorderColor = Color.Black;
            NavButton_Reports.onHoverState.BorderRadius = 1;
            NavButton_Reports.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Reports.onHoverState.BorderThickness = 2;
            NavButton_Reports.onHoverState.FillColor = Color.FromArgb(255, 240, 221);
            NavButton_Reports.onHoverState.ForeColor = Color.Black;
            NavButton_Reports.onHoverState.IconLeftImage = Properties.Resources.folder;
            NavButton_Reports.onHoverState.IconRightImage = null;
            NavButton_Reports.OnIdleState.BorderColor = Color.Transparent;
            NavButton_Reports.OnIdleState.BorderRadius = 1;
            NavButton_Reports.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Reports.OnIdleState.BorderThickness = 2;
            NavButton_Reports.OnIdleState.FillColor = Color.Transparent;
            NavButton_Reports.OnIdleState.ForeColor = Color.White;
            NavButton_Reports.OnIdleState.IconLeftImage = Properties.Resources.folder__1_;
            NavButton_Reports.OnIdleState.IconRightImage = null;
            NavButton_Reports.OnPressedState.BorderColor = Color.Black;
            NavButton_Reports.OnPressedState.BorderRadius = 1;
            NavButton_Reports.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Reports.OnPressedState.BorderThickness = 2;
            NavButton_Reports.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            NavButton_Reports.OnPressedState.ForeColor = Color.White;
            NavButton_Reports.OnPressedState.IconLeftImage = Properties.Resources.folder__1_;
            NavButton_Reports.OnPressedState.IconRightImage = null;
            NavButton_Reports.Size = new Size(200, 40);
            NavButton_Reports.TabIndex = 3;
            NavButton_Reports.TextAlign = ContentAlignment.MiddleLeft;
            NavButton_Reports.TextAlignment = HorizontalAlignment.Center;
            NavButton_Reports.TextMarginLeft = 0;
            NavButton_Reports.TextPadding = new Padding(35, 0, 0, 0);
            NavButton_Reports.UseDefaultRadiusAndThickness = true;
            // 
            // NavButton_Products
            // 
            NavButton_Products.AllowAnimations = true;
            NavButton_Products.AllowMouseEffects = true;
            NavButton_Products.AllowToggling = false;
            NavButton_Products.AnimationSpeed = 200;
            NavButton_Products.AutoGenerateColors = false;
            NavButton_Products.AutoRoundBorders = false;
            NavButton_Products.AutoSizeLeftIcon = true;
            NavButton_Products.AutoSizeRightIcon = true;
            NavButton_Products.BackColor = Color.Transparent;
            NavButton_Products.BackColor1 = Color.Transparent;
            NavButton_Products.BackgroundImage = (Image)resources.GetObject("NavButton_Products.BackgroundImage");
            NavButton_Products.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Products.ButtonText = "Products";
            NavButton_Products.ButtonTextMarginLeft = 0;
            NavButton_Products.ColorContrastOnClick = 45;
            NavButton_Products.ColorContrastOnHover = 45;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            NavButton_Products.CustomizableEdges = borderEdges6;
            NavButton_Products.DialogResult = DialogResult.None;
            NavButton_Products.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Products.DisabledFillColor = Color.FromArgb(204, 204, 204);
            NavButton_Products.DisabledForecolor = Color.FromArgb(168, 160, 168);
            NavButton_Products.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            NavButton_Products.Font = new Font("Courier New", 12F, FontStyle.Bold);
            NavButton_Products.ForeColor = Color.White;
            NavButton_Products.IconLeftAlign = ContentAlignment.MiddleLeft;
            NavButton_Products.IconLeftCursor = Cursors.NoMoveHoriz;
            NavButton_Products.IconLeftPadding = new Padding(11, 3, 3, 3);
            NavButton_Products.IconMarginLeft = 11;
            NavButton_Products.IconPadding = 10;
            NavButton_Products.IconRightAlign = ContentAlignment.MiddleRight;
            NavButton_Products.IconRightCursor = Cursors.Default;
            NavButton_Products.IconRightPadding = new Padding(3, 3, 7, 3);
            NavButton_Products.IconSize = 25;
            NavButton_Products.IdleBorderColor = Color.Transparent;
            NavButton_Products.IdleBorderRadius = 1;
            NavButton_Products.IdleBorderThickness = 2;
            NavButton_Products.IdleFillColor = Color.Transparent;
            NavButton_Products.IdleIconLeftImage = Properties.Resources.clipboard__1_;
            NavButton_Products.IdleIconRightImage = null;
            NavButton_Products.IndicateFocus = false;
            NavButton_Products.Location = new Point(0, 349);
            NavButton_Products.Name = "NavButton_Products";
            NavButton_Products.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Products.OnDisabledState.BorderRadius = 1;
            NavButton_Products.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Products.OnDisabledState.BorderThickness = 2;
            NavButton_Products.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            NavButton_Products.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            NavButton_Products.OnDisabledState.IconLeftImage = null;
            NavButton_Products.OnDisabledState.IconRightImage = null;
            NavButton_Products.onHoverState.BorderColor = Color.Black;
            NavButton_Products.onHoverState.BorderRadius = 1;
            NavButton_Products.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Products.onHoverState.BorderThickness = 2;
            NavButton_Products.onHoverState.FillColor = Color.FromArgb(255, 240, 221);
            NavButton_Products.onHoverState.ForeColor = Color.Black;
            NavButton_Products.onHoverState.IconLeftImage = Properties.Resources.clipboard;
            NavButton_Products.onHoverState.IconRightImage = null;
            NavButton_Products.OnIdleState.BorderColor = Color.Transparent;
            NavButton_Products.OnIdleState.BorderRadius = 1;
            NavButton_Products.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Products.OnIdleState.BorderThickness = 2;
            NavButton_Products.OnIdleState.FillColor = Color.Transparent;
            NavButton_Products.OnIdleState.ForeColor = Color.White;
            NavButton_Products.OnIdleState.IconLeftImage = Properties.Resources.clipboard__1_;
            NavButton_Products.OnIdleState.IconRightImage = null;
            NavButton_Products.OnPressedState.BorderColor = Color.Black;
            NavButton_Products.OnPressedState.BorderRadius = 1;
            NavButton_Products.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Products.OnPressedState.BorderThickness = 2;
            NavButton_Products.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            NavButton_Products.OnPressedState.ForeColor = Color.White;
            NavButton_Products.OnPressedState.IconLeftImage = Properties.Resources.clipboard__1_;
            NavButton_Products.OnPressedState.IconRightImage = null;
            NavButton_Products.Size = new Size(200, 40);
            NavButton_Products.TabIndex = 2;
            NavButton_Products.TextAlign = ContentAlignment.MiddleLeft;
            NavButton_Products.TextAlignment = HorizontalAlignment.Center;
            NavButton_Products.TextMarginLeft = 0;
            NavButton_Products.TextPadding = new Padding(35, 0, 0, 0);
            NavButton_Products.UseDefaultRadiusAndThickness = true;
            NavButton_Products.Click += NavButton_Products_Click;
            // 
            // NavButton_Item
            // 
            NavButton_Item.AllowAnimations = true;
            NavButton_Item.AllowMouseEffects = true;
            NavButton_Item.AllowToggling = false;
            NavButton_Item.AnimationSpeed = 200;
            NavButton_Item.AutoGenerateColors = false;
            NavButton_Item.AutoRoundBorders = false;
            NavButton_Item.AutoSizeLeftIcon = true;
            NavButton_Item.AutoSizeRightIcon = true;
            NavButton_Item.BackColor = Color.Transparent;
            NavButton_Item.BackColor1 = Color.Transparent;
            NavButton_Item.BackgroundImage = (Image)resources.GetObject("NavButton_Item.BackgroundImage");
            NavButton_Item.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Item.ButtonText = "Inventory";
            NavButton_Item.ButtonTextMarginLeft = 0;
            NavButton_Item.ColorContrastOnClick = 45;
            NavButton_Item.ColorContrastOnHover = 45;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            NavButton_Item.CustomizableEdges = borderEdges7;
            NavButton_Item.DialogResult = DialogResult.None;
            NavButton_Item.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Item.DisabledFillColor = Color.FromArgb(204, 204, 204);
            NavButton_Item.DisabledForecolor = Color.FromArgb(168, 160, 168);
            NavButton_Item.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            NavButton_Item.Font = new Font("Courier New", 12F, FontStyle.Bold);
            NavButton_Item.ForeColor = Color.White;
            NavButton_Item.IconLeftAlign = ContentAlignment.MiddleLeft;
            NavButton_Item.IconLeftCursor = Cursors.Default;
            NavButton_Item.IconLeftPadding = new Padding(11, 3, 3, 3);
            NavButton_Item.IconMarginLeft = 11;
            NavButton_Item.IconPadding = 10;
            NavButton_Item.IconRightAlign = ContentAlignment.MiddleRight;
            NavButton_Item.IconRightCursor = Cursors.Default;
            NavButton_Item.IconRightPadding = new Padding(3, 3, 7, 3);
            NavButton_Item.IconSize = 25;
            NavButton_Item.IdleBorderColor = Color.Transparent;
            NavButton_Item.IdleBorderRadius = 1;
            NavButton_Item.IdleBorderThickness = 2;
            NavButton_Item.IdleFillColor = Color.Transparent;
            NavButton_Item.IdleIconLeftImage = Properties.Resources.clipboard__1_;
            NavButton_Item.IdleIconRightImage = null;
            NavButton_Item.IndicateFocus = false;
            NavButton_Item.Location = new Point(0, 267);
            NavButton_Item.Name = "NavButton_Item";
            NavButton_Item.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Item.OnDisabledState.BorderRadius = 1;
            NavButton_Item.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Item.OnDisabledState.BorderThickness = 2;
            NavButton_Item.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            NavButton_Item.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            NavButton_Item.OnDisabledState.IconLeftImage = null;
            NavButton_Item.OnDisabledState.IconRightImage = null;
            NavButton_Item.onHoverState.BorderColor = Color.Black;
            NavButton_Item.onHoverState.BorderRadius = 1;
            NavButton_Item.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Item.onHoverState.BorderThickness = 2;
            NavButton_Item.onHoverState.FillColor = Color.FromArgb(255, 240, 221);
            NavButton_Item.onHoverState.ForeColor = Color.Black;
            NavButton_Item.onHoverState.IconLeftImage = Properties.Resources.clipboard;
            NavButton_Item.onHoverState.IconRightImage = null;
            NavButton_Item.OnIdleState.BorderColor = Color.Transparent;
            NavButton_Item.OnIdleState.BorderRadius = 1;
            NavButton_Item.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Item.OnIdleState.BorderThickness = 2;
            NavButton_Item.OnIdleState.FillColor = Color.Transparent;
            NavButton_Item.OnIdleState.ForeColor = Color.White;
            NavButton_Item.OnIdleState.IconLeftImage = Properties.Resources.clipboard__1_;
            NavButton_Item.OnIdleState.IconRightImage = null;
            NavButton_Item.OnPressedState.BorderColor = Color.Black;
            NavButton_Item.OnPressedState.BorderRadius = 1;
            NavButton_Item.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Item.OnPressedState.BorderThickness = 2;
            NavButton_Item.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            NavButton_Item.OnPressedState.ForeColor = Color.White;
            NavButton_Item.OnPressedState.IconLeftImage = Properties.Resources.clipboard__1_;
            NavButton_Item.OnPressedState.IconRightImage = null;
            NavButton_Item.Size = new Size(200, 40);
            NavButton_Item.TabIndex = 1;
            NavButton_Item.TextAlign = ContentAlignment.MiddleLeft;
            NavButton_Item.TextAlignment = HorizontalAlignment.Center;
            NavButton_Item.TextMarginLeft = 0;
            NavButton_Item.TextPadding = new Padding(35, 0, 0, 0);
            NavButton_Item.UseDefaultRadiusAndThickness = true;
            NavButton_Item.Click += NavButton_Item_Click;
            // 
            // NavButton_Home
            // 
            NavButton_Home.AllowAnimations = true;
            NavButton_Home.AllowMouseEffects = true;
            NavButton_Home.AllowToggling = false;
            NavButton_Home.AnimationSpeed = 200;
            NavButton_Home.AutoGenerateColors = false;
            NavButton_Home.AutoRoundBorders = false;
            NavButton_Home.AutoSizeLeftIcon = true;
            NavButton_Home.AutoSizeRightIcon = true;
            NavButton_Home.BackColor = Color.Transparent;
            NavButton_Home.BackColor1 = Color.Transparent;
            NavButton_Home.BackgroundImage = (Image)resources.GetObject("NavButton_Home.BackgroundImage");
            NavButton_Home.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Home.ButtonText = "Dashboard";
            NavButton_Home.ButtonTextMarginLeft = 0;
            NavButton_Home.ColorContrastOnClick = 45;
            NavButton_Home.ColorContrastOnHover = 45;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            NavButton_Home.CustomizableEdges = borderEdges8;
            NavButton_Home.DialogResult = DialogResult.None;
            NavButton_Home.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Home.DisabledFillColor = Color.FromArgb(204, 204, 204);
            NavButton_Home.DisabledForecolor = Color.FromArgb(168, 160, 168);
            NavButton_Home.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            NavButton_Home.Font = new Font("Courier New", 12F, FontStyle.Bold);
            NavButton_Home.ForeColor = Color.White;
            NavButton_Home.IconLeftAlign = ContentAlignment.MiddleLeft;
            NavButton_Home.IconLeftCursor = Cursors.Default;
            NavButton_Home.IconLeftPadding = new Padding(11, 3, 3, 3);
            NavButton_Home.IconMarginLeft = 11;
            NavButton_Home.IconPadding = 10;
            NavButton_Home.IconRightAlign = ContentAlignment.MiddleRight;
            NavButton_Home.IconRightCursor = Cursors.Default;
            NavButton_Home.IconRightPadding = new Padding(3, 3, 7, 3);
            NavButton_Home.IconSize = 25;
            NavButton_Home.IdleBorderColor = Color.Transparent;
            NavButton_Home.IdleBorderRadius = 1;
            NavButton_Home.IdleBorderThickness = 2;
            NavButton_Home.IdleFillColor = Color.Transparent;
            NavButton_Home.IdleIconLeftImage = Properties.Resources.speedometer__1___1_;
            NavButton_Home.IdleIconRightImage = null;
            NavButton_Home.IndicateFocus = false;
            NavButton_Home.Location = new Point(0, 227);
            NavButton_Home.Name = "NavButton_Home";
            NavButton_Home.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            NavButton_Home.OnDisabledState.BorderRadius = 1;
            NavButton_Home.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Home.OnDisabledState.BorderThickness = 2;
            NavButton_Home.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            NavButton_Home.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            NavButton_Home.OnDisabledState.IconLeftImage = null;
            NavButton_Home.OnDisabledState.IconRightImage = null;
            NavButton_Home.onHoverState.BorderColor = Color.Black;
            NavButton_Home.onHoverState.BorderRadius = 1;
            NavButton_Home.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Home.onHoverState.BorderThickness = 2;
            NavButton_Home.onHoverState.FillColor = Color.FromArgb(255, 240, 221);
            NavButton_Home.onHoverState.ForeColor = Color.Black;
            NavButton_Home.onHoverState.IconLeftImage = Properties.Resources.speedometer__1_;
            NavButton_Home.onHoverState.IconRightImage = null;
            NavButton_Home.OnIdleState.BorderColor = Color.Transparent;
            NavButton_Home.OnIdleState.BorderRadius = 1;
            NavButton_Home.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Home.OnIdleState.BorderThickness = 2;
            NavButton_Home.OnIdleState.FillColor = Color.Transparent;
            NavButton_Home.OnIdleState.ForeColor = Color.White;
            NavButton_Home.OnIdleState.IconLeftImage = Properties.Resources.speedometer__1___1_;
            NavButton_Home.OnIdleState.IconRightImage = null;
            NavButton_Home.OnPressedState.BorderColor = Color.Black;
            NavButton_Home.OnPressedState.BorderRadius = 1;
            NavButton_Home.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            NavButton_Home.OnPressedState.BorderThickness = 2;
            NavButton_Home.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            NavButton_Home.OnPressedState.ForeColor = Color.White;
            NavButton_Home.OnPressedState.IconLeftImage = Properties.Resources.speedometer__1___1_;
            NavButton_Home.OnPressedState.IconRightImage = null;
            NavButton_Home.Size = new Size(200, 40);
            NavButton_Home.TabIndex = 0;
            NavButton_Home.TextAlign = ContentAlignment.MiddleLeft;
            NavButton_Home.TextAlignment = HorizontalAlignment.Center;
            NavButton_Home.TextMarginLeft = 0;
            NavButton_Home.TextPadding = new Padding(35, 0, 0, 0);
            NavButton_Home.UseDefaultRadiusAndThickness = true;
            NavButton_Home.Click += NavButton_Home_Click;
            // 
            // MainContainer
            // 
            MainContainer.Dock = DockStyle.Fill;
            MainContainer.Location = new Point(200, 0);
            MainContainer.Name = "MainContainer";
            MainContainer.Padding = new Padding(10);
            MainContainer.Size = new Size(900, 700);
            MainContainer.TabIndex = 4;
            // 
            // FormDragFeature
            // 
            FormDragFeature.AllowOpacityChangesWhileDragging = false;
            FormDragFeature.ContainerControl = this;
            FormDragFeature.DockIndicatorsOpacity = 0.5D;
            FormDragFeature.DockingIndicatorsColor = Color.FromArgb(202, 215, 233);
            FormDragFeature.DockingOptions.DockAll = false;
            FormDragFeature.DockingOptions.DockBottomLeft = false;
            FormDragFeature.DockingOptions.DockBottomRight = false;
            FormDragFeature.DockingOptions.DockFullScreen = false;
            FormDragFeature.DockingOptions.DockLeft = false;
            FormDragFeature.DockingOptions.DockRight = false;
            FormDragFeature.DockingOptions.DockTopLeft = false;
            FormDragFeature.DockingOptions.DockTopRight = false;
            FormDragFeature.DragOpacity = 0.9D;
            FormDragFeature.Enabled = false;
            FormDragFeature.ParentForm = this;
            FormDragFeature.ShowCursorChanges = true;
            FormDragFeature.ShowDockingIndicators = true;
            FormDragFeature.TitleBarOptions.BunifuFormDrag = FormDragFeature;
            FormDragFeature.TitleBarOptions.DoubleClickToExpandWindow = false;
            FormDragFeature.TitleBarOptions.Enabled = true;
            FormDragFeature.TitleBarOptions.TitleBarControl = null;
            FormDragFeature.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // sqliteCommand1
            // 
            sqliteCommand1.CommandTimeout = 30;
            sqliteCommand1.Connection = null;
            sqliteCommand1.Transaction = null;
            sqliteCommand1.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // POSButton
            // 
            POSButton.AllowAnimations = true;
            POSButton.AllowMouseEffects = true;
            POSButton.AllowToggling = false;
            POSButton.AnimationSpeed = 200;
            POSButton.AutoGenerateColors = false;
            POSButton.AutoRoundBorders = false;
            POSButton.AutoSizeLeftIcon = true;
            POSButton.AutoSizeRightIcon = true;
            POSButton.BackColor = Color.Transparent;
            POSButton.BackColor1 = Color.Transparent;
            POSButton.BackgroundImage = (Image)resources.GetObject("POSButton.BackgroundImage");
            POSButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            POSButton.ButtonText = "POS";
            POSButton.ButtonTextMarginLeft = 0;
            POSButton.ColorContrastOnClick = 45;
            POSButton.ColorContrastOnHover = 45;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            POSButton.CustomizableEdges = borderEdges1;
            POSButton.DialogResult = DialogResult.None;
            POSButton.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            POSButton.DisabledFillColor = Color.FromArgb(204, 204, 204);
            POSButton.DisabledForecolor = Color.FromArgb(168, 160, 168);
            POSButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            POSButton.Font = new Font("Courier New", 12F, FontStyle.Bold);
            POSButton.ForeColor = Color.White;
            POSButton.IconLeftAlign = ContentAlignment.MiddleLeft;
            POSButton.IconLeftCursor = Cursors.Default;
            POSButton.IconLeftPadding = new Padding(11, 3, 3, 3);
            POSButton.IconMarginLeft = 11;
            POSButton.IconPadding = 10;
            POSButton.IconRightAlign = ContentAlignment.MiddleRight;
            POSButton.IconRightCursor = Cursors.Default;
            POSButton.IconRightPadding = new Padding(3, 3, 7, 3);
            POSButton.IconSize = 25;
            POSButton.IdleBorderColor = Color.Transparent;
            POSButton.IdleBorderRadius = 1;
            POSButton.IdleBorderThickness = 2;
            POSButton.IdleFillColor = Color.Transparent;
            POSButton.IdleIconLeftImage = Properties.Resources.settings__1_;
            POSButton.IdleIconRightImage = null;
            POSButton.IndicateFocus = false;
            POSButton.Location = new Point(0, 470);
            POSButton.Name = "POSButton";
            POSButton.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            POSButton.OnDisabledState.BorderRadius = 1;
            POSButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            POSButton.OnDisabledState.BorderThickness = 2;
            POSButton.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            POSButton.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            POSButton.OnDisabledState.IconLeftImage = null;
            POSButton.OnDisabledState.IconRightImage = null;
            POSButton.onHoverState.BorderColor = Color.Black;
            POSButton.onHoverState.BorderRadius = 1;
            POSButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            POSButton.onHoverState.BorderThickness = 2;
            POSButton.onHoverState.FillColor = Color.FromArgb(255, 240, 221);
            POSButton.onHoverState.ForeColor = Color.Black;
            POSButton.onHoverState.IconLeftImage = Properties.Resources.gear;
            POSButton.onHoverState.IconRightImage = null;
            POSButton.OnIdleState.BorderColor = Color.Transparent;
            POSButton.OnIdleState.BorderRadius = 1;
            POSButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            POSButton.OnIdleState.BorderThickness = 2;
            POSButton.OnIdleState.FillColor = Color.Transparent;
            POSButton.OnIdleState.ForeColor = Color.White;
            POSButton.OnIdleState.IconLeftImage = Properties.Resources.settings__1_;
            POSButton.OnIdleState.IconRightImage = null;
            POSButton.OnPressedState.BorderColor = Color.Black;
            POSButton.OnPressedState.BorderRadius = 1;
            POSButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            POSButton.OnPressedState.BorderThickness = 2;
            POSButton.OnPressedState.FillColor = Color.FromArgb(198, 40, 40);
            POSButton.OnPressedState.ForeColor = Color.White;
            POSButton.OnPressedState.IconLeftImage = Properties.Resources.settings__1_;
            POSButton.OnPressedState.IconRightImage = null;
            POSButton.Size = new Size(200, 40);
            POSButton.TabIndex = 8;
            POSButton.TextAlign = ContentAlignment.MiddleLeft;
            POSButton.TextAlignment = HorizontalAlignment.Center;
            POSButton.TextMarginLeft = 0;
            POSButton.TextPadding = new Padding(35, 0, 0, 0);
            POSButton.UseDefaultRadiusAndThickness = true;
            POSButton.Click += POSButton_Click;
            // 
            // MainPage
            // 
            AutoScaleDimensions = new SizeF(8F, 17F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.White;
            ClientSize = new Size(1100, 700);
            Controls.Add(MainContainer);
            Controls.Add(SideNav);
            Font = new Font("Times New Roman", 11.25F, FontStyle.Regular, GraphicsUnit.Point, 0);
            FormBorderStyle = FormBorderStyle.None;
            Icon = (Icon)resources.GetObject("$this.Icon");
            Margin = new Padding(4);
            Name = "MainPage";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Daza's Best";
            Load += MainPage_Load;
            SideNav.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)bunifuPictureBox1).EndInit();
            ResumeLayout(false);
        }

        #endregion
        private Panel SideNav;
        private Panel MainContainer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 NavButton_Home;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 NavButton_Reports;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 NavButton_Products;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 NavButton_Item;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuFormDrag FormDragFeature;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 LogOut_btn;
        private Microsoft.Data.Sqlite.SqliteCommand sqliteCommand1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 NavButton_PurchaseItem;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 POSButton;
    }
}
