// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemBackEnd;

#nullable disable

namespace SystemBackEnd.Migrations
{
    [DbContext(typeof(BackEndDBContext))]
    [Migration("20251020133905_UnexpectedChanges")]
    partial class UnexpectedChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SystemBackEnd.Models.IngredientsByProduct", b =>
                {
                    b.Property<int>("Row")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientID")
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientsCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Row");

                    b.ToTable("IngredientsByProduct", (string)null);
                });

            modelBuilder.Entity("SystemBackEnd.Models.Items", b =>
                {
                    b.Property<int>("Row")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BalanceStocks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemID")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ItemImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ItemPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Row");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("SystemBackEnd.Models.POSPaymentTransaction", b =>
                {
                    b.Property<int>("Row")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Discount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaymentTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionHeaderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Row");

                    b.ToTable("POSPaymentTransaction", (string)null);
                });

            modelBuilder.Entity("SystemBackEnd.Models.POSTransactionDetails", b =>
                {
                    b.Property<int>("Row")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TransactionDetailsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionHeaderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Row");

                    b.ToTable("POSTransactionDetails", (string)null);
                });

            modelBuilder.Entity("SystemBackEnd.Models.POSTransactionHeader", b =>
                {
                    b.Property<int>("Row")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Grandtotal")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionHeaderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Row");

                    b.ToTable("POSTransactionHeader", (string)null);
                });

            modelBuilder.Entity("SystemBackEnd.Models.POSTransactionHistory", b =>
                {
                    b.Property<int>("Row")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TransactionHeaderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionHistoryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionHistoryDetails")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionHistoryTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("Row");

                    b.ToTable("POSTransactionHistory", (string)null);
                });

            modelBuilder.Entity("SystemBackEnd.Models.Products", b =>
                {
                    b.Property<int>("Row")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProductImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Row");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("SystemBackEnd.Models.PurchaseItemHeader", b =>
                {
                    b.Property<int>("Row")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Addedby")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dateverified")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Grandtotal")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Isverified")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Purchaseheaderid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purchasenumber")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Verifiedby")
                        .HasColumnType("TEXT");

                    b.HasKey("Row");

                    b.ToTable("PurcahseItemHeader", (string)null);
                });

            modelBuilder.Entity("SystemBackEnd.Models.PurchaseitemDetails", b =>
                {
                    b.Property<int>("Row")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemID")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Priceperunit")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Purchasedetailsid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Purchaseheaderid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Row");

                    b.ToTable("PurchaseItemDetails", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
