// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemBackEnd;

#nullable disable

namespace SystemBackEnd.Migrations
{
    [DbContext(typeof(BackEndDBContext))]
    [Migration("20250929145655_UpdatingGuidofItemID")]
    partial class UpdatingGuidofItemID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SystemBackEnd.Models.Items", b =>
                {
                    b.Property<int>("Row")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BalanceStocks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemID")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ItemImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ItemPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Row");

                    b.ToTable("Items", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
